### ISSUE TITLE
Add Terms of Service link

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#1]
<a href="https://github.com/mikejohnstn"><img src="https://avatars.githubusercontent.com/u/515035?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mikejohnstn](https://github.com/mikejohnstn)**
_Wednesday Feb 20, 2013 at 22:37 GMT_

---

Can be similar to iOS (subtle link when you create an account).

**Comment by jleandroperez** [comment]
Closing this one since the ToS are already available in two spots:

- The new about screen
- New onboarding (SignUp flow)

Thank you Dan!
