### ISSUE TITLE
Shortcut key for deleting tags

### ISSUE THREAD

**Issue by remzr7** [Automattic/simplenote-macos#101]
There should be shortcut keys for deleting tags. Having to delete tags by right clicking is pretty annoying

**Comment by drw158** [comment]
You can just click on the tag and hit the delete key.

**Comment by jleandroperez** [comment]
Closing this one since Tags really need to be selected / highlighted first, and doing so with the GUI is the easiest way.

Plus, as @drw158 mentioned, the **delete** key will remove the tag, once selected.

Thanks for your interest in Simplenote @remzr7!
