### ISSUE TITLE
Improved MD view/edit

### ISSUE THREAD

**Issue by memoriafuturi** [Automattic/simplenote-macos#1018]
Would really love if the MD was "improved". Personally, my favourite is something like Typora where you can edit and view the MD at the same time and it kind of hides the formatting codes unless you're on the item - particularly nice for URL links. Would also be nice if can use external CSS for this - letting community to develop their own, like for Standard Notes and Typora, might be an "easy" way to do this.

**Comment by jleandroperez** [comment]
Adding a +1 vote in our internal system for the Live Markdown Edition feature (and another +1 for the customizable CSS Markdown).

Thank you for reaching out!
