### ISSUE TITLE
Simplenote v2.15 doesn't open

### ISSUE THREAD

**Issue by chrisjf** [Automattic/simplenote-macos#1029]
Please, be as descriptive as possible.  Issues lacking detail, or for any other reason than to report a bug, may be closed without action.

### Expected
The app should open.

### Observed
The app starts (because I see that the menu bar changes to "Simplenote"), but the main window doesn't open. 

### Reproduced
> 1. Double click on the icon to open the app. 

#### Screenshots

<img width="1792" alt="Screen Shot 2021-09-06 at 19 05 57" src="https://user-images.githubusercontent.com/105042/132264863-a3e87db5-ff1b-4efc-8289-3da8cff5a20c.png">
^ The above screenshot is what it looks like when the Simplenote app is opened. 

***

<img width="563" alt="Screen Shot 2021-09-06 at 19 06 12" src="https://user-images.githubusercontent.com/105042/132264867-24c29191-69fc-4dc4-b1d7-aea7bb62a75e.png">
^ I am able to click on the Simplenote menu > "About Simplenote" to get this window to appear.

***

<img width="1792" alt="Screen Shot 2021-09-06 at 19 06 31" src="https://user-images.githubusercontent.com/105042/132264870-db9c418a-0aca-4681-a4a0-a5315b9c86e0.png">
^ When I click on the Note menu > New the above blank window appears.

***

I previously had Simplenote installed on my system from the App Store. I deleted the app and tried reinstalling from the App Store. This didn't fix the issue. (I even tried again (deleting and reinstalling) using the app "App Cleaner" to no avail.)

Make|Model|macOS Version|App Version
-|-|-|-
Apple|MacBook Pro 16-inch 2019|macOS v11.5.2|v2.15

**Comment by charliescheer** [comment]
Hi there @chrisjf !!  Thanks for reporting this issue.  I have looked into it and it seems to be an issue with the light/dark themes on Simplenote.  I am going to continue looking into what is goin on here and get a fix out as soon as possible.  In the meantime if you set Simplenote to dark mode it will open.  Once you open Simplenote if you go to View -> Theme -> Dark then quit the app and restart it, the notes will open.  check out this video to see those steps.
https://d.pr/i/hEOhrI

**Comment by chrisjf** [comment]
Hi @charliescheer. Thanks for your hard work, the quick reply, and the dark mode workaround! Looking forward to light mode again in the next version 😇

**Comment by charliescheer** [comment]
This is fixed in #1031 I am going to close this issue. There should be a hot fix out soon

@chrisjf keep an eye out for version 2.15.1 in the app store.  Once that is out, update and you should be able to go back to light mode

**Comment by chrisjf** [comment]
THANK YOU @charliescheer @mokagio 👏 🙌 (Yes, I was creeping in your branches last night and saw you folks were working on a fix. 😉) Great job team Simplenote! Have a wonderful week!

**Comment by charliescheer** [comment]
Hey @chrisjf Just letting you know there is a new version of SNMac in the app store now, 2.15.1, if you update to that you will be able to switch back to light mode.  Thanks again for this report!
