### ISSUE TITLE
Sign Up: No errors given when passwords mismatch

### ISSUE THREAD

**Issue by hoverduck** [Automattic/simplenote-macos#104]
I attempted to create a new account, and accidentally typed one of the passwords incorrectly, but had no idea what was wrong.  Clicking the Sign Up button doesn't do anything.

![simplenote-nux](https://cloud.githubusercontent.com/assets/7233112/21615945/9db5e6b8-d1ad-11e6-9fdd-f3f58075e819.gif)

By contrast, putting in an invalid e-mail address or a too-short password does provide an error:
![screen shot 2017-01-03 at 12 11 34 pm](https://cloud.githubusercontent.com/assets/7233112/21615993/d9895ab2-d1ad-11e6-9cd2-5e4fb03f4a10.png)

**Comment by arunsathiya** [comment]
Noting that this is still an issue. Tested on Simplenote for Mac (Simplenote 1.3.8)

![screen recording 2018-10-15 at 15 11 57 2018-10-15 15_13_50](https://user-images.githubusercontent.com/18581859/46943319-03f2a580-d08d-11e8-818d-b35fd32ea24e.gif)

## What is expected

A notice that passwords don't match is shown, like in the case of Simplenote Electron (screenshot below from Simplenote Electron 1.1.7)

<img width="1136" alt="screenshot 2018-10-15 at 15 16 18" src="https://user-images.githubusercontent.com/18581859/46943514-6ea3e100-d08d-11e8-9322-0849f4532971.png">

**Comment by rachelmcr** [comment]
I ran into the same issue today while testing version 1.7.0 beta. If the `Confirm Password` field is empty or doesn't match the `Password` field, there are no password-related errors (even if the passwords are too short).

**Comment by jleandroperez** [comment]
Closed via #550. Shipping in Simplenote 1.10.

Thanks everyone!!
