### ISSUE TITLE
Unable to expand menu on Trash from sidebar for Empty option (v1.1.8)

### ISSUE THREAD

**Issue by hoverduck** [Automattic/simplenote-macos#105]
See here a comparison between v1.1.8 (left) and v1.1.7 (right).  The newer version doesn't expand the Empty Trash menu, but still shows the carat dropdown indicator.
![simplenote-trash](https://cloud.githubusercontent.com/assets/7233112/21616371/356e4260-d1af-11e6-8b7d-36f7f65d1b5c.gif)

**Comment by lancewillett** [comment]
Confirmed this same issue today, version 1.1.8 (1180).

**Comment by designsimply** [comment]
Tested and confirmed. Found that the same problem happens for any tag menu. ([16s](https://cloudup.com/cGwpsQglO2F))
