### ISSUE TITLE
Provide DMG package

### ISSUE THREAD

**Issue by ansidev** [Automattic/simplenote-macos#1061]
### What
Provide DMG package

### Why
Due to my company policy, I cannot download the software from Apple AppStore, it requires login with Apple ID.

**Comment by charliescheer** [comment]
Thanks for the suggestion!  At this time we only distribute the native Mac app in the Mac App Store, but we do have an electron version of Simplenote that you can download instead.  You can find that [here](https://github.com/Automattic/simplenote-electron/releases/download/v2.21.0/Simplenote-macOS-2.21.0.dmg)
