### ISSUE TITLE
Collapsable Menu Panel

### ISSUE THREAD

**Issue by nfortenberry** [Automattic/simplenote-macos#1078]
It'd be great if the left side menu panel was easily collapsable.  Currently it takes up a decent bit of the screen and seeing the full text is not always needed.  This is currently possible by dragging the panel to be smaller, however, it does not look good and is not easy to expand/collapse:
![image](https://user-images.githubusercontent.com/1483072/211879505-5f352162-44d6-426f-aa45-e29e3e681c5f.png)

### What
An easy way to expand and collapse the side panel.  The collapsed version would show only the icons where the expanded version would show the full icon/text/note count.

### Why
The current menu does not provide much value when it is alway expanded. Users can easily recognize the icon and collapse the menu to save screen space.

### How
There could be an icon (such as a "<<" or ">>") at the bottom of the side panel to expand/collapse the panel. The collapsed view would look similar to the screenshot above, however, cleaner and more usable.

**Comment by charliescheer** [comment]
Thank you for this suggestion.  Looking at the images that you shared, that doesn't look like Simplenote Mac to me.  These icons are un familiar and seem to imply some features that Simplenote doesn't currently support (like folders)  In Simplenote Mac you can hide the side bar by going to View > Focus Mode, which hides all panels.

I am gonna close this issue, but please feel free to open again with more information.
