### ISSUE TITLE
Pop-out note into separate window

### ISSUE THREAD

**Issue by nfortenberry** [Automattic/simplenote-macos#1079]
It'd be great if a user could pop out a note into a separate window which would be separate from the main SimpleNote view.

### What
A user could double click a note and it would pop out into a new window that is only the text editor.

### Why
This would allow users to edit multiple notes at once, as well as easily hide sensitive information (such as the side panel) when presenting notes via screenshare.

### How
A user could double click a note in order to have it open in a new window.

**Comment by mokagio** [comment]
See also https://github.com/Automattic/simplenote-macos/issues/1076

**Comment by charliescheer** [comment]
Closing this issue as a duplicate of #1076
