### ISSUE TITLE
Change minimum window width

### ISSUE THREAD

**Issue by Brin-o** [Automattic/simplenote-macos#1083]
### What
I would like the minimum window width to be changed to a smaller amount to allow for easier vertical window tiling. 

### Why
Look at the screenshot attached. Trying to tile the apps into a 3/4 and 1/4 grid is currently impossible because simple notes does not want to take up as little as 1/4 of the width. I dont really see a reason why this is not possible when the sidebar is collapsed.

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/49071768/215993284-7e74bd5e-c318-4aa7-bad0-f9520e6a69b2.png">

**Comment by charliescheer** [comment]
updated to a new minimum in #1086  closing
