### ISSUE TITLE
[Bug] Fine-grained font size adjustment broken

### ISSUE THREAD

**Issue by tedmiston** [Automattic/simplenote-macos#1095]
Originally reported [here](https://twitter.com/kicksopenminds/status/1668278925410041859).

### Expected

***(Required)*** Font size adjustment (`View > Font Size > Smaller` / `View > Font Size > Bigger`) work for fine-grained adjustment like they always have.

### Observed

***(Required)*** Instead these menu font size adjustments have lost their ability to be fine-grained, and now they only make very coarse-grained adjustments mirroring the coarse "Text Size" setting in Preferences.

Unfortunately on my system, this means that Text Size 1/5 is illegibily small and Text Size 2/5 is HUGE.

For years, I have used Text Size 2/5 and then decreased the font size by 1–2 steps via the menu item.  This is a more fine-grained control for font size than the one offered in Preferences for "Text Size".

### Reproduced

***(Required)***

> 1. Set "Text Size" in Preferences to 2/5.
> 2. Click `View > Font Size > Smaller` in 2.18.
> 3. Observe that it behaves differently (more aggresively) than previous versions of the app.

***(Optional)*** If applicable, add screenshots, animations, or videos to help illustrate your problem.

***(Optional)*** If you reproduced the bug on a specific system, please replace SYSTEM_MAKE, SYSTEM_MODEL, MACOS_VERSION, and APP_VERSION below with the details for that system.  If you reproduced the bug on multiple systems, please add a row for each system.

Make|Model|macOS Version|App Version
-|-|-|-
SYSTEM_MAKE|SYSTEM_MODEL|MACOS_VERSION|APP_VERSION

**Comment by tedmiston** [comment]
^ As I reported in https://github.com/Automattic/simplenote-macos/issues/1089#issuecomment-1587583984, it is not possible for outside contributors to change tags.

**Comment by tedmiston** [comment]
Hello - This bug from almost a month ago is still appearing in the production app on the Mac App Store.  Is it possible to get a response and/or update?  

Tagging @mokagio because it looks like you're the only one active on this in recent commit history.

**Comment by jleandroperez** [comment]
Hello there @tedmiston,

I'm afraid this is part of a feature implemented two years ago, and it's by design. https://github.com/Automattic/simplenote-macos/pull/1045

That being said, I'll pass along your feedback to the team.

Thank you for reaching out!

**Comment by tedmiston** [comment]
@jleandroperez Breaking the font sizing was by design... and done 2 years ago?  That does not make sense...

Your own team on Twitter already acknowledged that it was a bug...

The update was only just recently released in the MAS very recently.  Are you saying the MAS version of the app lags by 2 years?!

Font sizing in the new app looks like looking through a magnifying glass.  It is completely unusable.

It's hard to how imagine how any QA would pass this change unless they only tested on one very high screen resolution.

**Comment by tedmiston** [comment]
Why do you close the issue as "completed" when the bug is clearly outstanding?

**Comment by jleandroperez** [comment]
Hey there @tedmiston, apologies it took me a while to get back to you.

As of around two years ago, font size step was updated so that it would jump by 5pt increments / decrements, and it would range from 10pt thru 30pt. Theory is that you were using a font size that is no longer within those parameters, but you only noticed when you changed the font size parameter.

I've touched base with our design team, and we'll be lowering the font size granularity in the next Simplenote macOS release (2.19), so that you can restore your preferred settings. 

For the record, this has been already adressed via #1101.

Thank you for reaching out!
