### ISSUE TITLE
When you first select an empty tag field, auto-suggest a few recently used tags

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#11]
<a href="https://github.com/mikejohnstn"><img src="https://avatars.githubusercontent.com/u/515035?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mikejohnstn](https://github.com/mikejohnstn)**
_Monday Jul 29, 2013 at 23:02 GMT_

---

**Comment by jleandroperez** [comment]
Closing this one as wontfix since it basically implies building the entire Tags Editor from scratch (and we haven't received any requests, in the past few years!).
