### ISSUE TITLE
Homebrew installs only Intel version

### ISSUE THREAD

**Issue by DaveEveritt** [Automattic/simplenote-macos#1138]
`brew install --cask simplenote` installs v2.21.0 but the Intel version.

So on opening OS X asks to install Rosetta (which I don’t want) to open… Visual Studio Code (Silicon VSCode already installed with Homebrew and working fine), so I’m guessing this alert is related to Electron.

I don’t want to run Rosetta. Is it possible to get the ARM/Silicon version of SimpleNote through a HomeBrew Cask install?

### Expected
expected homebrew to install ARM or universal version

### Observed
Homebrew installs Intel version

### Reproduced
run `brew install --cask simplenote`

### System
M2 MacMini running Ventura 13.6.5.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by jleandroperez** [comment]
Hey there @DaveEveritt !!

I'm afraid `brew install` will get you the [Simplenote Electron binary](https://github.com/Automattic/simplenote-electron).
Simplenote Mac (Native) is around version 2.19, with native Apple Silicon support.

Our official distribution channel is the Mac AppStore, please use that one!

Thank you for reaching out!

**Comment by DaveEveritt** [comment]
I see, that's exactly what I did yesterday and it obviously works fine. But what's the rationale behind offering only the Electron version via Homebrew?

**Comment by jleandroperez** [comment]
Since the standard way to install Mac Apps (at least with GUI, not CLI!) is the MAS, the binary available via brew is mostly meant for Linux users, mostly!.

That being said, I'll pass along the feedback to the team. Thank you for reaching out!

**Comment by DaveEveritt** [comment]
Understood, although many developers use the Mac's *nix facilities the same way as Linux users do, and Homebrew is the Mac package manager of choice that keeps installs manageable, like aptitude is for Linux. Thanks for passing it on :-)

**Comment by gingerpaledale** [comment]
@jleandroperez hi. Thanks for your comment:
> Since the standard way to install Mac Apps (at least with GUI, not CLI!) is the MAS, the binary available via brew is mostly meant for Linux users, mostly!.
> That being said, I'll pass along the feedback to the team. Thank you for reaching out!

I'm also curious to know if there is a political/deliberate stand regarding _not_ supporting MacOS client installation via Homebrew. Do you maybe have any comments on that or can you refer me to someone among the maintainers who knows better?

The follow-up question then would be: would it be possible and appreciated if an external contributor (e. g. like myself) implements a cask (Homebrew script) for installing the production MacOS client? In other words, does Automattic make signed MacOS binaries (`.dmg` or `.pkg`) available for download via a public URL?

Tnx in advance.
