### ISSUE TITLE
Provide current synced status per note

### ISSUE THREAD

**Issue by geekpete** [Automattic/simplenote-macos#114]
I saw some behaviour where I added a note in the mac client and it didn't appear to be synced for some time when checking with the web client.
Also saw that some notes updated in the web client were still showing old versions in the mac client.
There's no visibility for the user of the note sync status in the mac client.
As a user I have no visibility of this, I have to manually go to the web client to see if my mac client additions/changes have been "saved" or not. And I need to wait an indefinite amount of time before my notes and changes become fully synced with no UI feedback.

Perhaps some indicator for last sync status would be good to show the user.
For new notes, if not yet synced then last synced would be "never"
Though there is a "modified" detail in the top right ellipsis, it gives no information about if these changes have synced successfully or not.  

Also maybe a way to indicate the difference between an old unchanged note (eg very old last synced timestamp but that's ok cos it hasn't been updated since then) vs a newly updated note that has sync pending.

So perhaps two indicators for the following info per note:
sync status: syncing/synced/sync pending  
and
last synced: some date/time in the past or never

So you would then see if a note has been created/updated locally but not yet synced.

**Comment by bummytime** [comment]
For context, Electron has the overall sync status:

<img width="232" alt="Screen Shot 2019-05-15 at 2 29 48 PM" src="https://user-images.githubusercontent.com/154014/57803411-f7672600-771d-11e9-9d4e-e489a4398605.png">
<img width="296" alt="Screen Shot 2019-05-15 at 2 29 55 PM" src="https://user-images.githubusercontent.com/154014/57803412-f7ffbc80-771d-11e9-9e15-88762e01932b.png">

**Comment by jleandroperez** [comment]
I've added +1 vote for granular Sync Status in our internal feature-request tracker.

Thanks for reaching out!
