### ISSUE TITLE
Feature Request: Add extended markdown

### ISSUE THREAD

**Issue by jrodan** [Automattic/simplenote-macos#117]
Hi together, 

I would like to see two more features for simplenote: 

- inline editing (there a editors who support also markdown)
- extended markdown like checkboxes
-- https://github.com/blog/1825-task-lists-in-all-markdown-documents

Thanks and regards

**Comment by QQQNo** [comment]
Footnotes would be fantastic, as well. They're working wonderfully in the iOS version!

**Comment by remzr7** [comment]
This would be awesome! @jleandroperez  any updates?

**Comment by roundhill** [comment]
Rolling this one into #73
