### ISSUE TITLE
Data Loss

### ISSUE THREAD

**Issue by iSumitG** [Automattic/simplenote-macos#118]
I had data loss. I suspect some sync issue between my two laptops and I lost a lot of text. Thankfully I realized that something is missing and restored the note from history. Below are the simplified details of the events. CAPITAL letters denotes the content of the note. * denotes an event. 
Please let me know if this is unclear. As you can see, there was data loss. 

\*6pm, laptop1 (personal) and laptop2 (office): both laptops are in sync at 6pm\*
ABCD

\*turns off laptop2\*

\*12pm, next day\*

\*1am on laptop1:\* 
ABCD
EFGH

\*turns off laptop1\*

\*9am, laptop2:\*
ABCD
EF

\*thinking why the text I wrote last night not appearing completely here, but didn't pay much attention\*

\*10am, laptop2: added some text\*
GHIJ
ABCD
EF

\*6pm, turns off laptop2\*

\*8pm\*
\*turns on laptop1\*
\*waiting for the note to sync on laptop1..but it remains what it was at 1am last night\*
\*turns on laptop2\*
\*waiting for the note to sync on both laptops..nothing happens\*

\*8:15pm, laptop1:  added just the dot in the end to see if it syncs\*
ABCD
EFGH.

\*it syncs immediately and thus deleting the data I entered at 10am on laptop2\*
\*8:15pm, laptop2:\*
ABCD
EFGH.

\*data that I entered on laptop2 at 10am is gone\*
\*restores it back from history on laptop2 to 10am\*

\*8:20pm, laptop2:\*
GHIJ
ABCD
EF

\*as soon as it is restored on laptop2, the laptop1 updates\*

\*08:20pm, laptop1:\*
GHIJ
ABCD
EF

**Comment by bummytime** [comment]
Not able to repro at this time. Closing.
