### ISSUE TITLE
Parameterize all colors, fonts, and sizes in a plist

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#12]
<a href="https://github.com/mikejohnstn"><img src="https://avatars.githubusercontent.com/u/515035?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mikejohnstn](https://github.com/mikejohnstn)**
_Saturday Aug 10, 2013 at 21:18 GMT_

---

Probably via DB5 or something like it (OSX support added in this pull request: https://github.com/quartermaster/DB5/pull/6)

**Comment by bummytime** [comment]
Closing for now.
