### ISSUE TITLE
View untagged notes

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/simplenote-macos#120]
In the web app it's possible to view all untagged notes by searching for tag:untagged. It would be good to have this in other apps also.

**Comment by rwaynick** [comment]
+1 for this feature. Another related idea might be to have a default 'untagged' tag appear in the sidebar in addition to being able to search for it.

**Comment by bummytime** [comment]
On Android, this exists:

<img width="260" alt="Napkin 142 05-23-19, 2 17 43 PM" src="https://user-images.githubusercontent.com/154014/58280134-949d0c80-7d65-11e9-9773-53d41f6ab57a.png">

**Comment by 0n0n0m0uz** [comment]
> In the web app it's possible to view all untagged notes by searching for tag:untagged. It would be good to have this in other apps also.

I can't even view untagged notes on the web version either.  At one point I swear I could.

**Comment by dctr** [comment]
`tag:untagged` neither works in web nor macOS for me.

By now, this is the only feature that keeps me from fully migrating to Simplenote. I have heaps of notes and if I quickly add one on the go I don't want to need to add a tag. Yet if I don't the note gets lost easily. Would it be hard to add this feature on macOS?

**Comment by sarahfg** [comment]
Requested in #2606107-zen

**Comment by lancewillett** [comment]
Would love to see untagged notes in the macOS app. I was using the web view as a fallback, but that seems removed now, too. Is that true?

My workflow relies on finding any untagged notes in a weekly sweep, to catch loose ends.

**Comment by jleandroperez** [comment]
@lancewillett the `Untagged Notes` filter is coming to the (native) macOS app in the next release (along with a huge redesign). Ref. #458

As per the web update, not sure about that one! cc'ing @belcherj since he'll know better.

Thank you for reaching out, hope you're doing ggggreat!!!

**Comment by lancewillett** [comment]
Thank you, @jleandroperez ❤️ 

I love Simplenote (and the team).
