### ISSUE TITLE
Welcome to simplenote mac replace all notes

### ISSUE THREAD

**Issue by TheMartes** [Automattic/simplenote-macos#122]
Hello, today i installed simplenote into my mac, and when i sing in to my account message "Welcome to simplenote Mac!" replace all my notes, and i cant figure how to fix it for 2 hours. Any help? 
![image](https://cloud.githubusercontent.com/assets/16374732/25291901/38df4a28-26d4-11e7-87b5-e8c8c405547a.png)

**Comment by roundhill** [comment]
Our support team can help you out! Please submit a request here: https://simplenote.com/contact-us
