### ISSUE TITLE
[ASK] Can markdown preview on width larger?

### ISSUE THREAD

**Issue by taimaiduc** [Automattic/simplenote-macos#128]
Can Markdown preview with the width larger?

I have a big screen in mode preview markdown blank space too much but the content too small to view

![2017_06_29_16_29_40_](https://user-images.githubusercontent.com/10907980/27681203-9abc4256-5ce8-11e7-9fed-7049b24d8f20.png)

**Comment by jleandroperez** [comment]
Closing this one, since the macOS Binary doesn't have Markdown preview. 

@taimaiduc if possible, please, reopen in the [Electron Repository](https://github.com/Automattic/simplenote-electron),
thank you!!
