### ISSUE TITLE
Undo works, until a bullet, then undo becomes wonky

### ISSUE THREAD

**Issue by tscizzle** [Automattic/simplenote-macos#129]
I can type, and undo those keys just fine.

But when I hyphen bullets things like 
"
\- blah blah
\- another blah blah
"

suddenly undo and redo behave very strangely. It is hard to describe the new wonky behavior, because it seems so random. Like, deleting a bullet and clicking undo will make is reappear, but then  doing redo won't do anything, or typing and then doing undo won't do anything. Stuff like that.

**Comment by Krinkle** [comment]
I am experiencing the same issue. The Undo/Redo functionality does not work correct when inside a bullet list.

Whether adding text in an existing item, or adding a new bullet, undo tends to mangle the entire document making changes in unexpected places of the text.

Version 1.3.6 (latest) on macOS 10.13.

**Comment by mgalbritton** [comment]
Another report here in #1415065-zen. I was able to recreate this.

Steps to recreate:

1) add text to a note

2) add a bulleted list using `-`

3) add some more text

4) Go to undo and undo a few times. 

5) You will see that it undos parts of the note until it gets to the bulleted list where it then undoes all of it.

I was able to restore the note using the history option.

**Comment by esm2000** [comment]
This is still an issue today...

**Comment by jleandroperez** [comment]
Closing in favor of #467, since we're adding lots of (tech level) details, and an attack plan.
Will be fixed in the next release, working on this one right right now. 

Thanks everyone for helping us improve Simplenote!!
