### ISSUE TITLE
Add a global keyboard shortcut to activate the app

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#13]
<a href="https://github.com/mikejohnstn"><img src="https://avatars.githubusercontent.com/u/515035?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mikejohnstn](https://github.com/mikejohnstn)**
_Wednesday Aug 21, 2013 at 18:01 GMT_

---

**Comment by jleandroperez** [comment]
Closing this one as won't fix. The app is accessible thru macOS's Dock, and visible via CMD + Tab.

Please feel free to reopen if needed!
