### ISSUE TITLE
Duplicate tags appear on sidebar

### ISSUE THREAD

**Issue by ghost** [Automattic/simplenote-macos#130]
When I open a note (with a pre-exisiting tag) and SIMPLY CLICK in the tag area (on the right side of the existing tag):

![tag area](https://user-images.githubusercontent.com/1519780/29122781-06833706-7d46-11e7-9929-a24503af34d8.png)

...it will create a duplicate tag of the pre-existing tag in the sidebar:

![sidebar](https://user-images.githubusercontent.com/1519780/29122810-209a44e0-7d46-11e7-87d4-2135bd382ed7.png)

Simplenote Mac Version 1.1.8 (1182)
macOS Sierra 10.12.6

**Comment by rachelsquirrel** [comment]
Related issue: https://github.com/Automattic/simplenote-macos/issues/70

**Comment by bummytime** [comment]
Closing in favor of #70
