### ISSUE TITLE
Quick shortcut to switch between preview and edit mode

### ISSUE THREAD

**Issue by pablosproject** [Automattic/simplenote-macos#131]
I would like to add a shortcut like cmd+shift+P to switch between edit and preview mode. 

Will dig into the code and try to implement myself before submit.

**Comment by dmsnell** [comment]
Hi @pablosproject! Thanks for the interest in digging into the code. We'll be happy to review and help where possible. This is a great idea too - something we're currently implementing in the Electron-based app as well at automattic/simplenote-electron#603

**Comment by Robertght** [comment]
As I was testing this one: https://github.com/Automattic/simplenote-electron/issues/1553 I noticed this is still a FR. +1

**Comment by jleandroperez** [comment]
Closing as done via #888: `Cmd + Shift + P` Toggles markdown preview
