### ISSUE TITLE
Add ability to use the right arrow to move from list view to editor view

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#14]
<a href="https://github.com/mikejohnstn"><img src="https://avatars.githubusercontent.com/u/515035?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mikejohnstn](https://github.com/mikejohnstn)**
_Friday Aug 23, 2013 at 00:47 GMT_

---

**Comment by jleandroperez** [comment]
Closing as done via #888.

Thank you!!
