### ISSUE TITLE
Simplenote freezes upon system wake from sleep

### ISSUE THREAD

**Issue by kriskorn** [Automattic/simplenote-macos#148]
User reported that once they wake their system from sleep, Simplenote freezes. 

- Process is identified as "Not Responding" and taxes CPU at 70%-99% until process is killed. 
- Killing process and restarting app returns app to normal behavior. 
- Happens predictably every time Mac is woken from sleep the last ~7 days.

**System:**

Mac OS v10.13.2 
Simplenote v1.1.8, 1182 
MacBook Pro (Late 2013)

#835782-zen

**Comment by bummytime** [comment]
**Update 5/14/2019 →** Tested in Simplenote 1.4.2 on macOS 10.14.4 (Mojave) andwas not able to repro. Closing for now.
