### ISSUE TITLE
Support very basic bullet lists

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#15]
<a href="https://github.com/mikejohnstn"><img src="https://avatars.githubusercontent.com/u/515035?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mikejohnstn](https://github.com/mikejohnstn)**
_Friday Aug 23, 2013 at 22:26 GMT_

---

When you hit enter within a dash/bullet list, automatically add another dash/bullet.

**Comment by bummytime** [comment]
Already implemented. Closing.
