### ISSUE TITLE
Clicking outside history slider should restore latest note content

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#151]
If you scroll back in the revision history and then click out of the revision dialog box, the note stays on that selected revision:

![simplenoterevisions](https://user-images.githubusercontent.com/789137/33842885-afe9850a-de50-11e7-8560-f8f0d8d991fd.gif)

**Comment by jleandroperez** [comment]
Closing as cannot repro anymore.
Tested on Simplenote 1.12. 

Thank you Dan!!
