### ISSUE TITLE
Incorrect pinned note syncing behavior

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#152]
While testing note pinning and sync, I noticed some inconsistency with updates to the list ordering:

- When I pin/unpin a note in the app, it immediately moves to the expected place in the list of notes (at the top when pinned, under other pinned notes when unpinned).
- If  I pin/unpin a note from another device, the pinned status is synced immediately but the list of notes isn’t immediately reordered (so the newly pinned note still shows up among unpinned notes instead of at the top of the list).
- If I edit the content of a post, the note isn’t immediately moved to the top of the list. (This is an issue both when I’m only working on a single device and when I’m working on multiple devices — with multiple devices, the note content syncs immediately but the list isn’t reordered.)

**Comment by jleandroperez** [comment]
Closing this one since it's no longer relevant. 
We've rebuilt the Notes List around NSFetchedResultsController (Ref. #626), and all the things update in realtime now.

To be released in Simplenote macOS 2.6.

Thank you Dan!!
