### ISSUE TITLE
CPU spikes during scrolling with lots of notes

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#16]
<a href="https://github.com/mikejohnstn"><img src="https://avatars.githubusercontent.com/u/515035?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mikejohnstn](https://github.com/mikejohnstn)**
_Sunday Aug 25, 2013 at 19:03 GMT_

---

**Comment by bummytime** [comment]
**Update 5/14/2019 →** Tested in Simplenote 1.4.2 on macOS 10.14.4 (Mojave) and this issue no longer occurs.
