### ISSUE TITLE
Provide "Export As..." option in the Note menu

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/simplenote-macos#161]
As a Simplenote user, I only like to keep my "active" notes in the app. I consider notes related to on-hold or completed projects to be "archived", and prefer to keep them out of my line of sight.

It would be helpful to have a "Export As..." (or "Save As...") option in the Note menu so I could easily archive notes into Dropbox:

![image](https://user-images.githubusercontent.com/36432/34124147-bebbe726-e3e6-11e7-97b9-a835e10fb3b1.png)

Here's the equivalent in the Preview app:

![image](https://user-images.githubusercontent.com/36432/34124206-eaf763c4-e3e6-11e7-9289-11002088db1d.png)

**Comment by danielbachhuber** [comment]
I'd be open to trying my hand at submitting a pull request (and giving feedback on the contribution process) if this was deemed a reasonable enhancement.

**Comment by roundhill** [comment]
Hi @danielbachhuber! Hmm it's too bad that the Dropbox app doesn't support accepting text shares. Seems reasonable to me. You'll probably have to create the file and insert the text.

**Comment by crankygeologist** [comment]
@roundhill Would it be possible to implement the "Export notes" functionality in the Mac app, like the Linux and Windows versions? As a Mac user, I know I can do this from the website, but I often get "Server is busy" errors when clicking on the link to download the Zip file.

**Comment by bummytime** [comment]
Closing in favor of #294
