### ISSUE TITLE
Sidebar: the closed state isn't persisted across relaunches

### ISSUE THREAD

**Issue by folletto** [Automattic/simplenote-macos#164]
If the sidebar is toggled closed, it's not kept closed when the app re-opens.

### Steps to reproduce

1. Open Simplenote
2. Toggle the sidebar closed (i.e. the app has only the list and the content columns, no tags)
3. Close Simplenote
4. Re-open Simplenote
5. The sidebar will be open again

**Comment by roundhill** [comment]
Thanks @folletto! This is actually a dupe of #163. Hoping to get that fixed soon.

**Comment by folletto** [comment]
I searched for "sidebar" and I couldn't find it... and it was the one right at the top instead. :P 

Thanks!
