### ISSUE TITLE
Long tags in sidebar truncated + no condensed view

### ISSUE THREAD

**Issue by hisyam** [Automattic/simplenote-macos#166]
I updated to Simplenote v1.2 (1200) and noticed that the sidebar:
- can't be resized so all the long tags get truncated
- has more whitespace so if you have lots of tags you have to scroll down in the sidebar to see the tag that you want

![simplenote sidebar problem](https://user-images.githubusercontent.com/31984069/34640076-edac6642-f326-11e7-906f-5e2793edee8c.png)

Can you please add:
- resizable sidebar
- bring back the condensed view of the sidebar as an option

**Comment by Robertght** [comment]
Another request in #1066993-zen

**Comment by pranali333** [comment]
Another request on "Long tags are getting truncated in the sidebar."

https://woothemes.zendesk.com/agent/tickets/1980185

Thanks

**Comment by jleandroperez** [comment]
Closing this one via #532. Simplenote 1.11, (shipping soon!) supports sidebar resizing.

Apologies it took us a while to get this patched up, and thanks everyone for reaching out!!
