### ISSUE TITLE
Support RTL text

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#17]
<a href="https://github.com/mikejohnstn"><img src="https://avatars.githubusercontent.com/u/515035?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mikejohnstn](https://github.com/mikejohnstn)**
_Wednesday Aug 28, 2013 at 20:09 GMT_

**Comment by iamgabrielma** [comment]
From an user (3018809-t):

> could you consider making the Mac desktop version arabic friendly, so that we can write from right to left if we are writing in this script? This works on the android version of the app for example.

**Comment by cecilerainon** [comment]
Hello! I have received a report from someone in Israel who mentioned that since the last update, RTL isn't supported anymore: https://woothemes.zendesk.com/agent/tickets/995563

This issue is still opened so I'm a little confused whether or not RTL was ever supported or not.

**Comment by msilbers** [comment]
We have had another request for this in #1417969-zen, although it's likely the same user as above

**Comment by bummytime** [comment]
Ref: #198

**Comment by bummytime** [comment]
Closing in favor of #198
