### ISSUE TITLE
Spell check doesn't find MISPELLD UPPERKASE WERDS  

### ISSUE THREAD

**Issue by crankygeologist** [Automattic/simplenote-macos#172]
See title. This might be a macOS bug. Same issue in TextEdit. ;-)

Simplenote for Mac
Version 1.2 (1200)

**Comment by roundhill** [comment]
I confirmed that Mail.app has the same behavior, so don't think we can do anything about this for now.

**Comment by Gatada** [comment]
Classic "not a bug, but feature" kinda thing: uppercase words are often acronyms that often or always fails spell checks. About year ago Windows 10 apparently also stopped spell checking UPPERKASE WERDS.
