### ISSUE TITLE
Character count for Chinese/Japanese/Korean characters is incorrect

### ISSUE THREAD

**Issue by Piyopiyo-Kitsune** [Automattic/simplenote-macos#175]
Currently Simplenote does not count words correctly for Chinese, Japanese, and Korean when I tested on my Android mobile device and iPad.
Ideally, for these languages a character count would suffice as it's not commonplace to do word counts like we do in English.

Android(ver 1.5.7):
![screenshot_20180208-151216](https://user-images.githubusercontent.com/17694715/36003383-a8bccf7e-0ce2-11e8-9e0e-d71f95df8589.png)
It says 5 words, when there are actually 7 words. 

iPad(ver 4.4.5)
![image uploaded from ios](https://user-images.githubusercontent.com/17694715/36003642-c4f78f2a-0ce3-11e8-8caf-01b47a0ab581.png)
It says 15 words, when there are actually 7 words. 

Total characters(without spaces): 18

**Comment by jleandroperez** [comment]
Hello there @Piyopiyo-Kitsune!

In this repository we track macOS bugs. Mind filing an issue in [the Simplenote Android Repository](https://github.com/Automattic/simplenote-android) ?

Thanks!!

**Comment by Piyopiyo-Kitsune** [comment]
@jleandroperez Thanks for the correction!
Added the Android here https://github.com/Automattic/simplenote-android/issues/495
and iOS here: https://github.com/Automattic/simplenote-ios/issues/191

**Comment by jleandroperez** [comment]
Thank you!! much appreciated!
