### ISSUE TITLE
Add search term highlighting

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#18]
<a href="https://github.com/tomwitkin"><img src="https://avatars.githubusercontent.com/u/3904502?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [tomwitkin](https://github.com/tomwitkin)**
_Wednesday Aug 28, 2013 at 21:07 GMT_

---

For the note list, the following two files are useful:
- https://github.com/Simperium/simplenote-ios/blob/master/Simplenote/Classes/NSTextStorage%2BHighlight.m
- https://github.com/Simperium/simplenote-ios/blob/master/Simplenote/Classes/NSString%2BSearch.m

This could also be applied to the note editor. I think it's more difficult to bring over the blue highlighting that's there on iOS since that uses UIViews.

**Comment by suaracahaya** [comment]
Please implement highlighting search terms in Mac app too...

**Comment by rwaynick** [comment]
Another vote in 794816-zen

**Comment by spncrb** [comment]
Another request for this in 815690-zen

**Comment by katinthehatsite** [comment]
Another request in 1044645-zen. The user would like to add the highlighting of the search terms.

**Comment by Hywan** [comment]
Another request in #1053382-zen.

**Comment by Piyopiyo-Kitsune** [comment]
Requested again in #1071028-zen

**Comment by msilbers** [comment]
requested in #1540067-zen as we have this functionality in Android already

**Comment by pjeutr** [comment]
Coming from Notational Velocity, this is what I really need in my worklfow.

I see it fixed on linux / windows some time ago
https://github.com/Automattic/simplenote-electron/pull/424

Any plans for macOS?

**Comment by iamgabrielma** [comment]
1830712-zen

**Comment by edequalsawesome** [comment]
Requested in #1909776-zen

**Comment by bummytime** [comment]
## Searching in macOS:
![search_highlight](https://user-images.githubusercontent.com/154014/58289015-d4222380-7d7a-11e9-9424-a069a56d3ce0.gif)

## Searching in electron:
![search_highlight2](https://user-images.githubusercontent.com/154014/58289021-d6847d80-7d7a-11e9-9f2f-228865bfedc4.gif)

**Comment by rachelmcr** [comment]
We received another request for this kind of in-note searching and highlighting in 2282877-zen. This person uses both the iOS and Mac apps and expected search to work the same across platforms.

**Comment by thehenrybyrd** [comment]
Another request in #2285348-zen, from another person who uses iOS and Mac apps and expected a more consistent experience.

**Comment by JoffreyLGT** [comment]
Hi, I'm using SimpleNote on Electron, Android and Mac and this feature is really missing on Mac.
Is there any plan to bring it?

**Comment by mgalbritton** [comment]
Moved this to our internal feature tracking.
