### ISSUE TITLE
Feature request: WikiLinks

### ISSUE THREAD

**Issue by hypertexthero** [Automattic/simplenote-macos#185]
**The ability to link to an existing note or create a new note using text formatting** that supports both [wikilinks](https://www.mediawiki.org/wiki/Help:Links#Internal_links) and [CamelCaseToCreateANoteAndLinkToIt](https://simple.wikipedia.org/wiki/CamelCase#Wiki_link_markup) syntax would bring [Simplenote](https://simplenote.com/) closer to a representation of our interlinked creative thinking, connecting ideas on the fly.

Interlinked notes is the only feature I really miss in Simplenote. Thank you for considering this request!

**References:**
_[Pragmatic Thinking and Learning](http://wiki.c2.com/?PragmaticThinkingAndLearning)_  
_[TiddlyWiki](https://tiddlywiki.com/)_

**Comment by jleandroperez** [comment]
I've added +1 vote to "Internal Links Support", in our (internal) feature requests system.

Thank you for reaching out!!

**Comment by blakewatson** [comment]
+1000 for this feature
