### ISSUE TITLE
Add Menu Divider Between Empty Trash and Sign Out

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#186]
Some users are accidentally signing out when they intended to empty the trash. We should add a menu divider to help prevent this:

<img width="182" alt="screen shot 2018-02-26 at 9 08 58 am" src="https://user-images.githubusercontent.com/789137/36684401-0e5ce5b2-1ad5-11e8-9cab-6fa0093f5bc6.png">

**Comment by Gatada** [comment]
Hm, this was simple enough - so created a fix/ branch for it, but I'm unable to publish it?

**Comment by pachlava** [comment]
[testing] fix/feature verified on MBP 16" Intel | macOS 11.2 | Simplenote 2.8 (11218)
