### ISSUE TITLE
Suggestion: Pin lock/password protection for the app

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/simplenote-macos#187]
Simplenote Android app has a pin lock feature. A similar feature could be implemented on the Mac app for privacy/security reasons.

Checked if the Mac app has one, and turns out it does not.

**Comment by arunsathiya** [comment]
978177-zen

**Comment by johngodley** [comment]
#1021501-zen

**Comment by rantoncuadrado** [comment]
#1310482-zen

**Comment by iamgabrielma** [comment]
1847977-zen

**Comment by iamgabrielma** [comment]
1859999-zen

**Comment by manu-chroma** [comment]
Hi, I had the same feature request in mind. Can we have this feature request open for better visibility? I feel it'll have more chances of eventual implementation that way.

**Comment by codebykat** [comment]
Hi @manu-chroma, we use GitHub for tracking active work and bugs, not feature requests. We do take user feedback into account when planning future work (whether it comes in via GitHub, support tickets, Twitter, carrier pigeons, etc.) so it's not a waste to post here! But for the most part we don't leave the issues open unless they're on our immediate radar.

**Comment by manu-chroma** [comment]
makes sense, thanks for ack'ing :)
