### ISSUE TITLE
Add an option to make toolbar smaller

### ISSUE THREAD

**Issue by zenwalker** [Automattic/simplenote-macos#188]
That would be nice if we had an option to decrease toolbar height. The new toolbar which takes about 20% of the whole application space distracts and annoys me. I had thought I could get used to it but after a month I still can’t.

**Comment by bummytime** [comment]
Ref: #327

**Comment by jleandroperez** [comment]
Closing this one since we're shipping a redesigned toolbar in Mark 1.10.

Thanks everyone!
