### ISSUE TITLE
Double-clicking a tag pill to rename it creates a new tag

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#19]
<a href="https://github.com/mikejohnstn"><img src="https://avatars.githubusercontent.com/u/515035?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mikejohnstn](https://github.com/mikejohnstn)**
_Friday Aug 30, 2013 at 17:44 GMT_

---

Not 100% clear what should happen, but we've talked about this in the past. Renaming that tag outright is probably most expected.

**Comment by bummytime** [comment]
**Update 5/14/2019 →** Tested in Simplenote 1.4.2 on macOS 10.14.4 (Mojave) and this issue is still happening.

**Comment by jleandroperez** [comment]
Closed via #551
