### ISSUE TITLE
Support multiple accounts

### ISSUE THREAD

**Issue by andreyrd** [Automattic/simplenote-macos#192]
Similar to the feature request on the electron app https://github.com/Automattic/simplenote-electron/issues/310, it would be awesome to support switching between multiple accounts.

I use different accounts for my personal and work notes, and sometimes I want to switch between the two. I haven't dug into the source to see how difficult this would be to implement, but I'll try to when I find the time. And for what it's worth, I understand that this is probably low priority as it's not a normal use case.

**Comment by jleandroperez** [comment]
Moving this one to an internal system (where we can track the number of times something has been requested).

Closing for now. Thank you for the feature request!

**Comment by makulatura** [comment]
Hi!

I would like to support this request for a way how to separate multiple domains of information. I have two hobbies that don't overlap and I would love to be able to switch between two piles of notes.
