### ISSUE TITLE
Line spacing is too narrow

### ISSUE THREAD

**Issue by cnaa97** [Automattic/simplenote-macos#195]
Hi. I'm simple-note user. 

This is not a bug, It's enhancement issue.

when I text Korean, line-spacing(line-height) of editor is very narrow.

than It's hard to read text.

I think controlling line height function will be helpful for all users.

Thanks

**Comment by mjut** [comment]
I can confirm, line-spacing is too narrow in general. Not just Korean, it is the same with all other languages. It is not very pleasant to look at. Especially with longer texts....

Look at the examples here, Simplenote texts look like "normal" leading: 
https://en.wikipedia.org/wiki/Leading#Examples
It'd be much easier to read with at least 50% more leading. Actually, I would recommend 75%...

**Comment by cnaa97** [comment]
It's still looks narrow in 2019

![screen shot 2019-02-20 at 11 10 18 am](https://user-images.githubusercontent.com/7259107/53061152-3d866200-3500-11e9-8d59-8441d85de95b.png)

**Comment by cnaa97** [comment]
Here is alternative which is electron app.

https://github.com/Automattic/simplenote-electron/releases

**Comment by blakewatson** [comment]
Even for English text, the line spacing is uncomfortably narrow. Somewhere between 120% and 145% would be optimal. https://practicaltypography.com/line-spacing.html

**Comment by zero-hugo** [comment]
This is a question too for chinese . The line spacing and word spacing is too narrow. 
<img width="1083" alt="截屏2019-09-23下午12 25 53" src="https://user-images.githubusercontent.com/44722746/65846328-f1da4780-e36f-11e9-9cf2-037fb3636385.png">

**Comment by jleandroperez** [comment]
We're increasing line height via #556, shipping soon in Simplenote 1.11

Apologies it took us a while to address this, **thanks everyone** for reaching out!!
