### ISSUE TITLE
Zero margin on right side of Writing Area

### ISSUE THREAD

**Issue by Gatada** [Automattic/simplenote-macos#196]
A bug: Yesterday the app showed the writing area with zero margin on the right side.

Today, I'm unable to reproduce it.

**Comment by roundhill** [comment]
Do let us know if you are able to reproduce it!

**Comment by Gatada** [comment]
I did see it again. I think it might have to do with leaving full screen and adjusting window size. But I’ll keep an eye out for the exact steps.

**Comment by bummytime** [comment]
Closing for now.
