### ISSUE TITLE
Tag tokens in note editor don't wrap properly

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#2]
<a href="https://github.com/mikejohnstn"><img src="https://avatars.githubusercontent.com/u/515035?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mikejohnstn](https://github.com/mikejohnstn)**
_Wednesday Jun 05, 2013 at 18:54 GMT_

---

They wrap, but then overlap vertically with the row of tokens above them. See:
http://stackoverflow.com/questions/3735782/resizing-nstokenfield-after-populating-with-tokens
http://stackoverflow.com/questions/2333348/how-to-customize-nstokenfield-like-in-to-cc-fields-in-mac-mail

**Comment by bummytime** [comment]
Closing in favor of #57
