### ISSUE TITLE
Memory leak on connection failure

### ISSUE THREAD

**Issue by mattstevens** [Automattic/simplenote-macos#206]
Certain types of connection failures can result in a significant memory leak due to a retain cycle in the Simperium library. I encountered this through an unusual scenario, but it can result in Simplenote using over 1GB of private memory if I leave it running for a while.

The problem scenario is when the connection fails to be established due to an untrusted server certificate. A company I work for has a proxy deployed on their network that performs HTTPS intercept. Users are expected to trust the proxy's certificate on their devices and allow their secure traffic to be decrypted and monitored. I decline to do this on my personal machine, so when I VPN into this network Simplenote fails to connect due to the untrusted certificate. It then retries the connection every 2 seconds, leaking an SPRWebSocket instance each time, which in turn references all the memory associated with the underlying CFStreams.

I opened a PR with a fix in Simperium/simperium-ios#573, though I don't know if this is the right place.

**Comment by mattstevens** [comment]
It would also be nice if Simperium supported the system HTTP proxy settings for the websocket connection, that would allow me to bypass this problematic environment.

**Comment by bummytime** [comment]
Closing — https://github.com/Simperium/simperium-ios/pull/573 was merged.

**Comment by mattstevens** [comment]
The PR was merged in Simperium, but Simplenote has yet to update to a version of Simperium that includes the fix. It went into Simperium 0.8.21, Simplenote is on 0.8.19.

**Comment by bummytime** [comment]
Thank you for catching that @mattstevens! New issue to track the pod update is #328. 🙇
