### ISSUE TITLE
Highlighted text color change for better readability

### ISSUE THREAD

**Issue by Robertght** [Automattic/simplenote-macos#207]
Hey!

One of our awesome users, pointed out that the highlighted text while using the Dark theme on the Mac app is quite hard to read. I've given a shot myself at this and it appears to be so.
![simplenote 2018-04-27 10-08-05](https://user-images.githubusercontent.com/6737345/39349250-ea63d712-4a02-11e8-8bef-2f3a002871d0.png)

Can we consider a different color for the text to increase readability?

**Comment by pauljacobson** [comment]
I received another report of this issue in 1578132-zen where the user included this screenshot:

![1578132_simplenote_dark-mode_text-highlight](https://user-images.githubusercontent.com/2912202/48832473-e7c7df80-ed81-11e8-9fca-e3a99dcc3631.png)

The user is running macOS High Sierra (they're unable to upgrade to Mojave). Please look into this issue as soon as possible.

**Comment by w-** [comment]
Hi. This is still an issue. A fix would be great here. thanks

**Comment by bummytime** [comment]
As alluded to above, this is not an issue in Mojave:

<img width="827" alt="Screen Shot 2019-05-15 at 11 37 49 AM" src="https://user-images.githubusercontent.com/154014/57793031-f7f3c280-7705-11e9-9fab-d180c644dbab.png">

**Comment by jleandroperez** [comment]
Closing this one since it's no longer relevant. Cannot repro in macOS Mojave (and higher), and older macOS releases aren't officially supported anymore.

Thanks everyone!!
