### ISSUE TITLE
Animate showing/hiding the tag list

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#21]
<a href="https://github.com/mikejohnstn"><img src="https://avatars.githubusercontent.com/u/515035?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mikejohnstn](https://github.com/mikejohnstn)**
_Friday Sep 13, 2013 at 22:55 GMT_

---

**Comment by jleandroperez** [comment]
Closed via #532. 

Wow 7 years later!! 🔥
