### ISSUE TITLE
Single linebreak not being read into preview on MacOS

### ISSUE THREAD

**Issue by maxorozco213** [Automattic/simplenote-macos#210]
Example:
Typing the following:

"This is the first line.
This line is a separate line."

is output as:

"This is the first line. This line is a separate line."

**Comment by bummytime** [comment]
**Update 5/15/2019 →** Still an issue on Simplenote 1.4.2:

![linebreak](https://user-images.githubusercontent.com/154014/57792154-f75a2c80-7703-11e9-8a5e-184bde0b1bbe.gif)

**Comment by bummytime** [comment]
Related: also an issue with lists:

<img width="773" alt="Napkin 136 05-15-19, 11 28 01 AM" src="https://user-images.githubusercontent.com/154014/57792454-a3037c80-7704-11e9-96e9-d46b93503cec.png">

Ref: https://github.com/Automattic/simplenote-ios/issues/212
