### ISSUE TITLE
Faulty conversion for JP Live Conversion

### ISSUE THREAD

**Issue by KokkieH** [Automattic/simplenote-macos#215]
Reported via Twitter

https://twitter.com/Akihiko1016/status/1007546877888229376

https://twitter.com/Akihiko1016/status/1007571440814575616

Steps to replicate, as confirmed by @hacchism:

When I type “`asdf`” in Japanese Keyboard, it should be “`あsdf`“. But the Live conversion makes it like this:

![screen shot on 2018-06-16 at 21_25_36](https://user-images.githubusercontent.com/11873759/41545340-41230ca8-731b-11e8-92ac-7b5146d90465.png)

When I type “`yukh`” in Japanese Keyboard, it should be “`ゆkh`“. But the Live conversion makes it like this:

![screen shot on 2018-06-16 at 21_32_35](https://user-images.githubusercontent.com/11873759/41545379-54999824-731b-11e8-9a0e-98dd04efb81f.png)

In Japanese, one Japanese letter is composed of two alphabets. For example, when I want to type “`ゆ`“, I need to type “`yu`” and convert “`yu`” to “`ゆ`“. The error this time seems to happen when we type wrong combination of alphabets for Japanese letter.

User report was for v 1.3.3, but also confirmed in v 1.3.4

**Comment by pauljacobson** [comment]
There is what appears to be a related report in 1218654-zen.

The user reported the following:

>Thanks for your great app. Simplenote helps me greatly, but I have a problem.
>When I type Japanese sentences, single bite english characters are garbled.
>These garbled characters are fixed after converting to double bite Japanese characters.
>I found some people says about same situation at app store review.
>What is caused this problem? I use 12inch Macbook and Mac OS X EI Captain ver. 10.11.6.
>If you have any solution, would you tell me please?

The user is using version 1.3.3 of the app.

The user also mentioned the following:

>I have sent screenshot as attachment files. Garbles are fixed as correct alphabets after converting, so I cannot copy and paste those text...sorry.

### Screenshots

Before converting:

![1218654_before_converting](https://user-images.githubusercontent.com/2912202/41762693-3e83d46e-7604-11e8-90b6-36daf3d36402.png)

After converting:

![1218654_after_converting](https://user-images.githubusercontent.com/2912202/41762699-459c3b60-7604-11e8-9d9c-a370dab046cc.png)

**Comment by minolasoft** [comment]
In Mac environment, this issue occur both Kotoeri and Atok.
I attached image and video recording.
<img width="254" alt="image" src="https://user-images.githubusercontent.com/7712137/42604615-aa02fc1a-85ae-11e8-8cf5-3fadd4db95d6.png">
[Simplenote_broken_conversion.mov.zip](https://github.com/Automattic/simplenote-macos/files/2186539/Simplenote_broken_conversion.mov.zip)

**Comment by Robertght** [comment]
#1825591-zen

**Comment by bummytime** [comment]
Closing in favor of #252
