### ISSUE TITLE
Simplenote 1.3.x doesn't sync on macOS 10.11.6 El Capitan

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/simplenote-macos#219]
This is a report from a user in 1229935-zen:

>Simplenote works well in Mac Sierra 10.12.6 on my Mac Mini. But I can't get it to sync at all on my Macbook with El Capitan 10.11.6

#### Steps to reproduce

>I've installed the app 3 x today after download from your site and deleted it twice with Appcleaner to be sure all files are flushed. The progress wheel just spins into eternity when I start up the application. In fact it doesn't show a login window at all, just the main window with a welcome screen. I assume it should open to a fresh login screen? In Sierra everything is fine. It downloads my files and also signs out and back in with the proper screen if need be.

>I was using Notational Velocity to access my Simplenote account for years, which still works fine on both machines. Even when I disable Notational on the El Capitan machine, Simplenote just refuses to load any files or sign out at all, just spins.

#### What I expected

Simplenote is not syncing in macOS 10.11.6.

#### What happened instead

Simplenote should sync correctly on macOS 10.11.x. The app officially supports macOS 10.10 according to the Mac App Store description.

#### Browser / OS version

macOS 10.11.6 El Capitan.

**Comment by mgalbritton** [comment]
There is another report of the same issue in 1227265-zen.

**Comment by mgalbritton** [comment]
Another report of the same issue in 1255336-zen.

**Comment by pcdonohue** [comment]
Also reported at 1273052-zen - OSX 10.11.16 user is also not able to sign out of their app.

**Comment by roundhill** [comment]
Taking a look at this.

**Comment by lizswafford** [comment]
Reported on 1273990-zen - **MacOS 10.11.2**, Simplenote 1.3.5.  There is no sign in button, only a sign out button on the login screen for the app. Requested a screenshot. Reinstalling the app didn't change the outcome.

**Comment by roundhill** [comment]
Seeing this exception in the logs on El Capitan: 

```
7/12/18 2:01:01.171 PM Simplenote[354]: +[NSButton buttonWithTitle:target:action:]: unrecognized selector sent to class 0x7fff76375410
```

I think the login window isn't showing because of this exception.

**Comment by Robertght** [comment]
#1273052-zen - another similar case running Mac OS X El Capitan version 10.11.6 (15G22010)
