### ISSUE TITLE
Add spotlight indexing of notes

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#22]
<a href="https://github.com/tomwitkin"><img src="https://avatars.githubusercontent.com/u/3904502?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [tomwitkin](https://github.com/tomwitkin)**
_Tuesday Sep 24, 2013 at 17:36 GMT_
_Originally opened as https://github.com/Automattic/simplenote-osx/issues/219_

---

**Comment by arunsathiya** [comment]
User requested the same feature. #1057577-zen

**Comment by charliescheer** [comment]
Another request #2397642-zen
