### ISSUE TITLE
Contents of Selected Note not shown when contents of a note is deleted after search

### ISSUE THREAD

**Issue by damiannep** [Automattic/simplenote-macos#220]
Steps to reproduce
1. Open the Mac app.
2. Type in a search word.
3. Select a note to edit (click on a result).
4. Delete the contents of the note.

Expected result: Show the content of the next note in the results.

Actual result: The next note in the search results is selected but it's contents are not shown. To access that note, it is necessary to select another note in the results list first and then return to that note.

<img width="903" alt="hightlighted note but" src="https://user-images.githubusercontent.com/30090682/41973122-61daccc4-7a14-11e8-9673-650bf5e887ec.png">

Reported by user in 1236298-t. I confirmed the steps and outcome.

**Comment by bummytime** [comment]
**Update 5/14/2019 →** Tested in Simplenote 1.4.2 on macOS 10.14.4 (Mojave), still happening:

![lorem](https://user-images.githubusercontent.com/154014/57802276-35167f80-771b-11e9-856f-d4b12298b549.gif)

**Comment by jleandroperez** [comment]
Closed via #764.

Apologies it took us a while to get to this one!!
