### ISSUE TITLE
User having trouble with a search "bug"

### ISSUE THREAD

**Issue by marcuswisecaesar** [Automattic/simplenote-macos#221]
> The problem is if you are trying to find a multiple word phrase such as "blue car", it shows all documents that happen to have both those words in it, even if it doesn't actually contain "blue car" as a phrase. That makes the search almost useless for multiple word phrases because it shows mostly irrelevant results.

 The user also reports that this is a "constant frustration" with Simplenote.  I have responded by letting the user know that the issue has been reported and thanked them for getting in contact.

**Comment by dmsnell** [comment]
@roundhill in the Electron app we added some slightly-more-complicatly search syntax that might be useful here.

https://github.com/Automattic/simplenote-electron/pull/604

**Comment by jleandroperez** [comment]
Closing as cannot repro.

Simplenote 2.2, tested on macOS 10.15 and macOS 10.13.

Please feel free to reopen if needed, thank you!

**Comment by jleandroperez** [comment]
Adding a +1 vote for `Exact Phrase Search` to our (internal) Simplenote Feature Requests list.

**Thanks everyone!**
