### ISSUE TITLE
Cursor color in Dark theme

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/simplenote-macos#222]
When editing notes in Dark theme, default macOS mouse cursor color (black) is used. This results in a very low contrast with the dark theme background.

![cursor](https://user-images.githubusercontent.com/25105483/42164922-7a719bcc-7e07-11e8-97d8-6874bd3ecdbe.png)

Potentially related to https://github.com/Automattic/simplenote-macos/issues/207

Note: It is difficult to take screenshot as the mouse cursor disappears automatically, added photo instead.

**Comment by bummytime** [comment]
This is working as expected in Mojave:

![mouse_cursor](https://user-images.githubusercontent.com/154014/57793388-cdeed000-7706-11e9-8936-4fbad92b026e.gif)
