### ISSUE TITLE
Enhancement: Support ODB Editor Suite

### ISSUE THREAD

**Issue by hmelman** [Automattic/simplenote-macos#223]
I'd love to see support for [ODB Editor Suite](https://www.barebones.com/support/develop/odbsuite.html) so that external editors could be easily used on notes. nvAlt supports this and it's the last feature I'd want to switch to Simplenote.

**Comment by bummytime** [comment]
Ref: https://inessential.com/2019/02/25/the_odb_editor_suite_what_i_remember

**Comment by hmelman** [comment]
As an alternative, let me select a note and run choose a File and Folders Service for it from the Services menu.

**Comment by jleandroperez** [comment]
Added +1 vote to ODB support in our internal feature requests system.

Thank you for reaching out!
