### ISSUE TITLE
Keyboard shortcut for tag focus not working

### ISSUE THREAD

**Issue by jeremeylduvall** [Automattic/simplenote-macos#227]
On [our shortcut list](https://simplenote.com/help/#shortcuts), we list out a keyboard shortcut for moving the focus to tags - `Control-tab`.

A user reported in 1293649-zen that this is no longer working, and I can confirm on Simplenote 1.3.6. The other shortcuts I tested seem to work, but the `Control-Tab` shortcut doesn't do anything for me at the moment.

**Comment by wvnutt** [comment]
Thank you (from that user)! While you're at it, please add shortcuts for focusing on the sidebar and toggling Markdown preview! 😬

**Comment by jleandroperez** [comment]
Shortcuts revamped via #888 

 `Cmd + Shift + Y` Toggle between editing note and tags

Thank you!
