### ISSUE TITLE
Add Support for Mojave Dark Theme

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#228]
The app should support the native dark theme added in macOS Mojave.

**Comment by Nyco** [comment]
Seems like it's done in 1.3.7

**Comment by arunsathiya** [comment]
Considering it's available in 1.3.7 and assuming there are no further plans, should we consider closing this one @roundhill?

**Comment by roundhill** [comment]
Yes, there may be a few more coloring tweaks to be done but we've got the core support in there.
