### ISSUE TITLE
Make searching more Google-y

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#23]
<a href="https://github.com/tomwitkin"><img src="https://avatars.githubusercontent.com/u/3904502?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [tomwitkin](https://github.com/tomwitkin)**
_Wednesday Sep 25, 2013 at 17:04 GMT_

---

"note with text "a b c" is matched by search term "a b", but not "a c"! iOS app is good."

**Comment by crankygeologist** [comment]
I would also like to see more advanced search options using double quotes, like "title:blah" which would only find text in the first line of your notes.

**Comment by jleandroperez** [comment]
Closing in favor of #626. Thanks everyone!
