### ISSUE TITLE
Text substitution behaviour on MacOS

### ISSUE THREAD

**Issue by Robertght** [Automattic/simplenote-macos#230]
A user reached us regarding the [text substitution behaviour](http://osxdaily.com/2010/07/23/set-up-text-substitution-in-mac-os-x/) on MacOS.

1. Go into System prefferencs-> Keyboard-> Text and add a couple of text substitutions. Also create one that has another text substitution another one. For instance:
qqq - This is a recursive subtext
testx - This is a recursive substext qqq

2. Move to Simple note and try either of these text, but hit the X button and do not let them autocomplete.
3. Move to another note and switch back to the note before.
4. You'll notice the Text substitution has happened.

The user was super nice to create a video for us. The video can be found in the ticket: 1301908-zen

**Comment by bummytime** [comment]
Closing in favor of #291
