### ISSUE TITLE
Text stuck in incorrect wrapping when switching focus to another app

### ISSUE THREAD

**Issue by liviopv** [Automattic/simplenote-macos#236]
## Issue

When you resize the window, sometimes notes with longs blocks of texts will take longer to adjust text wrapping to the new window size. When that happens, if you switch focus to another app, it get "stuck" with the incorrect wrapping and only resizing the window again and wait a little bit will fix the text wrapping.

## Steps to reproduce

1. Open a note with long text blocks in the Mac app
2. Resize the window to a smaller size and until you're able to "break" the text wrapping
3. Switch focus to another app, like your browser
4. The Simplenote app will get "stuck" in the incorrect text wrapping,

## What I expected

The note should adjust the text wrapping even when inactive, or, at least, when I switched focus back to it.

## What happened instead

The note got stuck in the incorrect text wrapping, even when I switched focus back to it. Only resizing the window again seemed to affect text wrapping

## Screenshots

Video: http://cld.wthms.co/IWA8kr

## System

App version: 1.3.6
Mac OS 10.13.6

User report: 1383328-zen

**Comment by jleandroperez** [comment]
Closing as cannot repro. Simplenote 2.0 / macOS Catalina.

Please reopen if needed. Thank you!!
