### ISSUE TITLE
Published Note Link Not Readable in Dark Theme

### ISSUE THREAD

**Issue by mgalbritton** [Automattic/simplenote-macos#239]
When a note is published using the Dark theme, the link to copy is difficult to read.

Dark: 
![screen shot on 2018-09-09 at 09_51_01](https://user-images.githubusercontent.com/19782997/45265770-24886980-b416-11e8-87f5-b40fedb0a5f6.png)

Light:
![screen shot on 2018-09-09 at 09_55_13](https://user-images.githubusercontent.com/19782997/45265794-80eb8900-b416-11e8-82b6-6a33bb14a19e.png)

**Comment by bummytime** [comment]
Closing in favor of #311
