### ISSUE TITLE
Add keyboard shortcut to show / hide tags sidebar

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#24]
<a href="https://github.com/tomwitkin"><img src="https://avatars.githubusercontent.com/u/3904502?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [tomwitkin](https://github.com/tomwitkin)**
_Wednesday Sep 25, 2013 at 19:56 GMT_

---

**Comment by bummytime** [comment]
Already implemented. Closing.
