### ISSUE TITLE
Notes offset after update to 1.3.7

### ISSUE THREAD

**Issue by igorkulman** [Automattic/simplenote-macos#243]
I have updated the macOS app to 1.3.7 through the AppStore and now all my notes are offset from the left. It looks strange and it is a waste of space.

Here is a (redacted) screenshot

![screen shot 2018-09-25 at 18 23 40](https://user-images.githubusercontent.com/4746070/46028322-7efd1780-c0f0-11e8-82a0-04adec3b2e07.png)

**Comment by roundhill** [comment]
Hi! We forgot to put in the release notes about this new setting for note readability. 😞You can put it back to full width by going to `View -> Note Editor -> Line Length -> Full`.
