### ISSUE TITLE
Empty trash arrow went missing

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#249]
I think there used to be a little arrow that would appear on hover near the trash button. You can still click where it used to show, and the empty trash popup appears:

<img width="226" alt="screen shot 2018-10-10 at 9 58 49 am" src="https://user-images.githubusercontent.com/789137/46753106-c5678000-cc73-11e8-9193-eb79edbafd87.png">

I would vote to just update the context menu when you right-click on the trash to have the empty trash option there.

**Comment by msilbers** [comment]
I think that this button is entirely missing now. I see no option to empty trash on the Mac native app for Simplenote. I'm on 1.4.0 and a Simplenote user wrote in about this as well.
