### ISSUE TITLE
On Mavericks, uninstalling app from Launchpad and then reinstalling app causes the app to prompt for username and password on every subsequent launch 

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#25]
<a href="https://github.com/tomwitkin"><img src="https://avatars.githubusercontent.com/u/3904502?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [tomwitkin](https://github.com/tomwitkin)**
_Wednesday Sep 25, 2013 at 19:57 GMT_

---

"I installed SimpleNote from the App Store, and then I removed it using Launchpad. In OS X 10.9, this deletes the application itself, and it ALSO deletes everything the applications subfolder in ~/Library/Containers. After re-installing SimpleNote, I have to log in on every launch of the application, as if I’m launching it for the first time. The data is there as it doesn’t have to re-sync everything down, but login credentials aren’t saved."

**Comment by dartiss** [comment]
One further report - #2904675-t.

The user is running Mountain Lion, which he is aware is no longer supported. He also confirms that the workaround provided above does not work for him.

**Comment by deskroid** [comment]
Another report - #2935138-t

The user is running the app on OS X Mountain Lion (version 10.8) and it asks for a password on every launch. Letting him know that OSX < 10.9 are not supported as well.

**Comment by bummytime** [comment]
Closing because of issue age.
