### ISSUE TITLE
Add an alert, or remove the ability to delete a note by hitting the backspace or delete key

### ISSUE THREAD

**Issue by mirka** [Automattic/simplenote-macos#251]
_[Requested](https://github.com/Automattic/simplenote-electron/issues/553) by @dougmorin:_

#### Steps to reproduce
1. Click a note title
2. Press the backspace/delete key

#### What I expected
Note to prompt for deletion, or to not delete at all.

#### What happened instead
Note moved to trash without prompting

#### OS version
Mac OS Sierra

**Comment by bummytime** [comment]
Useful feature that many people use, however there probably could be a better UX here — e.g. one the first time hitting backspace on the note list, ask what the user would like to happen. Perhaps simply a global setting?

Leaving this issue open for now.

**Comment by jleandroperez** [comment]
Closing this one, since:

1. The note is in Trash afterwards
2. macOS works this exact same way. You can delete anything, and there is no confirmation

Thanks everyone!!
