### ISSUE TITLE
Shade of black in Dark mode doesn't match Apple's guidelines

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/simplenote-macos#253]
A user reported the following in 1483211-zen:

>Your black theme does not quite match the guidelines of Apple. Black is too black. This is not good for use.

The user provided this screenshot that indicates that the shade of black used in Simplenote's Dark mode doesn't match Apple's shade used in macOS windows:

![simplenote_macos_dark](https://user-images.githubusercontent.com/2912202/46913974-9f0d5180-cf9f-11e8-8e9b-bfa1aa75e592.jpg)

This may be related to issue #222

**Comment by GlebZakharenko** [comment]
Here is a more correct example. On too dark black there are no shadows at all.
![image](https://user-images.githubusercontent.com/5507748/46914050-c7498000-cfa0-11e8-9254-785985dca292.png)

**Comment by roundhill** [comment]
The best app to compare with is `Mail.app` which Simplenote matches up with exactly. We're using Apple's system colors on Mojave, not anything custom.

I think we can improve the look by using the toolbar appearance, and adding translucency so the tags list. That would get it feeling even more native.

**Comment by roundhill** [comment]
Yeah, you’re pointing to the toolbar which we can improve by setting its appearance so that it gets the gradient there. It would take a bit of work to get the divided under the toolbar to look proper.

**Comment by GlebZakharenko** [comment]
In general, there is an external application of "Tnings". And they perfectly adapted their design. I hope your adptation no worse. Thank you in advance, guys!
<img width="2270" alt="2018-10-17 18 12 24" src="https://user-images.githubusercontent.com/5507748/47096806-a56a2a80-d238-11e8-9af0-c676c5e18c21.png">

**Comment by jleandroperez** [comment]
Closing this one for now. We'll be refreshing the macOS color scheme shortly.

Thanks everyone!
