### ISSUE TITLE
Bug: Tags are not available in the revisions

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/simplenote-macos#254]
When trying to reproduce this issue https://github.com/Automattic/simplenote-electron/issues/887 on Simplenote Electron app, I noticed that tags are nowhere to be seen on the revisions. 

Describe the bug: Tags are not available in the revisions for Simplenote for Mac, when using the revisions feature.

**Steps to reproduce**: Follow the steps below to reproduce the issue. 

- Create a note 
- Modify the note contents multiple times and add single/multiple tags during this process
- Remove a few/all the tags
- Use the revisions feature to check all available revisions

**What is expected:** Tags are shown in the revisions where they were added

**What happens instead:** The tags are not seen instead

## More notes

When one compares [this video from Simplenote Electron](https://cloudup.com/cauBEfsn9zB) with [this video from Simplenote for Mac](https://cloudup.com/cZjKcO4vcIF), one can notice that the latter video doesn't show tags in the revision.

## Image from Simplenote Electron

<img width="1136" alt="screenshot 2018-10-14 at 22 59 57" src="https://user-images.githubusercontent.com/18581859/46919969-f09bf780-d004-11e8-816f-286af8aa3c35.png">

## Image from Simplenote for Mac

<img width="1012" alt="screenshot 2018-10-14 at 23 00 06" src="https://user-images.githubusercontent.com/18581859/46919970-f09bf780-d004-11e8-9258-4e6a7cd8b565.png">

**Comment by jleandroperez** [comment]
Closing in favor of #577 
Thank you Arun!!
