### ISSUE TITLE
Bug: Unable to restore notes when using dark mode, intermittently

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/simplenote-macos#255]
**Describe the bug:** It's not possible to restore notes from history when using dark mode for the first time, or when the dark mode settings are changed on Mac's `Systems preferences` (not on Simplenote's settings which was introduced here https://github.com/Automattic/simplenote-macos/pull/246)

**Steps to reproduce**: Follow the steps below to reproduce the issue. 

- Launch Simplenote for Mac with dark mode set on Mac settings.
- Create a note and modify it multiple times.
- Use the revisions feature to restore a note from the previous stage.

**What is expected:** The `Restore` button is clickable.

**What happens instead:** The `Restore` button cannot be clicked. [Video showing this behaviour](https://cloudup.com/c7s6EJAMxOW).

<img width="1012" alt="screenshot 2018-10-14 at 23 18 49" src="https://user-images.githubusercontent.com/18581859/46920241-dc59f980-d008-11e8-87a1-5437c798f7b2.png">

## When does this happen

- Launches Simplenote for Mac with dark mode, for the first time.
- When the user enables dark mode on Mac settings. (I am not very sure about this. I have been able to reproduce this intermittently)

## More notes

The `Restore` button can be clicked again when the below mentioned workaround is followed.

Switch to light mode on Simplenote settings and come back to dark mode. [Video showing this behaviour](https://cloudup.com/cKkXIPhzqOE). 

<img width="1012" alt="screenshot 2018-10-14 at 23 18 10" src="https://user-images.githubusercontent.com/18581859/46920239-d8c67280-d008-11e8-94a6-834a259d5ead.png">

## Or, is this not related to dark mode?

I should also add that I am not sure if this might be related to the dark mode, or is related to something else entirely.

**Comment by jleandroperez** [comment]
Closing this one as cannot repro.

Tested on macOS Mojave, multiple configurations (System dark / light mode with Simplenote set to "System's appearance", and actually setting the target theme).

The **Restore** button's UX was changed via #284, it's highly likely this issue was fixed as a side effect of such PR.

Please feel free to reopen if this happens ever again!
