### ISSUE TITLE
Theme: dark/light mode does not change with OS

### ISSUE THREAD

**Issue by msilbers** [Automattic/simplenote-macos#256]
I believe the expected behavior is for a manual theme change to override the OS theme change. However, it looks like this is being overridden if the theme was changed before the update as well, which makes it look like it has just stopped working altogether.

@roundhill mentioned that a future update can instead have this behavior reset upon sign out from the app.

#### Steps to reproduce
1. Change theme from light to dark
2. Update to the newest Simplenote app version for MacOS (1.3.8)
3. Change OS to dark mode or light mode

#### What I expected
I expected that the Simplenote theme would change along with the OS, at least until I made a manual change.

#### What happened instead
I am unable to get the Simplenote app to respond to an OS theme change. 

#### Simplenote version
Simplenote 1.3.8

#### OS version
Mac 10.14 - Mojave

**Comment by roundhill** [comment]
I'm thinking of adding a `System Default` option to the `Theme` menu, which would reset the theme selection back to the OS level?
