### ISSUE TITLE
Markdown preview incorrect with manually selected theme

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#257]
If you manually select a theme via the menu on Mojave, the markdown preview still adheres to the system wide setting:

<img width="1026" alt="screen shot 2018-10-16 at 10 11 13 am" src="https://user-images.githubusercontent.com/789137/47034760-17554d80-d12d-11e8-918c-96ad0b68e0a7.png">

**Comment by KokkieH** [comment]
Another report via [Twitter](https://twitter.com/KavirKaycee/status/1052899558798356481)
