### ISSUE TITLE
Undo keyboard shortcut causes notes to duplicate content on other devices

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#26]
<a href="https://github.com/tomwitkin"><img src="https://avatars.githubusercontent.com/u/3904502?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [tomwitkin](https://github.com/tomwitkin)**
_Thursday Oct 31, 2013 at 21:02 GMT_

---

Easily reproducible. 
1. Open Mac app
2. Open iPhone app
3. Make new note on Mac
4. Open note on iPhone
5. Type into Mac
6. Prest cmd + z to undo
7. Type more text on Mac
8. iPhone shows duplicate text

**Comment by jleandroperez** [comment]
Closing as cannot repro. Simplenote 1.9.1 / develop.
