### ISSUE TITLE
Be nicer about Help

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#27]
<a href="https://github.com/mikejohnstn"><img src="https://avatars.githubusercontent.com/u/515035?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mikejohnstn](https://github.com/mikejohnstn)**
_Friday Nov 08, 2013 at 00:35 GMT_

---

Maybe redirect to the website at least:
https://cloudup.com/cuqeeEHdGF6

**Comment by bummytime** [comment]
We now redirect to the website. Closing.
