### ISSUE TITLE
Make markdown editing / mode more like https://typora.io/

### ISSUE THREAD

**Issue by khornberg** [Automattic/simplenote-macos#272]
#### Steps to reproduce
1. Create new note
2. Type "# header<enter>"
3. See "# header" as the text
4. Click circle i icon
5. Click Markdown Formatted
6. Click eye icon
7. See markdown formatted text

#### What I expected

I have no idea how to do it on macOS or how one would implement this. It would be nice to have a markdown mode that automatically changes text to the markdown formatted version. https://typora.io/ does this. So basically, I would like the simplenote synchronization and text field of typora.

Typora seems to be based on electron an other web tech. I'm not sure how to implement those into the macOS or iOS versions. I'm not a big fan of electron apps in the current state as it is yet another Chromium version hogging memory and battery but I know that simplenote for other platforms is implemented that way and to implement this, that may be the only way for now.

#### What happened instead

I had to click a bunch of times to see my markdown formatted version

**Comment by bummytime** [comment]
Thanks for the suggestion @khornberg — closing this in favor of #326.
