### ISSUE TITLE
Keyboard shortcuts for navigation

### ISSUE THREAD

**Issue by joshyudeep** [Automattic/simplenote-macos#273]
First off, thanks so much! I really appreciated the enhancements you've guys made (e.g. dark mode, focus mode, etc). I was wondering if we could have some keyboard shortcuts added to the macOS version.

* Shortcut to get to the All notes section (right now you can nav up/down when you click on a note, but there's no way to get back to that note list from the keyboard after you've selected a note and started editing).
* Shortcut to get to the search bar

I apologize ahead of time if this is a duplicate request. 

Thanks again!

**Comment by jleandroperez** [comment]
Closing in favor of #816. We're kicking off a Shortcuts project shortly, thank you for reaching out!

(And apologies it took us a while to finally get to this one!)
