### ISSUE TITLE
Markdown: Colors changed for tables on light theme

### ISSUE THREAD

**Issue by msilbers** [Automattic/simplenote-macos#274]
#### Steps to reproduce
1. Create a table with markdown on the Simplenote Mac app with more than 3 rows
2. Preview the note

#### What I expected
For the text on the darker lines to be more readable (like previously).

#### What happened instead
The text on the darker lines blends in too much.

#### Simplenote version
1.3.9

#### macOS version
10.14.1

#### Screenshot
<img width="564" alt="screen shot 2018-11-25 at 1 25 57 pm" src="https://user-images.githubusercontent.com/31680407/48982872-072e7780-f0b6-11e8-822e-4f4b8b524f92.png">

Note: publishing the note looks fine with the markdown, just not previewing.

**Comment by arunsathiya** [comment]
I ran into this as well today. This happens only for light theme like noted on title.

<img width="792" alt="Screenshot 2019-03-09 at 14 22 38" src="https://user-images.githubusercontent.com/18581859/54068839-dba35780-4276-11e9-96ac-872aff67b64f.png">

On dark theme, it looks fine. 👍🏽 

<img width="813" alt="Screenshot 2019-03-09 at 14 23 35" src="https://user-images.githubusercontent.com/18581859/54068846-f83f8f80-4276-11e9-9514-1c40ae707655.png">

**Comment by jleandroperez** [comment]
Closing as cannot repro:

- macOS 10.13 + 10.15
- Simplenote 2.2

Please feel free to reopen if needed. Thank you!
