### ISSUE TITLE
Detail view lingers after remote deletion of current note.

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#28]
<a href="https://github.com/roundhill"><img src="https://avatars.githubusercontent.com/u/789137?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [roundhill](https://github.com/roundhill)**
_Saturday Feb 15, 2014 at 16:14 GMT_

---
1. Select a note.
2. On another app, delete the same note.
3. Observe that the note is deleted from the list, but the detail view still shows the note.

**Comment by jleandroperez** [comment]
Closed as cannot repro. 

**Highly likely** fixed via #764
