### ISSUE TITLE
Feature Request: Open markdown preview by default

### ISSUE THREAD

**Issue by sintezcs** [Automattic/simplenote-macos#286]
It will be really useful to have an option to show markdown preview by default. For example, one of the use-cases for me is to store a lot of useful code-snippets and cheatsheets in SimpleNote. And most of these notes are rarely changed, I just need to be able to find then and look through them. I categorize them with tags and add pieces of code and comments, formatted in markdown. Then, every time I want to look through my note I need to click the markdown preview mode to see its nice representation.

#### Implementation details
There can be an option for this in `View->Note Editor` menu. Like "Show markdown preview by default".

#### Expected behavior
If you have "Show markdown preview by default" option enabled:

1. You click on a note in the note list, and this note has markdown content
2. The note will be shown in a markdown preview mode
3. You click on the note body
4. Markdown preview is turned off and you can edit the note

**Comment by sintezcs** [comment]
Hey guys, do you have any updates on this request?

**Comment by jleandroperez** [comment]
Closing in favor of #372.

I'm afraid we don't have an ETA, as of now. But definitely on the list!

Thank you for reaching out!!
