### ISSUE TITLE
Feature Parity: Add Sort by Date Created

### ISSUE THREAD

**Issue by mgalbritton** [Automattic/simplenote-macos#292]
Simplenote on macOS has two sort by options: Alphabetical and Dated Updated. The electron version of Simplenote has: Date Modified, Date Created, and Alphabetical. 

Can we create parity between the apps to have the same sort by options? 

#### Simplenote version
1.4.0 (macOS)
1.3.4 (electron for macOS)

**Comment by bummytime** [comment]
Closing in favor of #33
