### ISSUE TITLE
Scrollbar shown when it's not necessary

### ISSUE THREAD

**Issue by jepelej** [Automattic/simplenote-macos#295]
A scrollbar is briefly shown in the notes list when the mouse hovers over the scrollbar area.

#### Steps to reproduce
1. Open the app
2. Open a tag list that contains only a few notes
3. Click on a note in the left sidebar
4. Click on the note content
5. Slowly move the mouse to the left sidebar
6. A scrollbar is briefly shown

#### What I expected

No scrollbar

#### What happened instead

Scrollbar

#### Simplenote version

Simplenote 1.4.0

#### macOS version

macOS 10.14.2

**Comment by bummytime** [comment]
**Update 5/14/2019 →** Tested in Simplenote 1.4.2 on macOS 10.14.4 (Mojave) and it still happens:

![scrolly](https://user-images.githubusercontent.com/154014/57796932-ea8f0600-770e-11e9-9788-f5178178a233.gif)

**Comment by jleandroperez** [comment]
Closing as cannot repro. Simplenote 1.10 / macOS Catalina.

Thank you!!
