### ISSUE TITLE
Don't load fonts from fonts.google.com

### ISSUE THREAD

**Issue by jepelej** [Automattic/simplenote-macos#296]
Use system fonts in order to provide consistent UI with other apps.

#### Steps to reproduce
1. Open the app
2. Observe a connection to fonts.google.com

#### What I expected

The app should display system fonts

#### What happened instead

The app connects to fonts.google.com

#### Simplenote version

Simplenote 1.4.0

#### macOS version

macOS 10.14.2

**Comment by roundhill** [comment]
The fonts are used for the Markdown preview, so it matches how it will look on simplenote.com when published.
