### ISSUE TITLE
Checklists don't display properly

### ISSUE THREAD

**Issue by tfeb** [Automattic/simplenote-macos#297]
I updated the iOS app a few days ago and have created checklists in some of my notes.  Today I updated the Mac version (current app store release which I think is 1.4.1?).  It knows there are checklists in the notes but the checkbox displays as whitespace and you can't click in it.  Creating a new checklist on the Mac does the same thing.

I'm running 10.12 which may be the problem: if so this should probably be noted somewhere at least.

(I can add more details tomorrow: travelling today.)

**Comment by roundhill** [comment]
Thanks! It may require 10.13... we'll double check.

**Comment by tfeb** [comment]
It would be really cool if it could be persuaded to work in 10.12: I'm going to upgrade to 10.14, but life gets in the way.  Obviously if it's hard then it's a different question.

**Comment by catherineomega** [comment]
I can confirm that it also doesn't display correctly on 10.11. Is it just the emoji or icon font required?

**Comment by kriskarkoski** [comment]
#1786716-zen

**Comment by iamgabrielma** [comment]
1854243-zen
