### ISSUE TITLE
Notes with only an URL transforms all other notes plain text to URL as well

### ISSUE THREAD

**Issue by iamgabrielma** [Automattic/simplenote-macos#298]
Having a note with an URL alone, or starting  seems to transform all plain text in other notes to URL as well.

#### Steps to reproduce
1. Create a new note
2. Write down an URL, for example http://simplenote.com/
3. Check the other notes
4. See how all text has been transformed in an URL as well

**Video of the issue:** 

http://cld.wthms.co/22S6YA

Reported on 1789402-zen
Tested with 1.4.1

**Comment by pauljacobson** [comment]
Also reported in 1783250-zen

The user is using version 1.4.1

**Comment by edequalsawesome** [comment]
Issue was also reported in #1800294-zen:

> if a note has an URL in the first line, all text across ALL subsequent notes is treated and styled as a hyperlink to that first url, even subsequent URLs in that or other notes. Moving that URL to the second line, fixes this behavior, but moving it back replicates it consistently.

**Comment by mgalbritton** [comment]
Another report in #1791526-zen

**Comment by roundhill** [comment]
Reproduced: 

<img width="154" alt="screen shot 2019-02-19 at 10 45 53 am" src="https://user-images.githubusercontent.com/789137/53039369-e6b35680-3433-11e9-8dca-d5f14abde1ee.png">

**Comment by KristinaKay** [comment]
Another report: 1806484-zen

**Comment by iamgabrielma** [comment]
1813279-zen
