### ISSUE TITLE
Restore last selected note on startup

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#3]
<a href="https://github.com/mikejohnstn"><img src="https://avatars.githubusercontent.com/u/515035?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mikejohnstn](https://github.com/mikejohnstn)**
_Wednesday Jun 05, 2013 at 20:14 GMT_

---

**Comment by jleandroperez** [comment]
Closing as won't fix.
