### ISSUE TITLE
Support accent characters in search

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#30]
<a href="https://github.com/fredrocious"><img src="https://avatars.githubusercontent.com/u/43576?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [fredrocious](https://github.com/fredrocious)**
_Monday Jul 28, 2014 at 19:31 GMT_

---

**Comment by jleandroperez** [comment]
Closed via #651

SimplenoteSearch (Swift Package) already supports accents. Thank you Dan!

(Wooo 4 years ago!!)
