### ISSUE TITLE
Delete from trash

### ISSUE THREAD

**Issue by madalingavanarescu** [Automattic/simplenote-macos#300]
#### Steps to reproduce
1. Delete a note from All Notes.
2. The note goes into Trash.
3.1. "Delete Note" button is unclickable in Trash.
3.2. The note still appears in the Trash even after I deleted it completely from an Android Device.

**Comment by bummytime** [comment]
**Update 5/14/2019 →** Tested in Simplenote 1.4.2 on macOS 10.14.4 (Mojave) and still occurring:

![delete](https://user-images.githubusercontent.com/154014/57796831-a7cd2e00-770e-11e9-8025-6f5ce40c0200.gif)
