### ISSUE TITLE
Checklists: Formatting lost when copy-pasting checklists

### ISSUE THREAD

**Issue by KokkieH** [Automattic/simplenote-macos#307]
#### Steps to reproduce
1. Create a new note
2. Create a checklist and add a few items to it.
3. Highlight some or all of the checklist items and right-click ->Cut / Cmd-X or Copy / Cmd-C
4. Create a new note and paste

#### What I expected
For the pasted content to still display as a checklist

#### What happened instead
Only the text content is pasted, with the checklist formatting being lost.

This works as expected in the Electron app.

#### Simplenote version
1.4.2

#### macOS version
10.14.2

#### Screenshot / Video
![checklist](https://user-images.githubusercontent.com/11873759/53429542-17ead400-39aa-11e9-96c3-f8acf0d8efbc.gif)

Reported via [Twitter](https://twitter.com/EnricoFermi18/status/1100239120658563075)

**Comment by nb** [comment]
Just a note that I run into this on a daily basis.

**Comment by rachelmcr** [comment]
This came up in a ticket: 2283992-zen

In this case, the user often copies and pastes from Simplenote to the Mail app, and it's confusing when the checkboxes disappear.

**Comment by rp8085** [comment]
+1 to this. I run into this on a daily basis as well.

**Comment by sarahfg** [comment]
Reported in #2647191-zen on the Mac App

**Comment by msilbers** [comment]
reported in #2739444-zen for the MacOS app

**Comment by darnelldibbles** [comment]
Reported on https://twitter.com/EnricoFermi18/status/1252672035135934465 for the MacOS app

**Comment by jleandroperez** [comment]
Closed via #706 / Simplenote Mark 2.5.

Thank you!

**Comment by garretmh** [comment]
Shouldn't this be fixed in version 2.5? I'm still seeing the behavior.

**Comment by jleandroperez** [comment]
@garretmh yes! fixed in 2.5.

Would it be possible to send repro steps (or a sample video?). Thanks in advance!

**Comment by garretmh** [comment]
@jleandroperez Here's a fairly minimal video showing the behavior.

https://user-images.githubusercontent.com/1526013/103795372-828be280-500b-11eb-95ba-78a96a02c734.mov

**Comment by jleandroperez** [comment]
Thank you for the clip @garretmh , much appreciated!

Quick Q: what's the OS version you're currently running?

**Comment by garretmh** [comment]
Big Sur 11.1

**Comment by jleandroperez** [comment]
Closing as fixed via #835 / Simplenote 2.8 (Release: Feb 22nd).

### Background:
1. Originally fixed via #706 
2. The Fix was contained within a Swift Extension
3. (And) such extension was missing in the AppStore Target.

I'm sorry it took us a bit to get this one fixed @garretmh !! And thanks **A LOT** for reaching out!!

**Comment by pachlava** [comment]
[testing] fix/feature verified on MBP 16" Intel | macOS 11.2 | Simplenote 2.8 beta3 (11220)
