### ISSUE TITLE
Focus mode improvement suggestion

### ISSUE THREAD

**Issue by kwonye** [Automattic/simplenote-macos#308]
From a user's feedback:

> Focus mode (mac app) is amazing! Such a great update.
> 
> However, why not take it all the way and have the top navigation bar (with history, share, delete, and info) and the tags also hide while in the mode?
> 
> I imagine that the type of people using focus mode would want as little visible as possible, considering that if they need to quickly tag/share a note it's SO easy to switch out of it using the new focus toggle.
> 
> If someone is using simplenote to draft a long piece of writing, the vast majority of the time that is spent writing the tag line/top navigation bar is sitting there unnecessarily.
> 
> Again, thank you for a fantastic and well implemented focus mode. Just wondering, why not take it further?

**Comment by jleandroperez** [comment]
Closing this one since as part of #458 we're actually redesigning the Toolbar.
