### ISSUE TITLE
Undo cmd-z sometimes stops working

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#31]
<a href="https://github.com/fredrocious"><img src="https://avatars.githubusercontent.com/u/43576?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [fredrocious](https://github.com/fredrocious)**
_Tuesday Sep 16, 2014 at 00:32 GMT_

---

**Comment by yogesh-zendrive** [comment]
This is still not fixed and this is extremely annoying if you work a lot with lists.
The most annoying thing is that if you undo and redo in a list then it completely screws up the list and there's no way to go back to whatever you had earlier.

I have not been able to use undo function of Simplenote forever and this is so annoying that I feel the need to try out other options even if I love Simplenote 😭

PLEASE FIX THIS.

**Comment by joofsh** [comment]
+1 this still doesn't work. This is making me start to look at other note tools.

If someone was able to point me to the relevant code I'd be interested in trying to fix this myself to give back and contribute

**Comment by roundhill** [comment]
Seeing if I can fix this for the next release.

**Comment by adglopez** [comment]
wondering if anyone else is experiencing this issue again?  running version 2.0.0 on Linux Ubuntu 20, installed using .deb package :thinking: 
worth mentioning Ctrl + Z doesn't work, but using the app menu and/or contextual menu works fine

(already made sure that the same keyboard shortcut works fine in any other app)

**Comment by ynadlunar** [comment]
same here

**Comment by jleandroperez** [comment]
Hello there @adglopez + @ynadlunar !!

I'm afraid this issue is for our native Mac app. We're tracking issues in [the Electron app here](https://github.com/Automattic/simplenote-electron/issues/2426) (which is the Simplenote version available in Linux / Windows).

Please feel free to add any extra details you may have, that would help us a lot!!

Thanks in advance!!
