### ISSUE TITLE
Editor: Incorrect Japanese characters rendered

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/simplenote-macos#310]
This is a user report in 1832556-zen. It may be related to the following issues: #252 and #215

#### Steps to reproduce

1. The user types character combinations to produce a specific circle character
2. The Simplenote editor renders the incorrect character

#### What I expected

This is the desired result: https://cld.wthms.co/YldU4L

#### What happened instead

When the same steps were reproduced in Simplenote, the following occurred: https://cld.wthms.co/p2ZL0i

#### Simplenote version

To be confirmed

#### macOS version

To be confirmed

**Comment by jordesign** [comment]
User confirmed they are using this version:

> Simplenote 1.4.2 via App Store on macOS 10.13.6 (17G5019).

**Comment by bummytime** [comment]
Closing in favor of #252
