### ISSUE TITLE
Publish button not readable in light theme

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/simplenote-macos#311]
When using the light theme on Simplenote Mac app, the Publish button is not readable. It appears in light text as indicated below.

<img width="1079" alt="Screenshot 2019-03-09 at 14 18 33" src="https://user-images.githubusercontent.com/18581859/54068878-42c10c00-4277-11e9-83a1-86ba4574fa02.png">
<img width="1067" alt="Screenshot 2019-03-09 at 14 18 43" src="https://user-images.githubusercontent.com/18581859/54068879-4359a280-4277-11e9-85d0-6c8e36b12e1c.png">

On dark theme, it is fine.

<img width="1120" alt="Screenshot 2019-03-09 at 14 26 19" src="https://user-images.githubusercontent.com/18581859/54068894-58363600-4277-11e9-87ff-e7513c3d58d6.png">
<img width="1141" alt="Screenshot 2019-03-09 at 14 26 26" src="https://user-images.githubusercontent.com/18581859/54068895-58363600-4277-11e9-9e23-13c20483b291.png">

Related issue for the light published link color on dark theme - https://github.com/Automattic/simplenote-macos/issues/239

**Comment by jleandroperez** [comment]
@arunsathiya **thank you** for reporting this one!!
