### ISSUE TITLE
Checkboxes Are Hidden after Switching Theme

### ISSUE THREAD

**Issue by theck13** [Automattic/simplenote-macos#321]
### Expected
After switching theme, checkboxes previously shown in notes with checklists are shown in the new theme.

### Observed
After switching theme, checkboxes previously shown in notes with checklists are hidden in the new theme.

### Reproduced
1. Create note with checklist including checked and unchecked checkboxes.
2. Notice checkboxes are shown in checklist.
3. Go to **_View_** > **_Theme_**.
4. If **_Light_** is selected, choose **_Dark_**.  If **_Dark_** is selected, choose **_Light_**.
5. Notice checkboxes are hidden in checklist.
6. Select another note.
7. Select previous note.
8. Notice checkboxes are shown in checklist.
9. Repeat Step 2 through Step 8 with opposite theme.

See the video [here](https://drive.google.com/open?id=1b1lydx_GvIf92_dmdWZ0luj5GY109rfo) for illustration.

Make|Model|macOS Version|App Version
-|-|-|-
Apple|MacBook Pro|10.14.4|1.4.2

**Comment by krutidugade** [comment]
A user reported this bug here - #2007689-zen

**Comment by theck13** [comment]
@krutidugade, can you add the details below from the ticket here?

Make|Model|macOS Version|App Version
-|-|-|-
SYSTEM_MAKE|SYSTEM_MODEL|MACOS_VERSION|APP_VERSION

**Comment by krutidugade** [comment]
User hasn't reverted with details and I've sent another reminder asking for details. This is all we know so far.

Make|Model|macOS Version|App Version
-|-|-|-
Apple|SYSTEM_MODEL|MACOS_VERSION|APP_VERSION

**Comment by jleandroperez** [comment]
Closing this one since it's not happening anymore.
Verified on Simplenote 10.11, macOS High Sierra and Catalina.

Thank you Tyler!!
