### ISSUE TITLE
Info Button Disabled and Shown When Viewing Trashed Notes

### ISSUE THREAD

**Issue by theck13** [Automattic/simplenote-macos#322]
### Expected
The ***Info*** button is hidden or visibly different than shown enabled buttons when viewing trashed notes.

### Observed
The ***Info*** button is shown and not visibly different than shown enabled buttons when viewing trashed notes.

### Reproduced
1. Create at least one note and one trashed note.
2. Select ***All Notes*** in left pane.
3. Notice ***History***, ***Share***, ***Trash***, and ***Info*** buttons are shown above note in right pane.
4. Click ***Info*** button.
5. Notice ***Info*** button color does change while clicked.
6. Notice note information is shown.
7. Select ***Trash*** in left pane.
8. Notice ***History*** and ***Share*** buttons are hidden above note in right pane.
9. Notice ***Trash*** and ***Info*** buttons are shown above note in right pane.
10. Click ***Info*** button.
11. Notice ***Info*** button color does not change while clicked.
12. Notice note information is not shown.

See the video [here](https://drive.google.com/open?id=12fD7tArvmT0JQq--EPWbgzBpj9_dqS4D) for illustration.

Make|Model|macOS Version|App Version
-|-|-|-
Apple|MacBook Pro|10.14.4|1.4.2

**Comment by jleandroperez** [comment]
Closing this one since it's been addressed via #458

Thank you Tyler!!
