### ISSUE TITLE
Make the tags + note sidebars resizeable

### ISSUE THREAD

**Issue by bummytime** [Automattic/simplenote-macos#327]
Currently the tags + note list sidebars are not resizable (even when dragging the window larger):

<img width="867" alt="Screen Shot 2019-05-15 at 12 29 58 PM" src="https://user-images.githubusercontent.com/154014/57796209-6b4d0280-770d-11e9-810a-e0e104add6f6.png">

Let's make that happen.

Ref: #80, #166

**Comment by jleandroperez** [comment]
Implemented via #458 

Thank you Bummy!!
