### ISSUE TITLE
 Note List Sorting: Not consistent with other clients

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#33]
<a href="https://github.com/roundhill"><img src="https://avatars.githubusercontent.com/u/789137?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [roundhill](https://github.com/roundhill)**
_Friday Dec 19, 2014 at 16:54 GMT_

---

We have added alpha sort, but users might want to sort Ascending/Descending or by created date.

**Comment by bummytime** [comment]
From https://github.com/Automattic/simplenote-macos/issues/292

> Simplenote on macOS has two sort by options: Alphabetical and Dated Updated. The electron version of Simplenote has: Date Modified, Date Created, and Alphabetical.

**Comment by bummytime** [comment]
From https://github.com/Automattic/simplenote-macos/issues/170

> I have a lot of notes that would benefit from staying separate, if there was a way to manually order notes. Anyone have a plan to add manual note sorting?
> 
> Manual sorting would be added in addition to Alphabetical and Date Updated.

**Comment by bummytime** [comment]
Current sorting UI on macOS client:

<img width="913" alt="Screen Shot 2019-05-23 at 2 44 30 PM" src="https://user-images.githubusercontent.com/154014/58281698-5bff3200-7d69-11e9-9f02-5e669a4756b1.png">
