### ISSUE TITLE
Change tag name to all capital letters will delete it

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#34]
<a href="https://github.com/roundhill"><img src="https://avatars.githubusercontent.com/u/789137?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [roundhill](https://github.com/roundhill)**
_Friday Jan 16, 2015 at 16:54 GMT_

---
1. Pick a tag to rename
2. Rename it the same name, but in all capital letters
3. The tag will disappear

**Comment by bummytime** [comment]
**Update 5/14/2019 →** Tested in Simplenote 1.4.2 on macOS 10.14.4 (Mojave) and this issue no longer occurs.
