### ISSUE TITLE
Prevent data loss when signing out

### ISSUE THREAD

**Issue by bummytime** [Automattic/simplenote-macos#342]
When signing out of the macOS app, it's possible to have un-synced changes locally and the user receives **no** warning. 

**To repro:**

1. Open Simplenote macOS
2. Kill you local network connection (go offline)
3. Open a note and change it
4. Sign out of the app
5. Notice the app signs out and all local notes are deleted

On Android, iOS, and Electron we have a screen similar to this:

<img width="165" alt="Napkin 152 06-25-19, 5 19 43 PM" src="https://user-images.githubusercontent.com/154014/60137720-757f0980-976d-11e9-8259-26a8cadc09eb.png">

Let's implement a dialog like this to protect against data loss.

**Comment by jleandroperez** [comment]
Closing this one since it's already supported in Simplenote macOS 😄 

Thank you Bummy!!

<img width="300" src="https://user-images.githubusercontent.com/1195260/92932065-c5053000-f41a-11ea-8a6e-9d353699a2b1.png">
