### ISSUE TITLE
Remove Simperium link from About screen

### ISSUE THREAD

**Issue by bummytime** [Automattic/simplenote-macos#349]
The current about screen looks like this:

<img width="446" alt="Screen Shot 2019-07-05 at 12 36 47 PM" src="https://user-images.githubusercontent.com/154014/60737911-ff736300-9f21-11e9-84de-af39d9fa47ce.png">

Let's remove the Simperium link from this view...much like we did in https://github.com/Automattic/simplenote-ios/pull/349

**Comment by jleandroperez** [comment]
I was in the neighborhood... and saw this one!. Removed via #374
