### ISSUE TITLE
Add 'List Assist'

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#35]
<a href="https://github.com/roundhill"><img src="https://avatars.githubusercontent.com/u/789137?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [roundhill](https://github.com/roundhill)**
_Thursday Feb 12, 2015 at 17:10 GMT_

---

Add auto-bullets (and numbering?) for lists typed in the editor.

iOS and Android apps already have this.

**Comment by bummytime** [comment]
This now works for bullets, but not numbering.

**Comment by jleandroperez** [comment]
Closing this one **for now**. To be added as part of the Spring Cleaning project!
