### ISSUE TITLE
Missing down arrow for the tag list

### ISSUE THREAD

**Issue by Robertght** [Automattic/simplenote-macos#360]
I'm unable to see the down arrow next to the tag when hoever, however, it looks like a overlapping/visibility issue because when I click a bit outside the container, the arrow is actually there:

The first clicks are right clicks on the tags, but the second ones are on the (invisible) arrow button:

https://monosnap.com/file/TdKo6vj9kAiX87BjydYH0Dz9Bw2imZ

Simplenote 1.5.0
macOS 10.14.5

**Comment by jleandroperez** [comment]
Closing this one since, as per Spring Cleaning, there isn't expected to be an arrow anymore.
Thank you!!

Ref. #458
