### ISSUE TITLE
Checklists: Checkbox circles in dark theme are the wrong color

### ISSUE THREAD

**Issue by msilbers** [Automattic/simplenote-macos#362]
### Expected
When adding checklists in dark theme, it should look like this:

<img width="179" alt="checklist-correct" src="https://user-images.githubusercontent.com/31680407/62397318-7b71c280-b543-11e9-8d7c-7e1075f1c4c1.png">

### Observed
Instead, especially when switching from light theme or system setting, it looks like this:

<img width="198" alt="Screen Shot 2019-08-02 at 4 35 47 PM" src="https://user-images.githubusercontent.com/31680407/62397420-da373c00-b543-11e9-90c9-220fa272f1eb.png">

### Reproduced
1. Set MacOS system setting to Light
2. Open Simplenote and switch the theme to System Appearance
3. Then switch the theme to Dark
4. Add checklist items

Make|Model|OS Version|App Version
-|-|-|-
Apple | MacBook Pro | 10.14.5 | 1.5
Apple | MacBook Pro | 10.14.5 | 1.6
Apple | MacBook Pro | 10.14.6 | 1.5

**Comment by msilbers** [comment]
"One feature request I have is that on MacOS, in dark mode, the checklist radio button is really really hard to see. To the point that I don't use it."

reported by a user in #2463382-zen

**Comment by rezzap** [comment]
"The checkboxes in the dark theme are really hard to see"

2608575-zen

**Comment by mgalbritton** [comment]
Reported in #2608367-zen.

**Comment by msilbers** [comment]
reported in #2719371-zen for Simplenote 1.9.1

**Comment by melindahelt** [comment]
Reported in #2769950-zen

• MacBook Pro 2018
• OSX Mojave 10.14.6
• Simplenote v 1.91

**Comment by jleandroperez** [comment]
Closing this one as cannot repro anymore.

- Simplenote 1.10
- macOS 10.14 **and** macOS 10.15

Thanks everyone!
