### ISSUE TITLE
Implement Rating Reminder

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#37]
<a href="https://github.com/jleandroperez"><img src="https://avatars.githubusercontent.com/u/1195260?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jleandroperez](https://github.com/jleandroperez)**
_Wednesday Mar 11, 2015 at 13:05 GMT_

---

We need to replicate the same Rating-Reminder mechanism we've got in WordPress iOS app.
Since one of the involved helpers is iOS only, let's investigate alternatives.

@drw158 (Sorry about spamming you!), same question as in [this issue](https://github.com/Automattic/simplenote-ios/issues/268). What do you think about having an extra row (Note List) asking for feedback?

Thank you!

**Comment by jleandroperez** [comment]
Closing this one for now. Let's reopen if needed!
