### ISSUE TITLE
Alphabetise tag list

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#38]
<a href="https://github.com/rachelsquirrel"><img src="https://avatars.githubusercontent.com/u/7946521?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rachelsquirrel](https://github.com/rachelsquirrel)**
_Tuesday May 12, 2015 at 13:09 GMT_

---

It would be great to be able to sort the list of tags alphabetically

**Comment by grizzee** [comment]
please add this. I think thats very important if you work with tags.

**Comment by kriskorn** [comment]
Another request - #1335518-zen

**Comment by bummytime** [comment]
Already implemented. Closing.
