### ISSUE TITLE
Move search field

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#39]
<a href="https://github.com/rachelsquirrel"><img src="https://avatars.githubusercontent.com/u/7946521?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rachelsquirrel](https://github.com/rachelsquirrel)**
_Saturday May 16, 2015 at 07:09 GMT_

---

The search field on the Mac app is at the bottom of the tag list while on the web app and mobile apps it's at the top. We've had some requests to move it on the Mac app to the top for easier access and consistency across devices.

t57919

**Comment by bummytime** [comment]
Closing this for now. We can reopen this issue if the team feels kind of UI update provides a big UX improvement.

/cc @SylvesterWilmott
