### ISSUE TITLE
Show share/publish icon in note list

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#4]
<a href="https://github.com/mikejohnstn"><img src="https://avatars.githubusercontent.com/u/515035?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mikejohnstn](https://github.com/mikejohnstn)**
_Monday Jun 10, 2013 at 19:09 GMT_

---

**Comment by bummytime** [comment]
The (old) web app had the published icon for any individual note:

<img width="728" alt="sharing_icon" src="https://user-images.githubusercontent.com/154014/58282571-c022f580-7d6b-11e9-90df-c9b0f0f335df.png">
