### ISSUE TITLE
Fugitive Cursor

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#40]
<a href="https://github.com/jleandroperez"><img src="https://avatars.githubusercontent.com/u/1195260?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jleandroperez](https://github.com/jleandroperez)**
_Tuesday Jun 09, 2015 at 18:53 GMT_

---
#### Steps:
1. Launch Simplenote OSX
2. Add a new note
3. Add a new list. Reach the end of the visible area
4. Add a new line

As a result, the cursor will [go fugitive](https://cloudup.com/ca1Ta-QVjZ0).

**Comment by jleandroperez** [comment]
Closing as cannot repro (anymore!!)
