### ISSUE TITLE
Enable Hardened Runtime (Update Sparkle)

### ISSUE THREAD

**Issue by loremattei** [Automattic/simplenote-macos#400]
Apple is going to make Notarization mandatory starting from January 2020.
In order to successfully notarize the app, the binary has to be built with the `Hardened Runtime` compiler flag enabled.
Currently, Simplenote MacOS crashes when compiled with `Hardened Runtime` because of `Sparkle`, making notarization impossible.

Note that notarization is only requested for the beta version of the app which is distributed on HockeyApp/AppCenter.

**Comment by jleandroperez** [comment]
Closed via #481 and #498

Thank you Lore!!
