### ISSUE TITLE
Checklist "Completed Task" Sign Is Inverted: Version 1.8

### ISSUE THREAD

**Issue by katinthehatsite** [Automattic/simplenote-macos#401]
### Steps to reproduce:

1) Install version 1.8. of Simplenote
2) Open a note
3) Create a checklist
4) Check off the task

### Expected
1. For the completed task sign to look like this:

<img width="270" alt="Screen Shot 2019-11-18 at 3 58 46 PM" src="https://user-images.githubusercontent.com/25575134/69093399-5c2c7180-0a1c-11ea-93a4-a8e1f95f3e66.png">

This is what I see on Version 1.7.0

### Observed
The mark for the completed tasks looked inverted: 

<img width="463" alt="Screen Shot 2019-11-18 at 3 59 57 PM" src="https://user-images.githubusercontent.com/25575134/69093465-7d8d5d80-0a1c-11ea-916d-273c4c95511b.png">

***(Optional)*** If applicable, add screenshots, animations, or videos to help illustrate your problem.

***(Optional)***
MacOS Version: Catalina 10.15.1
Simplenote: 1.8
Tested in both dark and light modes.

Make|Model|macOS Version|App Version
-|-|-|-
SYSTEM_MAKE|SYSTEM_MODEL|MACOS_VERSION|APP_VERSION

**Comment by rachelmcr** [comment]
Thank you for the report!

cc @jleandroperez I reproduced this and confirmed it's new as of the 1.8 beta.

**Comment by jleandroperez** [comment]
Thank you @katinthehatsite and @rachelmcr !!!
