### ISSUE TITLE
Archive notes

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#41]
<a href="https://github.com/rachelsquirrel"><img src="https://avatars.githubusercontent.com/u/7946521?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rachelsquirrel](https://github.com/rachelsquirrel)**
_Monday Jun 15, 2015 at 11:15 GMT_
_Originally opened as https://github.com/Automattic/simplenote-osx/issues/339_

---

There are a number of requests in the forums to be able to archive notes:
t48671

**Comment by jleandroperez** [comment]
Closing this one for now. Let's reopen if needed.
