### ISSUE TITLE
Have problem with auth on macos mojave 

### ISSUE THREAD

**Issue by PhotolocaDeveloper** [Automattic/simplenote-macos#410]
Hello, I am an old simple note user and I have a problem with auth on my mac.
I use simple note on mac os catalina and then I downgrade my computer to mojave and can't auth.

**Comment by PhotolocaDeveloper** [comment]
After I input my email and password (they are right because i use it in chorme) i have a message we have a promlem, try later

**Comment by jleandroperez** [comment]
Should be fixed now. Please feel free to reopen if needed,

Thanks for reaching out!!
