### ISSUE TITLE
Right Click "Search with Google" does not open default browser

### ISSUE THREAD

**Issue by rezzap** [Automattic/simplenote-macos#413]
### Expected
Right clicking on highlighted text and selecting search with Google should open default browser, e.g. Chrome. 

### Observed
When you select Search with Google, Safari opens by default. 

### Reproduced
Steps to reproduce the behavior.  
> 1. Go to MacOS app and open any note.
> 2. Highlight Text and right click to 'Search with Google'.
> 3. Safari will open a search for this and note your default browser (in this case Chrome).

![Screen Recording 2019-12-03 at 02 26 pm](https://user-images.githubusercontent.com/10325627/70059630-08ec1e80-15d9-11ea-8747-ef979b95ec3b.gif)

Macbook Pro 15 (2017)|macOS 10.15.1|MacOS Simplenote app 1.8

I did not replicate this in the Electron app on the same device. 

Reported in 2531740-zen

**Comment by jleandroperez** [comment]
Closing this one since it's an SDK issue. It's been reported to Apple, but i'm afraid we cannot really patch this one on our end.

Ref.: [Here](http://www.openradar.appspot.com/34216473) and [here](http://www.openradar.me/21687971).

Thank you!!
