### ISSUE TITLE
Multi-byte unicode characters disappearing from the Editor

### ISSUE THREAD

**Issue by mahangu** [Automattic/simplenote-macos#416]
### Expected
Unicode multi-byte characters should display just like normal characters in the Editor.
You should be able to type them out and delete them and see the changes immediately.

### Observed
1) When typing multi-byte characters in some languages, the characters immediately disappear from the Note Editor when you hit space. 

<img width="772" alt="Screen Shot 2019-12-10 at 9 29 20 AM" src="https://user-images.githubusercontent.com/10125810/70494205-55b48580-1b02-11ea-832d-bcf62f6d5818.png">

<img width="774" alt="Screen Shot 2019-12-10 at 9 31 10 AM" src="https://user-images.githubusercontent.com/10125810/70494198-5220fe80-1b02-11ea-9d74-268034fe111c.png">

However, the characters still display in the note preview in the Note List, and will show up in the Note Editor if you first click through to another note and come back to the note with the multi-byte characters.

<img width="761" alt="Screen Shot 2019-12-10 at 9 40 38 AM" src="https://user-images.githubusercontent.com/10125810/70494385-0a4ea700-1b03-11ea-8799-8fd3aa11fee4.png">

2) Next, if you try and delete one character from the note in the Note Editor, the whole line is deleted, though the character does get deleted in the note preview in the Note List.

<img width="772" alt="Screen Shot 2019-12-10 at 9 41 44 AM" src="https://user-images.githubusercontent.com/10125810/70494486-5ef22200-1b03-11ea-92c1-6c568b6ff3a5.png">

Once again, clicking on another note and coming back to the note with the multi-byte characters makes it display correctly.

This second issue was reported to us by a user in 2547593-zen.

### Reproduce
1. On your Mac, under Settings > Keyboard > Input Sources, click the `+` button to add any multi-byte input source (I tested with Sinhala / Japanese)
2. In Simplenote, go to any note and start typing with that multi-byte Input Source

Tested on macOS 10.14.6 / Simplenote 1.8

**Comment by Robertght** [comment]
Found another case in #2555487-zen

**Comment by sarahfg** [comment]
Again at #2569483-zen

**Comment by msilbers** [comment]
Reported in #2566652-zen on Mac OS Mojave versions10.14.6
#2566909-zen for macOS High Sierra (and iOS)
#2567030-zen

**Comment by msilbers** [comment]
reported in #2572746-zen for Korean on MacOS Mojave

**Comment by rezzap** [comment]
Again in 2574502-zen for Korean after updating to 1.8.1.

- MacBook Air
- macOS High Sierra 10.13.6
- Simplenote 1.8.1 on macOS

**Comment by msilbers** [comment]
reported in #2578500-zen

Unable to type in Japanese in their notes

**Comment by jleandroperez** [comment]
Hi there ＠mahangu！would it be possible to verify if this is still an issue in the latest update? (1.8.1).

Having trouble over here replicating this, it's highly likely it was _just_ fixed.

Thanks in advance!!

**Comment by sarahfg** [comment]
We've got a user who just reported this same issue using 1.8.1 #2580097-zen

**Comment by hichenming** [comment]
Same issue here with macOS 1.8.1，Chinese

**Comment by msilbers** [comment]
also reported in #25727460-zen as still affecting Simplenote 1.8.1, for Korean

**Comment by mahangu** [comment]
@jleandroperez Sorry for the late reply! I am still able to replicate this on 1.8.1.

**Comment by jleandroperez** [comment]
Thank you @mahangu !! Should be fixed in 1.9, soon 🔥
