### ISSUE TITLE
Can't rename or delete tag immediately after creating it

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/simplenote-macos#417]
### Expected

I expect to always be able to rename or delete a tag.

### Observed

Immediately after adding a new tag to a note, I can't rename or delete it.

Sometimes this also affects other tags (I can't rename or delete any tags) and sometimes it only affects the new tag. Sometimes the effect goes away immediately after doing something else in the app (like editing the note) and sometimes it lasts until I relaunch the app.

h/t @Robertght for reporting this during beta testing

### Reproduced

1. Open a note in the app.
2. Add a new tag to the note.
3. In the tags list, right click on the new tag.
4. Try to select "Rename tag" or "Delete tag" and notice that nothing happens.

![simplenote-macos-tags2](https://user-images.githubusercontent.com/8658164/70528109-54f11300-1b45-11ea-833f-e26f6724f88f.gif)

Make|Model|macOS Version|App Version
-|-|-|-
Macbook|Pro (2017)|macOS 10.15.1|1.9

**Comment by jleandroperez** [comment]
Closing as cannot repro anymore. Simplenote macOS 2.6 / Big Sur 11.1.

Thank you Rachel!!
