### ISSUE TITLE
Simplenote quits at unexpectedly at startup

### ISSUE THREAD

**Issue by manfrat** [Automattic/simplenote-macos#418]
After the update to version 1.8, when I open Simplenote, it quits unexpectedly.

Please, be as descriptive as possible.  Issues lacking detail, or for any other reason than to report a bug, may be closed without action.

### Expected
I open Simplenote, expecting to use it.

### Observed
After the update to version 1.8, when I open Simplenote, it quits unexpectedly.

### Reproduced
It happens everytime I try to open it, so I cannot use Simplenote anymore.

***(Optional)*** If applicable, add screenshots, animations, or videos to help illustrate your problem.

***(Optional)*** If you reproduced the bug on a specific system, please replace SYSTEM_MAKE, SYSTEM_MODEL, MACOS_VERSION, and APP_VERSION below with the details for that system.  If you reproduced the bug on multiple systems, please add a row for each system.

System: Macbook Pro, MacOS Catalina

**Comment by bummytime** [comment]
Thanks for the report @manfrat. We are aware of this issue and will have a patch very shortly. 

Closing in favor of #419
