### ISSUE TITLE
Crashing about 10 seconds after modifying a specific note

### ISSUE THREAD

**Issue by EagTG** [Automattic/simplenote-macos#419]
Please, be as descriptive as possible.  Issues lacking detail, or for any other reason than to report a bug, may be closed without action.

### Expected
That the app would continue to function as a specific note was modified

### Observed
Within seconds of any modification to a specific note, the app would close and MacOS would show the crash reporting dialog box.

### Reproduced
***(Required)*** If you cannot reproduce this bug consistently, please elaborate.  List the steps to reproduce the behavior.  For example:
> 1. Go to... the specific note that was causing the crash
> 2. Click on... anywhere in the note and make a modification
> 3. See error... within seconds the MacOS crash dialog would show

An effective work-around appears to have been to copy the contents of the note to a plain-text editor, delete the errant (or "corrupt") note, recreate the note, and all seems well now. I had initially thought that this was a bug introduced with the combination of Catalina and the new Simplenote 1.8 that I recently upgraded to, however that does not (yet) appear to be the case. Just an odd-timing coincidence. That said, this may be behavior introduced with the 1.8 version (as I had not seen it previously) but I have no evidence to back that up beyond circumstantial.

***(Optional)*** If applicable, add screenshots, animations, or videos to help illustrate your problem.

I have uploaded a collection of the crash reports that were captured by the MacOS console.

***(Optional)*** If you reproduced the bug on a specific system, please replace SYSTEM_MAKE, SYSTEM_MODEL, MACOS_VERSION, and APP_VERSION below with the details for that system.  If you reproduced the bug on multiple systems, please add a row for each system.

Make|Model|macOS Version|App Version
Apple|Mac Mini|10.15.1|1.8
SYSTEM_MAKE|SYSTEM_MODEL|MACOS_VERSION|APP_VERSION

[SimplenoteConsoleCrashReports.zip](https://github.com/Automattic/simplenote-macos/files/3945995/SimplenoteConsoleCrashReports.zip)

**Comment by dmsnell** [comment]
Thanks for the awesome bug report @EagTG!

@jleandroperez this looks like the same diff-match-patch Unicode encoding issue. In the crash report I'm seeing `Range or index out of bounds` and the behavior seems coincident.

**Comment by EagTG** [comment]
Absolutely, I can't put into words how much I love SimpleNote. Been using it for years. :-D

**Comment by jleandroperez** [comment]
@EagTG **Thank you** for sharing this, we're working to get this fixed ASAP!

😃

**Comment by jleandroperez** [comment]
Closing this one, since it's been fixed via #421 (AppStore version 1.8.1)

Please feel free to reopen if needed. Thanks everyone!!
