### ISSUE TITLE
Opening Sidebar changes note being viewed

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#42]
<a href="https://github.com/sandymcfadden"><img src="https://avatars.githubusercontent.com/u/1326294?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sandymcfadden](https://github.com/sandymcfadden)**
_Friday Jun 19, 2015 at 10:23 GMT_

---

A user reported in the Mac App when you toggle the sidebar from hidden to visible it changes the current note you are viewing to always be the first note in the list.

They think, and I agree, that it should keep the current note visible instead of changing.

**Comment by bummytime** [comment]
**Update 5/14/2019 →** Tested in Simplenote 1.4.2 on macOS 10.14.4 (Mojave) and this issue no longer occurs.
