### ISSUE TITLE
Checkboxes on current note deleted when theme is changed

### ISSUE THREAD

**Issue by potahto** [Automattic/simplenote-macos#422]
Changing from Light to Dark or Dark to Light deletes checkboxes.

To reproduce: 
1. Create a note with a checkbox.
2. Switch themes.

Expected Result: Note content is preserved.
Actual Result: Checkboxes (widgets/characters) are deleted.

Tested on Simplenote 1.8, macOS 10.14.6 Mojave.

Demonstration: https://streamable.com/qxp4j

**Comment by msilbers** [comment]
closing for duplicate of #321
