### ISSUE TITLE
Feature Request: Set text font for editing

### ISSUE THREAD

**Issue by ecnelises** [Automattic/simplenote-macos#427]
### What
Can we add an option to use fonts other than system default for text editing? To be clear, I DO NOT mean to introduce rich-text instead of plain text. At least, can we add an option to use monospace font for editors?

### Why
Markdown is fine and things work well. But when we type code or someone just doesn't like the default font, a font menu for changing how the text is displayed would be nice. Of course it's important to keep Simplenote simple, but that won't be a burden of feature, I think.

### How
Changing `View - Note editor - Font size` to a menu item about opening a font picker, in which we can set font of editor.

I want to see opinions about this feature from folks. If that's good, I can try adding this. Thanks!

**Comment by jleandroperez** [comment]
We keep track of feature requests in an internal system. Adding +1 vote to custom fonts.

Thank you for reaching out!!

**Comment by rghedin** [comment]
Any news regarding custom fonts?
