### ISSUE TITLE
macOS built-in shortcuts don't work anymore

### ISSUE THREAD

**Issue by Robertght** [Automattic/simplenote-macos#429]
When we try to use the macOS built-in shortcut system with the last version of Simplnote(1.8.1), it doesn't seem to work anymore, but it does work with a previous build, for example 1.7.

### Reproduced

Steps:
1. Create or check to see which shortcuts you have in Keyboard->Text: 
<img width="639" alt="Keyboard 2019-12-24 09-03-15" src="https://user-images.githubusercontent.com/6737345/71399453-53871680-262c-11ea-95f6-a4def2dd8fdf.png">
2. Try to add it through the last version of Simplenote.
3. They don't offer any suggestions as in the 1.7 build of Simplenote.

### Expected
To be able to use the keyboard shortcuts 

### Observed
The shortcut suggestion didn't work as in 1.7.

#2580072-zen

Make|Model|macOS Version|App Version
-|-|-|-
Macbook|Pro|macOS 10.15.2|Simplenote 1.8.1

**Comment by jleandroperez** [comment]
Closing as cannot repro. Simplenote macOS 2.2 / Catalina 10.15.6

Please feel free to reopen if needed. Thank you!!

<img width="300" src="https://user-images.githubusercontent.com/1195260/92934183-950b5c00-f41d-11ea-969d-31bfbd62cf7c.png">
