### ISSUE TITLE
Note focus when tabbing between applications on Mac

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#43]
<a href="https://github.com/rachelsquirrel"><img src="https://avatars.githubusercontent.com/u/7946521?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rachelsquirrel](https://github.com/rachelsquirrel)**
_Tuesday Jun 30, 2015 at 13:08 GMT_

---

A user reports that when they cmd+h out of Simplenote and then switch back using cmd+tab, it jumps to a different note from the one they were viewing previously. This has just started happening since the last update. I can reproduce. 

The user created a movie here:
https://www.dropbox.com/s/qfx0hjt6q0r0eid/Simplenote.mov?dl=0

Ticket:
t63188

**Comment by bummytime** [comment]
Tested the various things mentioned above ☝️ in Simplenote 1.4.2 on macOS 10.14.4 (Mojave):

> Focus on a specific tag is also lost when hiding and unhiding the app:

> This also happens when you follow these steps:
    Select the second note
    Hide the sidebar
    Unhide the sidebar

> Same thing happens when minimizing and expanding the App:

> they cmd+h out of Simplenote and then switch back using cmd+tab, it jumps to a different note from the one they were viewing previously.

and in every situation the the current note focus is maintained. Closing for now.
