### ISSUE TITLE
Can create a tag "trash"

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#44]
<a href="https://github.com/rachelsquirrel"><img src="https://avatars.githubusercontent.com/u/7946521?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rachelsquirrel](https://github.com/rachelsquirrel)**
_Tuesday Jul 07, 2015 at 10:25 GMT_

---

Open the Mac app and create a new note with the tag "trash". Then click the Tags link at the top left and in the list will appear "trash" as well as the real "Trash". If you click on either of these they both display the contents of the real "Trash" rather than the note with the tag "trash". There's no way to view the list of notes with tag trash unless you view "All notes".

Not sure if this is a bug or not but reporting it anyway.

case/63238

**Comment by bummytime** [comment]
**Update 5/14/2019 →** Tested in Simplenote 1.4.2 on macOS 10.14.4 (Mojave) and this issue no longer occurs.
