### ISSUE TITLE
Fixed sentence is deleted unexpectedly when edit other part of line.

### ISSUE THREAD

**Issue by minolasoft** [Automattic/simplenote-macos#449]
**Bug**

Fixed sentence is deleted unexpectedly when edit other part of line.

- Delete another part and all of double-byte strings are deleted unexpectedly.

- Fixed double-byte character through FEP and fixed characters deleted soon.

**Expected**

Fixed sentence must not deleted when other part of line is edited.

**Observe**

The bug is not occurred in the previous version by my memory.

[Screen Recording of bug occurring](https://youtu.be/YobP5DkoMLY)

**Comment by jleandroperez** [comment]
Closed via #430. Please feel free of reopening if needed.

Thanks everyone!
