### ISSUE TITLE
Hide notes list

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#45]
<a href="https://github.com/rachelsquirrel"><img src="https://avatars.githubusercontent.com/u/7946521?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rachelsquirrel](https://github.com/rachelsquirrel)**
_Tuesday Jul 14, 2015 at 07:54 GMT_

---

It would be great to be able to hide the list of notes on the left in the Mac app for distraction-free writing

**Comment by Robertght** [comment]
#1098726-zen

**Comment by bummytime** [comment]
Focus mode now exists in app for this purpose. Closing this issue.
