### ISSUE TITLE
URL in 'title' breaks the note, and all following notes, until relaunch

### ISSUE THREAD

**Issue by folletto** [Automattic/simplenote-macos#451]
When a URL is typed in the title, any note from that moment on gets hyperlinked.

1. Create a new note, with a URL in title
![Artboard 1](https://user-images.githubusercontent.com/4389/73356551-88713380-4292-11ea-9265-39dc6c919284.jpg)

2. Switch to any other note, you'll notice all the content gets hyperlinked
![Artboard 2](https://user-images.githubusercontent.com/4389/73356563-8e671480-4292-11ea-9bbf-dc2b3d3732ee.jpg)

3. Switch back to the original note, everything is hyperlinked from now on
![Artboard 3](https://user-images.githubusercontent.com/4389/73356590-9e7ef400-4292-11ea-8999-77eeea508f7b.jpg)

Simplenote: v1.9
macOS: 10.15.2 (19C57)

**Comment by jleandroperez** [comment]
Thank you Erin!! we'll get this one ASAP!

**Comment by bummytime** [comment]
Closing in favor of #448
