### ISSUE TITLE
Spring Cleaning: Phase I

### ISSUE THREAD

**Issue by jleandroperez** [Automattic/simplenote-macos#458]
### 🔨 Debt 🔨
- [x] Drop **INAppStoreWindow** since it's not really needed anymore
- [x] Drop VSThemeManager
- [x] Drop dead assets
- [x] Decouple VersionsViewController
- [x] Decouple ShareViewController
- [x] Decouple PublishViewController
- [x] Implement MarkdownViewController
- [x] Drop AppDelegate's IBOutlets

### 🎶 New UX 🎶   
- [x] Display NSWindow's titleBar
- [x] Refresh Tags List
- [x] Refresh App Icons
- [x] Re-Engineer ToolbarView: Review Encapsulation + Ownership
- [x] Re-Engineer SearchBar: Review Encapsulation + Ownership
- [x] Implement ColorStudio Tooling
- [x] Implement New Color Scheme
- [x] Implement the new (Vectorial) Assets
- [x] Implement our New Blue!
- [x] Implement SplitViewController
- [x] Implement New Notes List
- [x] Implement Extended Content in the Notes List
- [x] Refresh UI Icons: 24x24 >> 20x20
- [x] Restore Window TitleBar
- [x] Implement Dividers: Sidebar / Toolbar
- [x] Refresh Editor
- [x] Implement TagsEditor
- [x] Implement TagsEditor Scrolling Support
- [x] Implement Untagged Notes Support #120
- [x] Implement ModifiedUI
- [x] Refresh Popovers Style
- [x] Refresh ToolbarView
- [x] Review RTL Support

### 📸  Screenshots 📷 
<img width="300" src="https://user-images.githubusercontent.com/1195260/75882567-30cd6700-5e00-11ea-864f-5bf61aa32aab.png">
<img width="300" src="https://user-images.githubusercontent.com/1195260/75882608-45116400-5e00-11ea-9623-6a3a0695bf13.png">
<img width="300" src="https://user-images.githubusercontent.com/1195260/75882664-5ce8e800-5e00-11ea-9dbc-ad2b4b782540.png">

**Comment by codebykat** [comment]
User in 2995663-zen thinks the missing sidebar toggle icon is a bug and requests its return.

**Comment by jleandroperez** [comment]
Officially closing **Spring Cleaning Phase 1**... 

Thank you @aerych @guarani @danielebogo @etoledom @emilylaguna for the million + 1 reviews !!!!!!

🔥🔥🔥🔥🔥
