### ISSUE TITLE
Latex Support

### ISSUE THREAD

**Issue by adimyth** [Automattic/simplenote-macos#461]
Currently Simplenote for macos doesn't support latex. Some other note taking apps support latex. 
### What
**Support For Latex**
I have been using Simplenote for a couple of years, but the lack of latex rendering support is quite frustrating. Simplenote should be able to add mathematical equations in the markdown & render them properly. Majority of the websites provide option to copy these equations either as _tex commands_ or _mathml code_, but currently pasting them in the app has no effect, which is a very bad experience.

### Why
I believe this is a general requirement for anyone willing to add mathematical notations in their notes. Many papers as well as blogs have equations in latex form. Currently, the only way to add those equations to the notes is to take a screenshot of them, upload it somewhere & add it's link, which I feel is very crude.

I believe the feature request was descriptive enough. If not, please continue this discussion.

**Comment by jleandroperez** [comment]
Moving this one to an (internal) system, in which we do track feature requests.

Thank you for reaching out @adimyth !!
