### ISSUE TITLE
Add sharing icon

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#47]
<a href="https://github.com/rachelsquirrel"><img src="https://avatars.githubusercontent.com/u/7946521?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rachelsquirrel](https://github.com/rachelsquirrel)**
_Tuesday Aug 25, 2015 at 08:37 GMT_

---

This is a user request which I thought I'd add here. They'd like to be able to see the collaboration icons in the Mac app similar to how it works in the web app. 

ticketid=2316397

**Comment by bummytime** [comment]
Closing in favor of #77
