### ISSUE TITLE
Checklists: Note list preview doesn't always show 2 lines of checklists

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/simplenote-macos#482]
### Expected

When View > Notes List > Note Display is set to Comfy, I expect the notes list to show my note title along with 2 lines of the note in the preview.

### Observed

When the note begins with a checklist, the note preview only shows 2 lines if the checklist has exactly 2 items and no other content.

If the checklist contains more than 2 items, or other text is entered after the checklist, only the first item in the checklist appears in the note list preview.

### Reproduced

1. Go to **View > Notes List > Note Display** and select `Comfy`.
1. Create a new note.
2. Add a note title like `Checklist`.
3. Type `OPTION + CMD + C` or select **Format > Insert Checklist** to start a checklist, and enter some text for the first checklist item.
4. Press Enter and enter some text for the second checklist item. Notice that both checklist items appear in the note list preview.
5. Press Enter again (optionally add some text for the third checklist item) and notice the note list preview now only shows the first checklist item.
6. Delete the third checklist item and notice the note list preview now shows the two checklist items again.
7. Enter other text below the checklist and notice the note list preview now only shows the first checklist item.

![checklist-notelistpreview](https://user-images.githubusercontent.com/8658164/78592601-412c9380-783d-11ea-817f-d0eb11bfa128.gif)

Make|Model|macOS Version|App Version
-|-|-|-
Apple|Macbook Pro|macOS 10.15.4|1.10.0 beta

**Comment by jleandroperez** [comment]
Closing this one since it's not relevant anymore.

As of Simplenote 1.11 we've updated the logic that extracts the Note List text.

Ref. #542
