### ISSUE TITLE
Note list divider still visible after entering focus mode

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/simplenote-macos#485]
### Expected

I expect that when focus mode is enabled, the editor will take up the full width of the app window with no vertical dividers visible.

### Observed

With the sidebar toggled off (note list is visible but tag list not visible), entering focus mode doesn't remove the vertical divider that usually divides the note list from the editor.

### Reproduced

1. Toggle the sidebar so that everything (tags, note list, editor) is visible.
2. Enable focus mode and notice that it looks as expected.
3. Disable focus mode and toggle the sidebar off so only the note list and editor are visible.
4. Enable focus mode and notice that the vertical divider from the note list is still visible.

![Screenshot 2020-04-07 15 39 22](https://user-images.githubusercontent.com/8658164/78682523-ffa3f300-78e5-11ea-883d-c3d4b9f5c68a.png)

![macos_focusmode](https://user-images.githubusercontent.com/8658164/78682533-03377a00-78e6-11ea-95a9-de68b9266584.gif)

Make|Model|macOS Version|App Version
-|-|-|-
Apple|Macbook Pro|10.15.4|1.10.0 beta

## Reports

 - #2986452-zen

**Comment by jleandroperez** [comment]
Closed via #532, shipping soon in Simplenote 1.11.

Thank you Rachel!!
