### ISSUE TITLE
Sync: Removing a tag from a note in macOS app doesn't remove it in other clients

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/simplenote-macos#487]
### Expected

I expect that when I remove a tag from a note in the macOS app, that change will be synced everywhere.

### Observed

When I remove a tag from a note in the macOS app, the tag remains on the note in other clients.

### Reproduced

1. Create a note.
2. Add a tag to the note.
3. In another client (e.g. web, iOS app) confirm the note is synced with the tag.
4. In the macOS app, remove the tag from the note.
5. In the other client, notice that the tag remains on the note.

Make|Model|macOS Version|App Version
-|-|-|-
Apple|Macbook Pro|10.15.4|1.10.0 beta

**Comment by jleandroperez** [comment]
Closing as cannot repro anymore / Simplenote macOS 2.6.
The entire Tags Editor has been entirely rewritten a couple releases ago.

Thank you Rachel!!
