### ISSUE TITLE
Markdown: Preview mode doesn't disappear/reappear when receiving remote changes to markdown setting

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/simplenote-macos#488]
### Expected

I expect that preview mode will disappear/reappear when receiving remote changes to the markdown setting (i.e. when I change that setting in another client or device).

### Observed

Preview mode doesn't doesn't disappear/reappear when receiving remote changes to the markdown setting. The setting itself syncs but preview mode stays the same as before.

### Reproduced

1. Create a new note.
2. Enable markdown on the note from within macOS app; notice that preview mode appears immediately on the note.
3. Disable markdown on the note from within macOS app; notice that preview mode disappears immediately on the note.
4. In another client (e.g. web), enable markdown on the note. In macOS, notice that preview mode doesn't appear immediately but if you check the markdown setting it is enabled.
5. In another client (e.g. web), disable markdown on the note. In macOS, notice that preview mode doesn't disappear immediately but if you check the markdown setting it is disabled.

Make|Model|macOS Version|App Version
-|-|-|-
Apple|Macbook Pro|10.15.4|1.10.0 beta

**Comment by jleandroperez** [comment]
Closing in favor of #806 (since the newest one has a demo clip!)

Thank you Rachel!!
