### ISSUE TITLE
Animate the dotted menu icon

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#49]
<a href="https://github.com/roundhill"><img src="https://avatars.githubusercontent.com/u/789137?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [roundhill](https://github.com/roundhill)**
_Friday Sep 11, 2015 at 23:40 GMT_

---

It'd be neat if the menu button with the `...` could animate like on wp.com:

https://cloudup.com/cg6kkQX_w_T

**Comment by bummytime** [comment]
I don't see the dotted menu icon anymore...perhaps I am missing something? Please reopen if I have a screw loose 🔩  😄
