### ISSUE TITLE
Tag autocomplete should show suggestion for new tag

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#5]
<a href="https://github.com/mikejohnstn"><img src="https://avatars.githubusercontent.com/u/515035?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mikejohnstn](https://github.com/mikejohnstn)**
_Monday Jun 10, 2013 at 20:41 GMT_

---

If you start typing a tag name that doesn't exist, there should be an autosuggest entry like:
Create new tag named 'NewTag'

**Comment by jleandroperez** [comment]
Closing as `wontfix` since the tags editor has been reimplementedin 1.11.1.

Thank you!
