### ISSUE TITLE
Tags: Button for tag list/trash is absent

### ISSUE THREAD

**Issue by msilbers** [Automattic/simplenote-macos#518]
### Expected
The button to open the tag list and trash is now absent. This means you need to use a keyboard command or go to the file menu area to open the tag list or trash.

### Observed

It should be to the left of the search bar.

<img width="273" alt="Screen Shot 2020-04-25 at 1 06 33 PM" src="https://user-images.githubusercontent.com/31680407/80285836-a31e4180-86f5-11ea-9916-5dbb4659b4e6.png">

Make Model|macOS Version|App Version
-|-|-
MacBook Pro |10.14.6|Simplenote 1.10.0

**Comment by jleandroperez** [comment]
Closing this one since this change is actually part of the Spring Cleaning redesign.

Ref. #458.

Thank you Melissa!!

**Comment by codebykat** [comment]
User thought this was a bug and wants the icon back in 2947857-zen

**Comment by codebykat** [comment]
User in 2995663-zen also thought this was a bug and requests the icon back
