### ISSUE TITLE
Inconsistency: Deleting the last note in a Tag

### ISSUE THREAD

**Issue by jleandroperez** [Automattic/simplenote-macos#522]
### Steps:
1. Add a new Note
2. Assign a new tag to the new note (so that it's the only one in there)
3. Click over the new tag
4. Delete the note

As a result, the Note List will be cleared out, but the deleted note will remain onscreen.

![delete-glitch](https://user-images.githubusercontent.com/1435271/80554314-5e630680-8992-11ea-9bdf-4fb4efde5ecd.gif)

**Comment by mokagio** [comment]
@jleandroperez #512 references this bug and there's some work around it, too. 

Should this be closed, or should I bump the milestone? Thanks 🙌

**Comment by jleandroperez** [comment]
Bumping the milestone to 1.12, thank you @mokagio !!

**Comment by jleandroperez** [comment]
Closing as cannot reproduce. Simplenote 2.2.

Lots of code were recently changed, sooo this one is gone 🔥 

Thanks everyone!!
