### ISSUE TITLE
Unable to resize window smaller in El Capitan

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#53]
<a href="https://github.com/rachelsquirrel"><img src="https://avatars.githubusercontent.com/u/7946521?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rachelsquirrel](https://github.com/rachelsquirrel)**
_Tuesday Oct 06, 2015 at 06:21 GMT_

---

We've had a couple of reports on Twitter from users who can't resize the Simplenote window in El Capitan. They can make it larger but not smaller. I haven't installed El Capitan so haven't had the chance to repro yet.

**Comment by jleandroperez** [comment]
Closing as cannot repro.

Simplenote 1.10 / macOS Catalina. Please reopen if needed!!
