### ISSUE TITLE
App Store screenshots need to be updated

### ISSUE THREAD

**Issue by codebykat** [Automattic/simplenote-macos#530]
The screenshots in the App Store still show the sidebar button for toggling the tag list:

<img width="737" alt="Screen Shot 2020-05-06 at 4 16 15 PM" src="https://user-images.githubusercontent.com/52152/81237624-f4abb380-8fb4-11ea-958d-7606efb6bc63.png">

### Expected
The screenshots in the App Store should match what the app actually looks like.

### Observed
The screenshots are outdated. This is not helping user confusion about whether it's a bug (see #518)

**Comment by jleandroperez** [comment]
Closing this one since all of the screenshots have been updated.

Thank you Kat!!
