### ISSUE TITLE
Note order is not refreshed

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#54]
<a href="https://github.com/rachelsquirrel"><img src="https://avatars.githubusercontent.com/u/7946521?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rachelsquirrel](https://github.com/rachelsquirrel)**
_Tuesday Oct 06, 2015 at 11:51 GMT_

---

Steps:
1. Change the sort order in the Mac app to "Date Updated".
2. Edit a note down the list. 

The order of notes remains the same until exiting from the app and opening it again.

**Comment by jtoy** [comment]
this bug seems to be popping up for me as well, and this ticket is already here several times: https://github.com/Automattic/simplenote-macos/issues/102

**Comment by bummytime** [comment]
Closing in favor of #102
