### ISSUE TITLE
Making search mouse/trackpad-free

### ISSUE THREAD

**Issue by pmastela** [Automattic/simplenote-macos#540]
### What
Adding the ability to use search with no trackpad use.

### Why
It's faster. Currently, if I search for a word that occurs in several notes then I have to resort to the trackpad in order to click on the correct note. Being able to access the desired note without leaving the keyboard would save time for Simplenote users.

### How
Ideally, I hit CMD+L to access the search field, type in my keywords, then:
a. if first result is the one I want, simply hitting Return will drop me straight into the note
b. if desired note is not the first result, but one of the other results, then I can navigate between notes by pressing the up or down arrow (hitting Return opens it) OR the first ten 10 results are immediately accessible via CMD+<resultIndex>

**Comment by jleandroperez** [comment]
Hi there @pmastela ,

There's a shortcut to access the search field: Option + CMD + F.

As per the Search Results navigation suggestion (with keyboard), I've added that one to our Simplenote Ideas list.

Closing this issue for now, thank you for reaching out!
