### ISSUE TITLE
Unable to scroll to the bottom of long notes

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#55]
<a href="https://github.com/rachelsquirrel"><img src="https://avatars.githubusercontent.com/u/7946521?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rachelsquirrel](https://github.com/rachelsquirrel)**
_Tuesday Oct 06, 2015 at 15:55 GMT_

---

I can't reproduce this but a user reports that they can't scroll to the bottom of very long notes. Here's what they say:

"I open the note, scroll down to the last line, stop scrolling and the last few lines disappear(they go down) and I am only able to see the previous lines of text. I checked it one more time and found out that it only happens when there is white space after the characters in the end of the note. When I delete the spaces it works perfectly."

They're using Mac OS 10.9.5. Maybe that has something to do with it? I can scroll to the bottom of notes containing more than 16,000 words without any trouble.

ticketid=2372616

**Comment by gubrist** [comment]
I am facing the same problem on my Android App 1.5.1 (on my Mobile and Tablet) and 
a workd-around is adding lots of carriage returns to the end of the note.

Especially with the Android App, the keypad covers the text at the bottom instead of scrolling the remaining bottom text upwards.

**Comment by bummytime** [comment]
Closing in favor of #93
