### ISSUE TITLE
Deleting multiple tags only works if you scroll the mouse between deletes

### ISSUE THREAD

**Issue by adamshand** [Automattic/simplenote-macos#554]
### Expected

I should be able to "right click - delete" one tag and then immediately delete another tag which is visible in the tag list.

### Observed

* I can delete one tag.  
* If I try and delete another tag, without scrolling the tag list, nothing will happen when I select delete
* If I scroll the tag list then I can delete a tag.

Note that this only true for deleting by right clicking with the mouse.  I can delete tags as expected with the delete key.

### Reproduced

Easiest to see in [this screencast](https://www.dropbox.com/s/1rb5i22xfcrqqt2/simplenote-tags-bug.mov?dl=0).

This is macOS 10.15.5 and Simplenote 1.10.0 (installed by Homebrew).

**Comment by jleandroperez** [comment]
Closing as cannot repro / Simplenote 1.12 / macOS 1.12
The entire Tags List was recently rebuilt (almost from scratch) 😄 

Thank you for helping us improve Simplenote!
