### ISSUE TITLE
Nested tags

### ISSUE THREAD

**Issue by adamshand** [Automattic/simplenote-macos#555]
### What

The main feature I miss in Simplenote is the ability to have nested tags. My preferred implementation is using "/" characters in tags to indicate hierarchy.  

So the tag "Job/ClientFoo" is visually represented as a folder "Job" with a sub-folder of "ClientFoo".

The big advantage of this which I see is that it doesn't require changes to the backend, only in how tags are displayed in the "tag list".

### Why

I use tags to indicate different types of information. For example I might a set of status tags "Status/Idea", "Status/Working", and "Status/Finished". I might also have tags for different jobs, eg "Job/ClientA", "Job/ClientB".

This allows me to track things through a workflow while still keeping them organised.

### How

Google Mail labels and Bear.app's tags are probably the best examples of a system like this.

**Comment by jleandroperez** [comment]
For the time being, our approach to tackle complexity is by enhancing search (already out for other platforms, **soon to be implemented in the Mac**). However, this decision may be reverted in the future.

Thank you for reaching out @adamshand, I'll pass along the feedback to the team!

**Comment by jleandroperez** [comment]
P.s.: I forgot to mention, we do track ideas / suggestions in an internal system. Adding a vote on your behalf. 

Again, thanks for reaching out!!

**Comment by adamshand** [comment]
Thanks for the quick response, but for the record search doesn't actually solve the problem.

Search is a great way of find things but it doesn't help organise things.  

For a heavy user (for example I have a couple thousand notes which are are carefully organised and have been collected over about 20 years) a non-hierarchical tag list becomes extremely unwieldy to the point of uselessness.

Imagine you have a couple hundred tags.  You can't remember what they all are so every time you go to tag something you're scrolling up and down trying to find the tag.

Thanks for listening.

**Comment by jleandroperez** [comment]
The mindset behind improving search (as an initial step, at least!) is that: 

- Given a couple hundred tags, do you always remember the exact sequence of tags that would lead you to a specific document?
- How much time / effort do you invest in maintaining the Tags tree?

The idea is to (try to) keep things as simple as possible. Just typing a keyword should quickly locate the target document, and you'd avoid maintaining a tree structure, by hand.

That's in the lines of how Google's Gmail works. But yes, Gmail also offers nested tags 😄 

We may revisit this down the line, though. You're very right in one important point, which is, massive (single dimensional) tag lists are a problem.

Thank you for your time Adam!
