### ISSUE TITLE
El Capitan - line height issue with Chinese characters

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#56]
<a href="https://github.com/rachelsquirrel"><img src="https://avatars.githubusercontent.com/u/7946521?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rachelsquirrel](https://github.com/rachelsquirrel)**
_Wednesday Oct 07, 2015 at 09:31 GMT_

---

The top of the fourth line of a note with Chinese characters appears in the note list on the left with Mac OS 10.11.

![cqsd38ausaa7wih](https://cloud.githubusercontent.com/assets/7946521/10333842/67f6df30-6cde-11e5-9fbb-f4138c26784e.png)

Reported on Twitter:
https://twitter.com/quxiaowei/status/651647419667472384

**Comment by bummytime** [comment]
Closing in favor of #195
