### ISSUE TITLE
Checklist in Dark Mode not visible

### ISSUE THREAD

**Issue by fstath** [Automattic/simplenote-macos#564]
On the macOS version, the checklist's checkboxes are barely visible when Dark Mode is enabled.

Screenshot:
![Screenshot 2019-08-23 at 17 44 08](https://user-images.githubusercontent.com/32326882/63601200-a775e600-c5cd-11e9-8109-b88a6cf01be9.png)

Reported on Twitter: https://twitter.com/DesignICU/status/1164900244896833538

**Comment by jleandroperez** [comment]
This one was fixed via #434 in Simplenote 1.9.
Closing as cannot repro anymore. 

Thank you Kat!!

**Comment by codebykat** [comment]
Oh @jleandroperez this is actually a theme bug though! In dark theme the checkboxes are so dark you can barely see them. I just repro'ed in 1.10.0:

<img width="191" alt="Screen Shot 2020-06-19 at 11 18 32 AM" src="https://user-images.githubusercontent.com/52152/85168021-9eba6480-b21e-11ea-98b2-fe1240cba481.png">

**Comment by jleandroperez** [comment]
Thank you @codebykat !!!

Would it be possible to verify on the latest? I'm afraid it's looking good on my end.

- Tested with `Theme > Dark` and `Theme > System Appearance`
- macOS 10.15.

**Thank you!!!**


<img width="300" src="https://user-images.githubusercontent.com/1195260/89958519-62005d80-dc10-11ea-98cc-6355822135a9.png">

**Comment by codebykat** [comment]
Looks fixed in 2.0! Thanks @jleandroperez !

**Comment by jleandroperez** [comment]
Thank you Kat!!
