### ISSUE TITLE
Integrate tags with OSX tagging system

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#58]
<a href="https://github.com/rachelsquirrel"><img src="https://avatars.githubusercontent.com/u/7946521?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rachelsquirrel](https://github.com/rachelsquirrel)**
_Thursday Oct 22, 2015 at 09:40 GMT_

---

It would be good if Simplenote tags worked with OSX tags:
https://support.apple.com/en-nz/HT202754

**Comment by cupcakedream** [comment]
How do you imagine this working? I believe all the text docs are stored on the simplenote server

**Comment by bummytime** [comment]
This is not on our roadmap atm. Closing this issue for now.
