### ISSUE TITLE
Show Account Email Somewhere

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#59]
<a href="https://github.com/sandymcfadden"><img src="https://avatars.githubusercontent.com/u/1326294?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sandymcfadden](https://github.com/sandymcfadden)**
_Friday Oct 23, 2015 at 17:50 GMT_

---

Currently in the OSX app there doesn't appear to be anywhere that shows which account you are logged into. 

It would be awesome if there were some place we could see this. Maybe in the About menu or even change the Sign Out to say Sign out of <email>.

**Comment by bummytime** [comment]
Closing in favor of #64
