### ISSUE TITLE
Note metrics popover opens twice when double-clicking (i) icon

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/simplenote-macos#595]
### Expected
I expect that clicking on the (i) icon will open the note metrics popover.

### Observed
I noticed that if I double-click on the (i) icon I see the popover animate open twice.

### Reproduced

1. Create or open a note.
2. In the top right, click the (i) icon.
3. Notice that the note metrics popover opens.
4. Click to close the note metrics popover.
5. Double-click the (i) icon.
6. Notice that the note metrics popover seems to open twice (the opening animation appears twice).

GIF showing the steps above (opening the popover with a single click, and then with a double click):

![sn-macos-info-popover](https://user-images.githubusercontent.com/8658164/87431290-52283600-c5de-11ea-9da9-2ec6f3a5ed9a.gif)

Make|Model|macOS Version|App Version
-|-|-|-
Apple|Macbook Pro|10.15.5|1.12.0 beta

**Comment by jleandroperez** [comment]
Closed via #598. Thank you Rachel!!
