### ISSUE TITLE
Note metrics show -1 Words for new note

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/simplenote-macos#596]
### Expected
When I create a new note, I expect the note metrics to show the number of words as 0.

### Observed
The note metrics show the number of words as -1.

### Reproduced

1. Create a new note.
2. Without adding any content, click the (i) icon in the top right.
3. In the note metrics popover that opens, notice that Words is -1.

![Screenshot 2020-07-14 14 30 54](https://user-images.githubusercontent.com/8658164/87431710-edb9a680-c5de-11ea-8ed0-37d56180ef00.png)

Make|Model|macOS Version|App Version
-|-|-|-
Apple|Macbook Pro|10.15.5|1.12.0 beta

**Comment by rachelmcr** [comment]
The metrics look accurate when a single note is selected and it has content, but when multiple notes are selected it also looks like the word count is reduced by 1. I'm noting it here because it seems likely to be the same root issue.

Note 1 (2 words)|Note 2 (3 words)|Both notes (should be 5 words)
-|-|-
![Screenshot 2020-07-14 14 41 26](https://user-images.githubusercontent.com/8658164/87432650-33c33a00-c5e0-11ea-9ced-0b7c9c9b3f76.png)|![Screenshot 2020-07-14 14 41 30](https://user-images.githubusercontent.com/8658164/87432657-36259400-c5e0-11ea-89ae-0e35b1e5e2da.png)|![Screenshot 2020-07-14 14 41 36](https://user-images.githubusercontent.com/8658164/87432660-36be2a80-c5e0-11ea-8a55-8cd690d1ae49.png)

**Comment by jleandroperez** [comment]
Closed via #597. Thank you Rachel!!
