### ISSUE TITLE
Add ability to open notes in separate windows by double-clicking them

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#6]
<a href="https://github.com/mikejohnstn"><img src="https://avatars.githubusercontent.com/u/515035?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mikejohnstn](https://github.com/mikejohnstn)**
_Tuesday Jun 11, 2013 at 00:45 GMT_

---

Like the built-in notes app

**Comment by mgroth0** [comment]
Great app. I started using it on mac and android but then ran into an issue where I needed to see two notes side by side.

Does this being closed mean it's not a planned feature any more?

**Comment by jleandroperez** [comment]
@mgroth0 this one is in our pipeline, but at the moment there's no timeline set!

Thanks for your interest in our app!
