### ISSUE TITLE
Remember cursor position per note

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#60]
<a href="https://github.com/roundhill"><img src="https://avatars.githubusercontent.com/u/789137?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [roundhill](https://github.com/roundhill)**
_Friday Oct 23, 2015 at 20:45 GMT_

---

If you're working on large notes and are switching back and forth between them, the cursor position seems to just stay at where it was in the previous note. 

It'd be handy if we could store the last cursor position for a note and restore it when the note is loaded again.

**Comment by jleandroperez** [comment]
Closing this one as won't fix.
