### ISSUE TITLE
Top of Emoji visible in notes list

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#61]
<a href="https://github.com/roundhill"><img src="https://avatars.githubusercontent.com/u/789137?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [roundhill](https://github.com/roundhill)**
_Tuesday Dec 01, 2015 at 16:26 GMT_

---

Just noticed that if you have an emoji on the third line of a note, it's visible in the list view:

<img width="174" alt="screen shot 2015-12-01 at 8 24 23 am" src="https://cloud.githubusercontent.com/assets/789137/11506629/3a4fda26-9805-11e5-959f-1ed29b73cef5.png">

**Comment by bummytime** [comment]
I'm not sure if there are specific emoji that do this, but when testing SN 1.4.2 on macOS 10.14.4 (Mojave) I cannot see this issue anymore. Closing for now.
