### ISSUE TITLE
Tag list: Tags become unclickable

### ISSUE THREAD

**Issue by coreymckrill** [Automattic/simplenote-macos#614]
Sometimes the tags list becomes unclickable and I can’t switch to a different tag. I can still choose other notes with the same tag. The only fix I’ve found is to quit the app and restart.

### Expected
Clicking on a tag in the tag sidebar changes the list of notes to the ones with that tag.

### Observed
When the app first starts, this works as expected, but then at some point something breaks, and clicking a tag does nothing.

### Reproduced
I haven't been able to find specific actions that cause this to happen. It just seems to happen after the app has been open for a while.

MacBook Pro | MacOS Catalina | Simplenote 1.11.1

**Comment by coreymckrill** [comment]
Noting that this hasn't happened to me so far since upgrading to 1.12.0

**Comment by jleandroperez** [comment]
Thank you for the update @coreymckrill !! Digging into this one today 😄

**Comment by jleandroperez** [comment]
I've been trying to reproduce this one for a loooong time, no success so far.

Closing as cannot repro (1.12), **please by all means** feel free to reopen if needed.

Again, thank you @coreymckrill !!!
