### ISSUE TITLE
All Notes Button Unresponsive Occationally

### ISSUE THREAD

**Issue by sarahfg** [Automattic/simplenote-macos#615]
Issue reported: The all notes button is unresponsive when the user clicks on it.

>sometimes when I click on All Notes, it does nothing. I see it only with last update 

Make|Model|macOS Version|App Version
-|-|-|-
SYSTEM_MAKE|SYSTEM_MODEL|MACOS_VERSION|APP_VERSION
Mac OS|MacBook Pro|10.15.5 |1.11.1

#3169890-zen

Seems similar to this report #614

**Comment by jleandroperez** [comment]
Closing in favor of #614 since indeed both seem heavily related. Thank you Sarah!!!
