### ISSUE TITLE
Add keyboard shortcut shift+tab to unindent list items

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#62]
<a href="https://github.com/eliorivero"><img src="https://avatars.githubusercontent.com/u/1041600?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [eliorivero](https://github.com/eliorivero)**
_Thursday Dec 03, 2015 at 17:33 GMT_

---

This request came in 2445136-t: right now if you're in the line of a list item before the dash (or between the dash and the first word, right before the latter), you can press tab to indent the list item.
However, removing the indentation is done through ⌫ and it could be done through shift+tab which is not used in the editor context.
While this shortcut is not standard to TextEdit or Notes, it is a familiar shortcut to people working with SublimeText, Atom or PhpStorm.

**Comment by bwlang** [comment]
I love this idea - just was about to file it myself ;)

**Comment by roccotripaldi** [comment]
+1

**Comment by msilbers** [comment]
We had a request for this in #1462806-zen as well as a note that it currently works in Windows

**Comment by DanDynamics** [comment]
+1

**Comment by joshyudeep** [comment]
+1

**Comment by codebykat** [comment]
@rralian asked me about this and I was able to verify that this shortcut functionality exists on the web and the Electron app, but not here yet.

**Comment by irkeepin** [comment]
🙏 I miss having this feature every single day 🙏

**Comment by jleandroperez** [comment]
Closing in favor of #864
