### ISSUE TITLE
App ignores OSX scroll bar settings

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#63]
<a href="https://github.com/ashercantrell"><img src="https://avatars.githubusercontent.com/u/13423946?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ashercantrell](https://github.com/ashercantrell)**
_Wednesday Dec 30, 2015 at 23:38 GMT_

---

User e-mailed in and informed me that the OSX Simplenote app ignores the general OSX scrollbars settings, found under System Preferences -> General. 

Steps to replicate:
1. Open OSX's System Preferences pane
2. Click General
3. Change "Show scroll bars" to "Always"
4. Scroll bars still only appear when scrolling in Simplenote app

The scroll bars are still there and can be clicked on as usual, but are invisible unless scrolling. 

t-2473423

**Comment by bummytime** [comment]
**Update 5/14/2019 →** Tested in Simplenote 1.4.2 on macOS 10.14.4 (Mojave) and this issue no longer occurs:

<img width="1052" alt="Screen Shot 2019-05-15 at 2 57 29 PM" src="https://user-images.githubusercontent.com/154014/57805101-da345680-7721-11e9-94aa-981c4b7958f1.png">
