### ISSUE TITLE
New Note is not Visible after doing a Search (on macOS 10.13.6)

### ISSUE THREAD

**Issue by erricgunawan** [Automattic/simplenote-macos#637]
After starting search, pressing the new note button, the new note is not directly visible and editable. We have to start typing for a new search and remove typing to see the new notes.

This happened on macOS High_Sierra 10.13.6 and Simplenote 1.12.0

To be sure, user have removed Simplenote on their macOS High Sierra, download it again, launched, and log in again.

It's working fine on macOS Catalina 10.15.6.

### Expected
After typing in the search field, when pressing the new note button, the new note should be visible on the Note list, and can be edited right away.

### Observed
What happened instead, the New note is not visible. We have to start typing for a new search and remove it to then see the new notes created.

### Reproduced

> 1. Open Simplenote
> 2. Type some word in the Search field
> 3. Click New Note
> 4. No New note in the Note list
> 5. In macOS 10.15.5, the new note appeared in the list, so it can be edited right away.

***(Optional)*** If applicable, add screenshots, animations, or videos to help illustrate your problem.

There's a video that describes the issue well on 3194278-zen

I didn't include the video link here since it may contain some private information.

I couldn't reproduce it on macOS 10.15.5. I don't have 10.13.6 so I couldn't test it.

***(Optional)*** If you reproduced the bug on a specific system, please replace SYSTEM_MAKE, SYSTEM_MODEL, MACOS_VERSION, and APP_VERSION below with the details for that system.  If you reproduced the bug on multiple systems, please add a row for each system.

Make|Model|macOS Version|App Version
-|-|-|-
-|-|High Sierra 10.13.6|Simplenote 1.12.0

**Comment by jleandroperez** [comment]
Closing as cannot repro anymore.

Closed via #626, the entire NotesViewController has been rebuilt, from the ground up.

Thank you Eric!!
