### ISSUE TITLE
User Requests That Failed Searches Start New Note

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#65]
<a href="https://github.com/ChrissiePollock"><img src="https://avatars.githubusercontent.com/u/2545184?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ChrissiePollock](https://github.com/ChrissiePollock)**
_Tuesday Feb 16, 2016 at 19:44 GMT_

---

Their request is: 

> If you type something that is not there, you can hit enter and have a new note created immediately

t-2542252

**Comment by jleandroperez** [comment]
Closing this one as wontfix. Creating new content from the Search Bar is counter intuitive, and will definitely add noise to the flow.

Thank you!
