### ISSUE TITLE
Deleted Content Reappears in Different Note

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#66]
<a href="https://github.com/ChrissiePollock"><img src="https://avatars.githubusercontent.com/u/2545184?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ChrissiePollock](https://github.com/ChrissiePollock)**
_Tuesday Feb 16, 2016 at 21:47 GMT_

---

I was able to replicate this on my MacBook Air using the Simplenote App. 

User writes:
1. Create three notes with content.
2. Select a line of text in Note 1 and press backspace on the keyboard.
3. Open Note 2. Right click (or control-right/two-finger tap) and choose
   "Delete note".
4. This results in Note 3 being shown. Press cmd+z.

The removed text is now unexpectedly inserted in Note 3 (around the same
offset from which it was removed in Note 1).

There is a screencast in the ticket at 2540950

**Comment by bummytime** [comment]
I have tried to repro this a few different ways and was unable to do so. For now, I am going to close this issue, but reserve the right to open it later. 😄
