### ISSUE TITLE
Bug: when copy and pasting lines with markdown tickboxes the tickboxes aren't copied

### ISSUE THREAD

**Issue by JosephMcArthur** [Automattic/simplenote-macos#661]
### Expected

When a tickbox is copied it shows up in pasted text

### Observed

When tickboxes are copied a space is left were the tickbox should be

### Reproduced

This can largely be seen in this [GIF](http://g.recordit.co/EMLPuqjeGR.gif), but:

* use `- [ ]` to generate a tick box
* try and copy that tickbox to a new line
* it will not be copied

Bug seen on:

![image](https://user-images.githubusercontent.com/4953703/91656994-6607f880-eab5-11ea-8d39-1d5a55bd6c88.png)

Simplenote Version 1.12.0

**Comment by eshurakov** [comment]
To add to the issue, I noticed that after copying a checklist, checkboxes transform into some invisible characters in the beginning of the line.

**Comment by rezzap** [comment]
Another user has reported this on two different devices:

1. Macbook Pro 13-inch 2020 Four Thunderbolt 3 ports
mac OS Catalina 10.15.7
Simplenote 2.2

2. Macbook Pro 13-inch 2017 Two Thunderbolt 3 ports
MacOS Mojave 10.14.6
Simplenote 2.0

>When I make a checklist, sometimes I Cut (⌘X) a checklist item and then Paste (⌘V) it to somewhere else in the doc. After I paste, the checkbox turns into an empty space. I then have to convert it to a non-checklist (⌥⌘C), and then convert it back to a checklist again (⌥⌘C) in order to see the checkboxes.

Reported in 3426236-zen
