### ISSUE TITLE
Search for tags

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#67]
<a href="https://github.com/rachelsquirrel"><img src="https://avatars.githubusercontent.com/u/7946521?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rachelsquirrel](https://github.com/rachelsquirrel)**
_Monday Feb 22, 2016 at 12:06 GMT_
_Originally opened as https://github.com/Automattic/simplenote-osx/issues/426_

---

The web app lets you search for tags. It would be great to implement something similar in the Mac app.

ticketid=2551294

**Comment by kcirrr** [comment]
+1

I would like to be able to search for notes without labels.
And it would be great if the tags are included with in the regular search.
For instance when searching for "keyword", notes with "keyword" in the text, but also notes with label "keyword", are included in the search results.

**Comment by supernovia** [comment]
Requested here as well: https://twitter.com/gusparagus/status/896061064751624192

**Comment by jleandroperez** [comment]
Closing in favor of #626. We're building (shortly) a Tag Suggestions UI.

Thanks everyone!
