### ISSUE TITLE
Weird behaviour with Cmd + z and lists

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#68]
<a href="https://github.com/rachelsquirrel"><img src="https://avatars.githubusercontent.com/u/7946521?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rachelsquirrel](https://github.com/rachelsquirrel)**
_Saturday Feb 27, 2016 at 12:48 GMT_

---

Steps to reproduce:
1. Create a list like the following:
- item one
- item two
1. Put your cursor at the start of the first item one and hit enter.
2. Press Cmd + z

Instead of removing the newly created line is crops text from the line below and appends it to the end.

**Comment by bummytime** [comment]
Closing in favor of #129
