### ISSUE TITLE
Force click gesture support for look up / define

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#69]
<a href="https://github.com/jblz"><img src="https://avatars.githubusercontent.com/u/1587282?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jblz](https://github.com/jblz)**
_Tuesday Mar 01, 2016 at 19:50 GMT_

---

On my Macbook Pro, the default gesture for looking up / defining a word is the [force click](https://support.apple.com/en-us/HT204352).
<img width="376" alt="screen shot 2016-03-01 at 2 47 40 pm" src="https://cloud.githubusercontent.com/assets/1587282/13439706/b7351ba6-dfbc-11e5-9d78-cf5258393d02.png">
It seems to work most everywhere else, but not here.

If I change my system setting to the old default, "Tap with three fingers," it works as advertised.

**Comment by bummytime** [comment]
**Update 5/14/2019 →** Tested in Simplenote 1.4.2 on macOS 10.14.4 (Mojave) and this issue no longer occurs. Closing.
