### ISSUE TITLE
Investigate Tag Duplication

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#70]
<a href="https://github.com/jleandroperez"><img src="https://avatars.githubusercontent.com/u/1195260?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jleandroperez](https://github.com/jleandroperez)**
_Friday Mar 11, 2016 at 13:59 GMT_

---

```
1. Open the Mac app.
2. Open a note.
3. Delete the tag.
4. Create a new tag.
It apparently duplicates the deleted tag.
```

Thanks @rachelsquirrel!!

**Comment by gubrist** [comment]
Is there a temporary work-around to get rid of duplicate tags?

**Comment by darrenca** [comment]
Another user reported this issue (#2911147)

1. Delete a tag on a note.
2. Replace it with another existing tag.
3. Tag will appear on the sidebar twice.

**Comment by gubrist** [comment]
I strongly recommend to tag this report as a **Bug**.

**Comment by dmsnell** [comment]
I'm not sure if it's related but I have noticed odd behavior with the tags especially when working across different client apps.

Probably we need some good data documentation because the tags have both a `name` and an `id` and those two often look the same but I have seen tags with the same name appear having different ids (in the form of some hash or UUID)

If we have inconsistent behavior in this then that could be causing tag confusion.

**Comment by labuboco** [comment]
Need improvement. lol

**Comment by gubrist** [comment]
![simplenote-1 1 1-setup_12 12 2017](https://user-images.githubusercontent.com/22197180/33898933-292275b6-df6a-11e7-8e25-0bcc4af35bad.JPG)

Thanks :-)

What has to be done now to erase the duplicated tags?

**Comment by roundhill** [comment]
> What has to be done now to erase the duplicated tags?

I think you'll need to delete both copies of the tag and add them back again... sorry for the inconvenience there.

**Comment by hisyam** [comment]
@gubrist 
> What has to be done now to erase the duplicated tags?

1. Rename the tag to "tag2" or something
2. Delete the duplicated tag
3. Quit the app
4. Rename the tag to the original one

**Comment by gubrist** [comment]
Thanks, hisyam. I have just experienced the following:

1.     In the sidebar, rename the tag to "tag2" or something
---> one of the two tags "Job" renamed to "Job2"
-----> the notes **remained** in the tag "Job2"
-----> the notes **disappeared** in the tag "Job"
2.     Delete the duplicated tag
----> the tag "Job" deleted
3. Quit the app
4. Rename the tag to the original one

**Comment by gubrist** [comment]
The above **changing** procedure worked fine with:
- Windows Desktop (Electron) 

The notes are **displayed** correctly with:
- Windows Desktop (Electron) 
- Android (Version 1.5.7)

But witih **iOS 11.2. (Simplenote Version 4.5.1)**  
with one single tag "Job" any note is displayed at all.
If you search one representative note, which is supposed to be in "Job", using "All Notes" filter  you find the note with tag "Job2". But this tag is no longer existing in the tag list.

**Comment by mgalbritton** [comment]
Another report of this in #1449991-zen.

**Comment by gubrist** [comment]
Update 15.05.2019 → Still an issue in Simplenote Android 1.7.0 or (and) Simplenote Electron 1.5.0.
I am not able to trace which one did cause the Duplicate Tag

**Comment by jleandroperez** [comment]
Closing as cannot repro. Simplenote macOS 2.2.

We've enhanced Tag Validation in #617, duplication should not be an issue anymore. Please reopen if needed.

Thank you 😄
