### ISSUE TITLE
Notifications Prevent Use of Note History

### ISSUE THREAD

**Issue by azollafox** [Automattic/simplenote-macos#700]
### Issue:

When the app is full screen and you click on the 3 dots in the upper right corner then look at the note history, any notifications on your mac will show overtop of the history selector, so you can't use it.

User reported at 3432743-zen

**Comment by jleandroperez** [comment]
Closing this one since notifications can be dismissed (and virtually anything that the system puts on top can block any other button!).

Thank you Sarah!
