### ISSUE TITLE
Investigate: Apple Script Service

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#71]
<a href="https://github.com/jleandroperez"><img src="https://avatars.githubusercontent.com/u/1195260?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jleandroperez](https://github.com/jleandroperez)**
_Friday Apr 01, 2016 at 20:06 GMT_

---

From a user:

```
We received a suggestion to have a service for the mac app that creates a new note in Simplenote (I guess from selected text).
```

**Comment by jleandroperez** [comment]
Closing this one for now. Reopen if needed please!
