### ISSUE TITLE
Renaming a tag doesn't change the tag on the note

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#72]
<a href="https://github.com/rachelsquirrel"><img src="https://avatars.githubusercontent.com/u/7946521?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rachelsquirrel](https://github.com/rachelsquirrel)**
_Thursday Apr 21, 2016 at 06:26 GMT_

---

Steps:
1. Create a new note and add a tag "tag1".
2. Rename tag1 to tag2 using the menu on the left.
3. The tag on the new note remains tag1. 

I'm not sure if this is expected but it doesn't happen in iOS where the tag on the note changes to the new one.

**Comment by mfouladi** [comment]
Found this same issue. But it did update the tag on the file in the web version and closing and reopening the app will update the tag name properly. This is also similar to deleting in the MacOS version. Also trying it a few times and switching between tags when renaming will make it work sometimes.

**Comment by labuboco** [comment]
I have the same problem. Tag's bugs.

**Comment by donat** [comment]
Same here. I'd expect that renaming a tag would update the tags of the existing notes.

**Comment by bummytime** [comment]
**Update 5/14/2019 →** Tested in Simplenote 1.4.2 on macOS 10.14.4 (Mojave) and this issue no longer occurs. Closing for now.
