### ISSUE TITLE
Add Markdown

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#73]
<a href="https://github.com/shawnajean"><img src="https://avatars.githubusercontent.com/u/775884?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [shawnajean](https://github.com/shawnajean)**
_Friday Jun 24, 2016 at 17:57 GMT_

---

This is a pretty common request, though I'm not seeing it on the feature request site.

User requested to be notified when the feature is added: 2712422-t

**Comment by Luminus** [comment]
I'm adding my +1 to this as I'd love to see it happen soon too.

**Comment by cshg** [comment]
+1 from my side as well!

**Comment by rogaha** [comment]
+1

**Comment by mgresko** [comment]
+1

**Comment by Daoro** [comment]
Yes please !

**Comment by titoesteves** [comment]
@roundhill or anyone on Simplenote team. Looking at the amount of thumbs up and comments on this issue, it appears markdown support is one of the most requested features(if not the most requested feature). With that being said, can you provide some sort of ETA when markdown support would be added to the Mac application? Looks like the Simplenote apps for all other platforms have markdown support, so just wondering when Mac would receive the same love.

**Comment by jleandroperez** [comment]
Hello @titoesteves !

I'm sorry to say that, for the time being, this feature isn't being developed, and we cannot really provide an ETA. Thanks for your interest in Simplenote, we'll keep you posted!

**Comment by Bobeta** [comment]
+1 
What's the reason that all the other plattforms have it, except macOS?

**Comment by jleandroperez** [comment]
Hello @Bobeta,

Reason would be: it's a different codebase. Android / iOS / Windows are different apps, with their own implementation.

We'll keep you posted!

**Comment by pauljmartinez** [comment]
+1

**Comment by sebastienmoreno** [comment]
+1
Bear add it, and is pretty similar to Simplenote... But I don't want to switch to Bear because it's not open-source!

**Comment by jojoyuji** [comment]
+1 
Same here @sebastienmoreno! 
Meanwhile I'll be using the webapp version

**Comment by busera** [comment]
+1
I don't want to switch, because Simplenote is available for all the systems, I am using (Android, MacOS, Windows and Linux).

**Comment by gbissland** [comment]
+1 Please

**Comment by eduardozulian** [comment]
912567-zen
