### ISSUE TITLE
Change UI Text Colours 

### ISSUE THREAD

**Issue by SylvesterWilmott** [Automattic/simplenote-macos#733]
Let's change the UI text colours to more closely match the contrast that can be found in macOS system colours:

### Editor

**This includes**
- Title
- Body

**Colours**
- Light: Gray70 (#3c434a)
- Dark: Gray5 (#dcdcde)

 ### Navigation UI

**This includes**
- Tags list + icons
- Selected tag label (shown above the notes list eg. "All Notes")
- Tags within the editor

**Colours**
- Light: Gray90 (#1d2327)
- Dark: Gray5 (#dcdcde)

### Notes List

**This includes**
- Notes list rows titles and body text

**Colours**
Title:
- Light: Gray90 (#1d2327)
- Dark: Gray5 (#dcdcde)

Body:
- Light: Gray50 (#646970)
- Dark: Gray30 (#8c8f94)

### Search Bar

**This includes**
- Search bar placeholder
- Search bar input text

**Colours**
Title:
- Light: Gray50 (#646970)
- Dark: Gray30 (#8c8f94)

Body:
- Light: Gray90 (#1d2327)
- Dark: Gray5 (#dcdcde)

### Other

Change published icon (in the notes list) to:
- Light: Gray50 (#646970)
- Dark: Gray30 (#8c8f94)

Change "TAGS" label in the tags list to:
- Light: Gray50 (#646970)
- Dark: Gray30 (#8c8f94)

**Comment by jleandroperez** [comment]
Thanks for doing this Sly!!

Adding this ticket to the Big Sur refresh master issue.
