### ISSUE TITLE
Apple Silicon version

### ISSUE THREAD

**Issue by jiserra** [Automattic/simplenote-macos#735]
### What
A Simplenote Mac version that works natively on Apple Silicon computers (M1 chip)

### Why
Better performance on Apple Silicon computers

### How
🤷

**Comment by marty331** [comment]
I'm very interested in this also.

**Comment by vladstudio** [comment]
+1!

**Comment by poojashetty18** [comment]
Also requested in #3600711-zen

**Comment by deanjansen** [comment]
+1

**Comment by jleandroperez** [comment]
Closing this one via #802. Shipping in Simplenote mac 2.6.

Thanks everyone for reaching out!

**Comment by jleandroperez** [comment]
P.s.: Thank you @mokagio for adding Apple Silicon support!!

**Comment by mokagio** [comment]
FYI, version 2.6 will not include Apple Silicon support. See [this](https://github.com/Automattic/simplenote-macos/pull/802#issuecomment-765034695) for more details.

We're aiming to ship it with 2.7, which should go out two weeks from now 🤞 . Stay tuned.
