### ISSUE TITLE
Question: Is there a way to get API access for contributors?

### ISSUE THREAD

**Issue by inquisitiveSoft** [Automattic/simplenote-macos#738]
Hello,
Is there a path for new contributors since Simperium isn't offering trial accounts?

I'm an experienced Mac/iOS developer interested in contributing (specifically, thinking of starting with: https://github.com/Automattic/simplenote-macos/issues/716), and have downloaded the code, but am stumped at the login. Are there test api keys available somehow? Alternatively, is there a sensible way to develop without an account/disabling sync?

**Comment by dmsnell** [comment]
Hi @inquisitiveSoft - the project repository should have a Simperium connection configured for the "test backend." If you run the app it should let you create an account. Things should work except for publishing and sharing. Did you try running and using the app as cloned from `git`?

**Comment by jleandroperez** [comment]
Closing this one. Please let us know if anything!
