### ISSUE TITLE
Sidebar Action / Focus Mode

### ISSUE THREAD

**Issue by jleandroperez** [Automattic/simplenote-macos#742]
### Details:
Let's update the Sidebar Toolbar Button so that it deals with (3) states:

1.	Hide the Tags List
2. 	Hide the Notes List
3.	Show tags + notes list

**Plus:** When toggling Focus Mode let's make sure the previous Sidebar state is restored. 

Feedback from one of our awesome users below:

```
 I toggle Focus Mode on and off a ton, however whenever I turn it off, the Sidebar is toggled on, too (I almost never need to see the Sidebar). Can Sidebar visibility be uncoupled from Focus Mode?
```

**Comment by rezzap** [comment]
Some more user feedback on this: 

> Side Bar untoggles every time Focus Mode gets turned off!! I always keep Side Bar toggles and I want it that way so it annoys the heaven out of me to see them expand. I never authorize that! My usage needs this Focus Mode on/off functions for 5-10 times a day so you can imagine the level of frustration.

> (What’s worse is the side bar does not have a toggle button so I have to drug myself to carefully slowly come in between the columns to turn the mouse cursor into column adjustment mode to toggle side bar, or make the lamest journey ever from the app window to the menu bar to toggle once again. Since I use Focus Mode on/off, this journey happen just as often as that! It’s a torture and sin to force the mouse user to do that. My life got better after remembering the shortcut key to toggle but you know what I mean) 

The toggle buton not showing issue has been added here: https://github.com/Automattic/simplenote-macos/issues/759

From 3573636-zen
