### ISSUE TITLE
After relocating search bar, typing in search field does not filter notes list

### ISSUE THREAD

**Issue by JavonDavis** [Automattic/simplenote-macos#757]
Typing in the relocated Search field in the notes editor does not filter notes

### Expected
Notes should be filtered similar to version 2.4

### Observed
Notes were not filtered. 

### Reproduced
From Simplenote app version 2.5 type text into the search field and observe notes are not filtered.

**Comment by jleandroperez** [comment]
Fixed via #740

Thank you Javon!!
