### ISSUE TITLE
The toggle button for Focus Mode is no longer displaying in 2.4

### ISSUE THREAD

**Issue by rezzap** [Automattic/simplenote-macos#759]
A user sent in feedback requesting that the toggle button for Focus Mode be re-added. after updating the app to version 2.4 the option no longer displays and relies on the toolbar action menu item or the hotkey.

### Expected
I'm not sure if this is a bug or a change in UX, but the user expected the option to still be quickly accessible, especially in order to be able to do the switch when holding a mouse. 

### Observed
The icon no longer displays in the note in MacOS, but it still display on the web app. EDIT: What I see on the web app is the sidebar toggle option which seems to work in the same way as the focus mode. Having at least this option would be helpful. 

### Reproduced

![Image 2020-12-16 at 11 27 44 am](https://user-images.githubusercontent.com/10325627/102343040-f9e0d000-3f91-11eb-83b9-7ca8b9d4b7d4.jpg)

Make|Model|macOS Version|App Version
-|-|-|-
Macbook Pro|2019|10.15.7|2.4

User report 3573636-zen

**Comment by jleandroperez** [comment]
Closed via #737.

Shipping in Simplenote mac 2.6. Thank you @rezzap !!
