### ISSUE TITLE
Window bar of the Simplenote app doesn't change to dark mode in High Sierra

### ISSUE THREAD

**Issue by reginabally** [Automattic/simplenote-macos#761]
It was reported in 3573636-zen that the window bar of the Simplenote app doesn't change to black when the "Use dark menu bar and Dock" option is enabled on macOS High Sierra.

### Expected

The user expects the window bar of the Simplenote app to change according to the appearance setting in the macOS.

### Observed

The window bar of the Simplenote app remains as the light color scheme even though the "Use dark menu bar and Dock" option is enabled.

### Reproduced

1. Go to macOS System Preferences > General
2. Enable the "Use dark menu bar and Dock" option
3. See that the window bar of the Simplenote app remains in the original color scheme.

Screenshots can be found on the ticket.

Note that we're not able to reproduce this on macOS Big Sur, Catalina, and Mojave.

Make|Model|macOS Version|App Version
-|-|-|-
Apple|MacBook Pro (Retinar 15-incm Mid 2015)|macOS High Sierra Version 10.136|macOS 2.4

Other specification information of the device:

Processor 2.5 GHz Intel Core i7
Memory 16 GB 1600 MHz DDR3
Startup Disk Machintosh HO
Graphics AMO Radeon Rg M370X 2048 MB
Intel Iris Pro 1536 MB

**Comment by jleandroperez** [comment]
Hi there @reginabally !!

- macOS High Sierra didn't offer support to tint a Window's titlebar
- Our new minimum OS requirement is macOS 10.14 (which properly tints the titlebar!)

(If possible!!) please suggest the user to update the OS to the latest. 

Thank you!!!

**Comment by reginabally** [comment]
Thanks for taking a look, @jleandroperez! The user mentioned they can see the tinted title bar on Firefox and Visual Code Studio (screenshot in the ticket), hence the request.

But we've also let them know we may not be able to fix this at the moment.

**Comment by jleandroperez** [comment]
(There are ways!!) to actually tint it, which involve, essentially, drawing the titlebar by ourselves.

But even so, I'm afraid that we've also dropped support for High Sierra quite recently, so it's a no fix (at least at the moment!!).

Apologies about the bad news @reginabally !!
