### ISSUE TITLE
Strange Behavior in Title Bar with 2.5 on Big Sur

### ISSUE THREAD

**Issue by jkterry1** [Automattic/simplenote-macos#773]
I'm running version 2.5, with the newest big sur release. I'm not 100% sure when this happened, but I believe you guys introduced a regression in 2.5. When I double click on the title bar it no longer maximizes like in all other apps, and the minimize/maximize/close buttons are in the wrong place, shown in screenshot: 
<img width="227" alt="Screen Shot 2020-12-28 at 7 44 36 PM" src="https://user-images.githubusercontent.com/19422700/103251149-78038600-4945-11eb-948f-910b7245fd4c.png">

**Comment by jleandroperez** [comment]
Confirming the missing zoom on double-click is indeed a bug, we'll be working on a fix soon.
As per the Semaphore's location, we've adjusted that in #746 (Shipping soon in Simplenote 2.6).

Thank you @justinkterry for reaching out!!
