### ISSUE TITLE
True distraction-free mode

### ISSUE THREAD

**Issue by mgroth0** [Automattic/simplenote-macos#788]
Giving the user the option to hide the search bar and the two icons next to it (or just hiding them whenever in focus mode) would be nice.

**Comment by jleandroperez** [comment]
Hi there @mgroth0,

As per the next release (2.6 / AppStore) the Search Bar will be visible only after clicking the 🔍 icon. 
(Same behavior as in macOS Big Sur).

Thank you for reaching out!
