### ISSUE TITLE
Can't delete a tag in mac os app.

### ISSUE THREAD

**Issue by scalalang2** [Automattic/simplenote-macos#79]
When I try to delete a tag from left bar. It doesn't work at all. nothing happens.
but iOS works well. and it synchronized immediately.

<img width="258" alt="screen shot 2016-08-25 at 11 21 24 am" src="https://cloud.githubusercontent.com/assets/2603286/17954474/4308d65c-6ab6-11e6-8ef8-d574c41d340a.png">

**Comment by KokkieH** [comment]
Just confirmed this is still an issue in v 1.1.7 while trying to reproduce a different bug.

**Comment by eduardozulian** [comment]
In my case, El Capitan 10.11.6 + Simplenote Version 1.1.7 on allows me to delete tags normally.

**Comment by geekpete** [comment]
I see this behaviour on Sierra 10.12.2 (16C67) with SimpleNote Version 1.1.7 (1170)

**Comment by fditrapani** [comment]
This issue also came up in #3044540-T

**Comment by arunsathiya** [comment]
Noting that I am not seeing any issues with deleting tags on Simplenote for Mac (Simplenote 1.3.8) on macOS 10.14 - Mac OS Mojave. The delete activity works as expected.

**Comment by bummytime** [comment]
Closing.
