### ISSUE TITLE
Make all strings localized

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#8]
<a href="https://github.com/mikejohnstn"><img src="https://avatars.githubusercontent.com/u/515035?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mikejohnstn](https://github.com/mikejohnstn)**
_Monday Jul 15, 2013 at 19:08 GMT_

---

**Comment by jleandroperez** [comment]
Closed via #613
