### ISSUE TITLE
What if the app is responsive to its size.

### ISSUE THREAD

**Issue by scalalang2** [Automattic/simplenote-macos#80]
current version of this app is not responsive to its size.
Its maximum width is over half of the screen. 
so when I use it divided screen it looks like as follow.

<img width="500" alt="screen shot 2016-08-25 at 3 06 56 pm" src="https://cloud.githubusercontent.com/assets/2603286/17958607/1a5362e8-6ad6-11e6-8374-076a196d2826.png">

It's uncomfortable isn't it?
I just have been suggesting it.

**Comment by starpause** [comment]
I hide tags and would prefer to have the search and edit visible when the application is sized to half of the screen. Currently when I set the app to half the screen size (using spectacle) I get only the list of notes.

**Comment by jleandroperez** [comment]
Cannot reproduce anymore. Simplenote is adapting to fullscreen (side by side) without a glitch.

Simplenote 1.11 (shipping soon!) / macOS Catalina.

Thanks everyone!!
