### ISSUE TITLE
App should show the logged in username (email) at least somewhere

### ISSUE THREAD

**Issue by pachlava** [Automattic/simplenote-macos#813]
### What
There is a 'Sign Out' menu item, but there is no way a user on native can see under which account they are currently logged in. At least, I could not find it.

### Why
If app provides means for logging in / logging out, it should provide means to see which user is currently logged in.

### How
Not sure. Fast and dirty - add an email after 'Sign Out' text

**Comment by jleandroperez** [comment]
Closing as dupe, in favor of #64

Thank you @pachlava !!!
