### ISSUE TITLE
[Email Verification] 'Review your account' and 'Verify your Email' screens are too resizeable

### ISSUE THREAD

**Issue by pachlava** [Automattic/simplenote-macos#821]
### Expected
Should not be resizeable at all, or resizing should be wisely limited.

### Observed
Possible to resize the window a lot.

### Reproduced
1. Log in as a user with not verified email
2. See the new 'Review your account' / 'Verify your Email' screens
3. Both screens can be resized quite a bit

https://user-images.githubusercontent.com/73365754/106038557-c50f7f00-60e0-11eb-9a31-0cf88b04ee08.mov

Make|Model|macOS Version|App Version
-|-|-|-
Mac|MBP 16|11.1|2.7

**Comment by jleandroperez** [comment]
Closed via #822. Thank you @pachlava !!
