### ISSUE TITLE
SimpleNote Web - script error

### ISSUE THREAD

**Issue by gubrist** [Automattic/simplenote-macos#83]
The script error appears after some seconds with following web browsers:
- Firefox on Windows 10
- Chrome on Windows 10
- Internet Explorer on Windows 10
- Edge on Windows 10
- iOS on Mac
- Firefox on Andorid

There are NO add-ons etc. installed on my Chrome and Edge browser as I did not use theme before my test.

![script error firefox 14 09 2016](https://cloud.githubusercontent.com/assets/22197180/18515890/2ceee44c-7a97-11e6-98dd-f1cfca9176b0.JPG)

![script error chrome 14 09 2016](https://cloud.githubusercontent.com/assets/22197180/18515900/37bb2b24-7a97-11e6-8955-f371e9636e64.JPG)

![2016-07-22-java android firefox script](https://cloud.githubusercontent.com/assets/22197180/18515909/3f495e42-7a97-11e6-8725-40f91448f997.png)

I have created at two minutes Video;  so you can see the loading progress after start.
After approx. 1000 notes the performance goes down and it freezes:

https://www.youtube.com/watch?v=CxOmOeqR0k4&index=1&list=PL-XYMn1yU1M2LrYuTdnc0dNfUUJPw1_2R

**Comment by bummytime** [comment]
Not a SN macOS issue — closing here.
