### ISSUE TITLE
Double-click on title bar does not respect macOS Dock preferences

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/simplenote-macos#856]
From a user in 3731440-zen:

> Normally, if mac dock preferences are setup right, you should be able to double click the top of an application and have it minimize into the dock. This worked in Simplenote until the last few updates.
Now when I double click the top of Simplenote it maximizes regardless of my dock preference to minimize.

![Screen Shot 2021-02-11 at 11 07 11 AM](https://user-images.githubusercontent.com/1136160/107688212-25c4bd00-6c86-11eb-813d-874162915368.png)

### Expected
That the app respects what double-check should do.

### Observed
It always maximizes the app

### Reproduced
> 1. Open Simplenote
> 2. Double-click on the app title bar

Make|Model|macOS Version|App Version
-|-|-|-
Apple|Mac|11.2.1 Big Sur|2.7
Apple|Mac|10.15.7|2.6

**Comment by erricgunawan** [comment]
Edited above to include the MacOS version (from 3731440-zen)
