### ISSUE TITLE
Shift+Tab should outdent list

### ISSUE THREAD

**Issue by rezzap** [Automattic/simplenote-macos#864]
From a 4* app review:

> I can indent a list like this:
> - My
> 	- List
> ...by hitting tab at the start of the line. But there seems to be no way to un-indent, other than just hitting backspace and then re-starting the list. None of this appears in the menus.

### Expected

I would expect that Shift + Tab would outdent the list similar to how it does on other platforms (electron, web). 

### Observed

There is no way to try and outdent a list item on macOS app.

### Reproduced

> 1. Go to a note and create a new list using `-`
> 2. Click on tab on the next item to indent the next item
> 3. Try to move the tab back to the original list, this isn't working without needing to backspace and start the list fresh

Make|Model|macOS Version|App Version
-|-|-|-
Apple|MacBook Pro 13-inch, 2019|macOS 10.15.7|Simplenote macOS 2.7

**Comment by pachlava** [comment]
@rezzap there's an issue for this here: #62

@jleandroperez @eshurakov: does the backlog allow to have #62 moved from 'Future' milestone to something more close? It's actually requested a lot, here too: p7rJFO-ku-p2 and p7rJFO-sv-p2

It's working in Electron

**Comment by jleandroperez** [comment]
@pachlava Thank you for the heads up!! I'll try to get this done during March's HackWeek!!

🔥

**Comment by sergiou87** [comment]
I couldn't wait anymore and submitted a PR https://github.com/Automattic/simplenote-macos/pull/946 😅

**Comment by jleandroperez** [comment]
Thank you @sergiou87 for addressing this one!
