### ISSUE TITLE
Note still visible when removing it using a different device

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/simplenote-macos#88]
**Steps to reproduce:**
1. Create a note in your Mac app and keep it open
2. Go to your mobile device and trash the note

**What happens:**

When you delete a note on another device but still have this note active on your Mac, it will remove the note from the sidebar, but the content will still be visible.

**Screenshot:** 

<img width="606" alt="simplenote" src="https://cloud.githubusercontent.com/assets/1136160/19819243/80e49f20-9d32-11e6-94fe-5969e205fca1.png">

Reported in 2896537-t

**Comment by arunsathiya** [comment]
Noting that this is still the case on Simplenote for Mac (Simplenote 1.3.8) with macOS 10.14 - Mac OS Mojave. 

## Screenshot indicating this behaviour 

<img width="1012" alt="screenshot 2018-10-15 at 15 40 47" src="https://user-images.githubusercontent.com/18581859/46944855-ddcf0480-d090-11e8-8937-c7b5348a4ced.png">

Here is a screenshot indicating that `First note` delete on Simplenote for Android is removed from the sidebar, but is still showing up on the main view.

## Not the case on Simplenote Electron 

When I deleted the `Second note` as well (which is seen on the previous screenshot) using Simplenote for Android, it was automatically removed from Simplenote Electron as well.

<img width="1136" alt="screenshot 2018-10-15 at 15 42 57" src="https://user-images.githubusercontent.com/18581859/46944929-12db5700-d091-11e8-84f1-1a4a8a96fd10.png">

**Comment by jleandroperez** [comment]
Closing as duplicate, in favor of #28
