### ISSUE TITLE
Email Verification popping up at start - Mac

### ISSUE THREAD

**Issue by marty331** [Automattic/simplenote-macos#896]
<img width="494" alt="Screen Shot 2021-03-03 at 8 19 38 AM" src="https://user-images.githubusercontent.com/663316/109819657-ed1b6200-7bf9-11eb-9d3c-d092bcde4e96.png">

Email verification popping up at start of app (previously verified).  I then see the message "Cannot Confirm Account - please check your network settings and try again."  I am connected to the internet, otherwise how would I have created this bug report.

I'm on Mac, and Simplenote version 2.8.

**Comment by jleandroperez** [comment]
Hello there @marty331,

I'm sorry you're having trouble, we'd very much love to get this fixed ASAP.

- Is it possible you're connecting thru a proxy?
- Would it be possible to check if the issue happens in a different network?

Thanks in advance!

**Comment by marty331** [comment]
> Hello there @marty331,
> 
> I'm sorry you're having trouble, we'd very much love to get this fixed ASAP.
> 
> * Is it possible you're connecting thru a proxy?
> * Would it be possible to check if the issue happens in a different network?
> 
> Thanks in advance!

Actually it's only happening on my work Mac.  I am logged in through a VPN.  I have not seen this happen on my personal Mac.  Do you think that the VPN could be preventing the verification?

**Comment by jleandroperez** [comment]
The **Confirm** button is sending a request over to `https://app.simplenote.com/account/verify-email/`

Are you using the exact same Account in your Work / Personal mac, or it's different accounts?

**Comment by marty331** [comment]
I'm using the same account.  So I just tried sending a request with an app called Insomnia (similar to PostMan) and got access denied.  So this must just be VPN related.  I'll close this issue.  Thank you for the help.

**Comment by jleandroperez** [comment]
@marty331 opening that on the browser should give you a 404 (since it's expecting a POST request), but indeed, access denied sounds like networking glitch.

Please feel free to reopen if needed, thank you for reaching out!
