### ISSUE TITLE
Put add/remove/move animations in tag list, and perhaps note list

### ISSUE THREAD

**Issue by roundhill** [Automattic/simplenote-macos#9]
<a href="https://github.com/mikejohnstn"><img src="https://avatars.githubusercontent.com/u/515035?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mikejohnstn](https://github.com/mikejohnstn)**
_Thursday Jul 18, 2013 at 08:06 GMT_

---

Note list is trickier because it's using bindings, which reportedly don't work well with animations.

**Comment by jleandroperez** [comment]
Closing this one since it's implemented via #532 

(Seriously!!). Thank you all 😄
