### ISSUE TITLE
Tabs do not reach the maximum width of the window

### ISSUE THREAD

**Issue by ashercantrell** [Automattic/simplenote-macos#91]
In the macOS version of Simplenote, tabs (which are the equivalent of five spaces) only fill a partial line before wrapping to the next. Spaces, meanwhile, can cover the entire width of a line and only stop when they reach the edge of the app window.

I made a GIF to show this issue: https://cldup.com/yjyscoMW8k.gif

I was only able to place about 12 tabs (the gif starts a little late) before the cursor wrapped to the next line early, but was able to fill another line all the way to the window edge with spaces.

User-submitted bug, #2907322-t

**Comment by drw158** [comment]
Having trouble seeing the gif. Anyone else?

**Comment by jleandroperez** [comment]
Closing as cannot repro on my end. Plus since it's a really old bug, the GIF isn't available anymore.

Please feel free to reopen if needed, thank you!!
