### ISSUE TITLE
Last character at the end of the line wasn't displayed completely

### ISSUE THREAD

**Issue by reginabally** [Automattic/simplenote-macos#910]
It was reported in 3794675-zd-woothemes that the last character (rightmost) at the end of the line looks cut off. 

### Expected

The user expects to see a complete display of the last character of each of the lines on the note.

### Observed

The last character on the note looks cut off.

### Reproduced

I wasn't able to reproduce this on Big Sur.

Screenshot provided by the user:

![clipping](https://user-images.githubusercontent.com/40906847/110448079-d4301680-80fb-11eb-8aa5-3b141e515a67.png)

Make|Model|macOS Version|App Version
-|-|-|-
Mac mini|Late 2012|Mojave|2.8

I'm asking for the Make and Model of the device.

**Comment by pachlava** [comment]
@reginabally 👋  thanks for creating the issue! It looks like this depends on the 'Show scroll bars' setting (General macOS Settings). I can reproduce the issue on Big Sur 11.2, when the setting is set to 'Always':

<img width="212" alt="Screenshot 2021-03-09 at 12 01 23" src="https://user-images.githubusercontent.com/73365754/110453787-3cb4ce80-80cf-11eb-9521-979415bce9a7.png">

Make|Model|macOS Version|App Version
-|-|-|-
Mac|MBP 16|Big Sur 11.2|2.9 (11223)

**Comment by reginabally** [comment]
@pachlava Great catch! I have the "Show scroll bars" setting set to "Always" on but I need to set the app's "Line Length" option to "Full" and open the app in expanded view to reproducing this. The last character looks fine when it's not on expanded view.

Make|Model|macOS Version|App Version
-|-|-|-
Apple|iMac (Retina 5K, 27-inch, 2019)|Big Sur 11.2.2 (20D80)|2.8

**Comment by erricgunawan** [comment]
Updated the original post with the Make and Model from the user (i.e. 3794675-zen).

**Comment by blakewatson** [comment]
I’m able to reproduce this bug with narrow _or_ full setting on. I also have "Show scroll bars" set to "Always" in System Preferences (I need that for accessibility).

https://user-images.githubusercontent.com/801425/110668452-f162f480-8190-11eb-9824-31d38ebf4f9c.mp4

Make|Model|macOS Version|App Version
-|-|-|-
Apple|iMac (Retina 5K, 27-inch, Late 2015|Big Sur 11.1|2.8

**Comment by iamgabrielma** [comment]
Another case on 3818558-zen 

- MacBook Pro (13-inch, M1, 2020) (8gb, base model)
- Mac OS 11.2.3
- Simplenote 2.9

**Comment by zdenys** [comment]
I'm pasting my case own case from the closed duplicate issue https://github.com/Automattic/simplenote-macos/issues/928

https://user-images.githubusercontent.com/39308239/113307814-369cc100-930e-11eb-986e-c72465d3b6d6.mov

https://user-images.githubusercontent.com/39308239/113308847-3f41c700-930f-11eb-859b-be397f42f645.mov



Make|Model|macOS Version|App Version
-|-|-|-
Apple|MacBookPro 16-inch 2019|Big Sur 11.2.3|2.9

**Comment by rezzap** [comment]
Similar issue reported by a user in 3982211-zen 

I've reproduced this on macOS 10.15.7, 13" MacBook Pro 2019. 
Simplenote 2.11

It's very specific to the width of the window though and will happen only on certain widths. See screenrecording here:

![Screen Recording 2021-05-14 at 11 57 24 am](https://user-images.githubusercontent.com/10325627/118262175-68c44580-b4ac-11eb-9ca9-b010be5120ee.gif)

**Comment by zdenys** [comment]
Asked in p1624099972187800-slack-C036Y8QL4 if this can be prioritized.

**Comment by dandominguez04** [comment]
Another report related to the issue [#4095581-zen](https://woothemes.zendesk.com/agent/tickets/4095581)

<img width="572" alt="Screen Shot 2021-06-25 at 5 03 17 PM" src="https://user-images.githubusercontent.com/81183210/123650151-edb2b680-d7ef-11eb-8b80-1cc327febe6f.png">


- MacOS app
- Simplenote version: 2.13

**Comment by pachlava** [comment]
Also reported in #1048

**Comment by erricgunawan** [comment]
Another report from 4658366-zen:

- Simplenote Version 2.17
- macOS Big Sur Version 11.6
- MacBook Pro (13-inch, M1, 2020)

**Comment by CameronMilliken** [comment]
I use the Mac desktop app for Simplenote, version 2.17. In edit mode, I notice that the last character on a line is often partially or totally clipped. It looks like a typo, and on occasion I've gone back to add the missing character, only to find that it's already there and I've doubled the last character in the word

![screenShot-characterClipping](https://user-images.githubusercontent.com/36011531/181792377-38f6d19e-439b-4e82-b766-cc7dcd33c332.png)

https://woothemes.zendesk.com/agent/tickets/5413739

**Comment by reginabally** [comment]
Another report in 5533472-zd-woothemes:

<img width="1252" alt="image" src="https://user-images.githubusercontent.com/40906847/189264092-a243f6bb-b37d-4299-9db8-51cb2d6f2ce7.png">

**Comment by erricgunawan** [comment]
5789440-zen:

> Mac 10.15.7

> Simple Note cuts off letters from word endings on the right hand side of the screen. I’ve tried resizing the window and toggling side bar to hide/unhide. 

Screenshot is included in the original report.

**Comment by mdrockwell** [comment]
Another report in [the forums](https://forums.simplenote.com/forums/topic/note-text-cut-off-at-right-margin/):

> I’ve been experiencing a problem for a while now where the text of my notes is sometimes cut off at the right margin of the window. the text itself is not altered, but about one half of a character is not visible.

I was able to recreate the issue on macOS 12.6.3 using Simplenote 2.17 with scroll bars set to always show.

**Comment by reginabally** [comment]
Another report in the forums: https://forums.simplenote.com/forums/topic/the-scrollbar-will-fit-over-the-text/

MacOS 13.4.1 (c) (22F770820d)
Simplenote 2.18

**Comment by zdenys** [comment]
I discovered the `Note line length` option in the app settings:

![Pgs9s6.png](https://github.com/Automattic/simplenote-macos/assets/39308239/f0547c1a-9d8a-4a89-96b0-65bd856f682e)

When set to `Narrow`, the note content never touches the edges. Nice!

![wjcH73.png](https://github.com/Automattic/simplenote-macos/assets/39308239/841052bb-c8aa-4108-b89b-125aee419881)

I'm using it as a workaround until this bug is fixed.
