### ISSUE TITLE
Reduce the minimum width of note list pane

### ISSUE THREAD

**Issue by multinegsix** [Automattic/simplenote-macos#915]
### What
***(Required)*** What is the feature you are requesting?  Add a concise description of the feature being requested.

Minor improvement to the UI: Reduce the minimum width of note list pane.

### Why
***(Required)*** Why are you requesting this feature?  Add a concise description of the problem this feature solves.

I notice that in a recent update the minimum width of the note list side got increased. My notes usually have short titles, so it becomes somewhat annoying to see the blank space occupying too much screen area.

### How
***(Optional)*** If applicable, add screenshots, animations, or videos to help illustrate how the feature could be done.

<img width="715" alt="Screen Shot 2021-03-16 at 17 21 21" src="https://user-images.githubusercontent.com/5997909/111396322-0f8e9000-867c-11eb-89c2-406aebbc43c5.png">

Sent out the PR:
https://github.com/Automattic/simplenote-macos/pull/916

**Comment by jleandroperez** [comment]
For the record, pasting the same comment as in #916!

The reason why we needed to set the Notes List minimum width to 300pt is that the Search Bar lives on top of it, and the placeholder itself doesn't fit. This is specially a problem when the Tags List is collapsed, as you can see below.

Thank you for your interest in Simplenote!

<img width="300" alt="Screen Shot 2021-03-17 at 10 26 39 AM" src="https://user-images.githubusercontent.com/1195260/111475641-1238c600-870c-11eb-8f09-1ff5363099e4.png"> <img width="300" alt="Screen Shot 2021-03-17 at 10 26 56 AM" src="https://user-images.githubusercontent.com/1195260/111475656-1533b680-870c-11eb-97b4-e6309812499f.png">

**Comment by multinegsix** [comment]
Thank you @jleandroperez for replying!

Since this feature is unlikely to be reverted or improved in the near future, I wonder if there's any way I can rollback my app to the previous version? I didn't expect this sort of breaking change when I updated Simplenote via AppStore. This change, along with a bug that hides my input method candidate window, makes it almost impossible for me to use Simplenote on my mac at this moment.

**Comment by jleandroperez** [comment]
I'm sorry this is causing you trouble @catfalls !!

Officially speaking, Apple's AppStore does not let you download anything but the latest compatible version for your OS.
Alternatively you could run your own build (you'd need to setup signing certificates).

Now, that being said, we'd love to address the bug that's bothering you. May I trouble you with repro steps? (RE: `bug that hides my input method candidate window```).

**Thanks in advance!!**
