### ISSUE TITLE
Right edge padding/margin partially covers last letters

### ISSUE THREAD

**Issue by zdenys** [Automattic/simplenote-macos#928]
### Observed
In the most recent version, I noticed that the right-side edge padding, next to the vertical scrollbar may cover the last letters on long lines of text. This was not the case a few versions ago from what I recall.

### Expected
See no white margin/padding on the right edge covering any last letters of the row

### Reproduced
1. Add a long text in a new note
2. Try reducing the window width from the right edge
3. Notice that some last letters on lines are covered by the white margin/padding

https://user-images.githubusercontent.com/39308239/113307814-369cc100-930e-11eb-986e-c72465d3b6d6.mov

https://user-images.githubusercontent.com/39308239/113308847-3f41c700-930f-11eb-859b-be397f42f645.mov

Make|Model|macOS Version|App Version
-|-|-|-
Apple|MacBookPro 16-inch 2019|Big Sur 11.2.3|2.9

**Comment by pachlava** [comment]
Thank you for the report @zdenys ! It seems like this looks similar to #910. Feel free to reopen the issue if it's not the case.

**Comment by zdenys** [comment]
Definitely missed that one. Thank you for the fast reply. I added my case to https://github.com/Automattic/simplenote-macos/issues/910 now.
