### ISSUE TITLE
Text Displayed in the List for the Selected Entry Is for a Different Note after Update

### ISSUE THREAD

**Issue by mdrockwell** [Automattic/simplenote-macos#929]
### Expected
When launching Simplenote after an update, the selected note in the list and the note displayed should match.

### Observed
After updating Simplenote for Mac, the note selected in the list and the note displayed do not match.

### Reproduced
1. User updated Simplenote to latest version
2. User launched Simplenote

Screenshots here: 3871472-zd-woothemes

**Comment by rossanafmenezes** [comment]
User provided the following information:

running the latest release version of Big Sur, 11.2.3, on a iMac (Retina 5K, 27-inch, 2019). I’ve also noticed it previously on a MacBook Pro (Retina, 15”, 2013), running Mojave with the most recent Security Update available at the time.

**Comment by jleandroperez** [comment]
Closing as duplicate of #827

Thanks everyone!!
