### ISSUE TITLE
Insert checklist shortcut no longer working.

### ISSUE THREAD

**Issue by liamcrean** [Automattic/simplenote-macos#931]
"Command + Shift + C" worked in previous versions (and is shown as the shortcut in the format menu).

Might be the latest small update to Big Sur? (11.2.1).

Ta

**Comment by pachlava** [comment]
Thank you for the report @liamcrean - could you please specify the version of Simplenote you are using?

**Comment by liamcrean** [comment]
Hi pachlava - 2.9 (latest I can access). Looks like 2.10 is released but not showing in OSX Appstore..?

**Comment by pachlava** [comment]
@liamcrean the shortcut works both in 2.9 and 2.10 on my setup (Big Sur 11.2.3). Does using `Insert Checklist` menu item work in your case? Also, do other shortcuts work, for example, `Cmd+Shift+P` to toggle between preview/edit modes in a note with enabled markdown?

**Comment by liamcrean** [comment]
Hi pachlava. 

Thanks for getting back to me. This isn't a bug. Turns out it was a conflict with another app that I usually have running in the background (_ColorSlurp_ for pipetting screen colours). I should have tried that first - obvious now :)
