### ISSUE TITLE
Add Cmd+F keyboard shortcut

### ISSUE THREAD

**Issue by SylvesterWilmott** [Automattic/simplenote-macos#937]
Add keyboard shortcut Cmd+F to focus search. This shortcut should not affect Cmd+Shift+F. Both shortcuts should do the same.

The reason for this is muscle memory amongst Simplenote platforms and also between Simplenote and other apps.

**Comment by kaushikgopal** [comment]
I believe `⌘ F` currently searches within notes, so this would mean a swap of those keys.

**Comment by SylvesterWilmott** [comment]
Closing this issue with no action since there are some important differences between find and search so it makes sense to keep separate shortcuts for them.

**Comment by codebykat** [comment]
Just noting I found this confusing and thought it was a bug, since I thought we were supposed to have a single unified search UI (find globally and within note are the same on Electron).
