### ISSUE TITLE
Markdown Code Block Does Not Parse Properly

### ISSUE THREAD

**Issue by danielwrobert** [Automattic/simplenote-macos#95]
I noticed in one of my notes that the code blocks are not properly parsing out in the Preview.

The three back ticks before and after the block are still shown in the preview and any headers or other markdown characters are parsed as actual markdown and not as a part of the code.

**Example**

Editor:

<img width="778" alt="screenshot 2016-11-15 10 14 01" src="https://cloud.githubusercontent.com/assets/481776/20311127/98a9ec8a-ab1c-11e6-86c3-c149c6edfb4e.png">

Preview:

<img width="773" alt="screenshot 2016-11-15 10 14 20" src="https://cloud.githubusercontent.com/assets/481776/20311137/a67ce6c8-ab1c-11e6-9f0e-fdfa62b025cc.png">

**Comment by jleandroperez** [comment]
Closing this issue in favor of [this one](https://github.com/Automattic/simplenote-electron/issues/450), since the native Mac App doesn't support Markdown, and this would be an Electron App bug.

Thanks Daniel!

**Comment by danielwrobert** [comment]
My mistake, I saw macos and it didn't register that this repo is meant for the actual native MacOS application. I should have realized!

This is actually an issue I was having with Simplenote in the browser. It looks like you all have that sorted out now.

Sorry about the confusion!

**Comment by jleandroperez** [comment]
No worries at all @danielwrobert!! hope you're doing more than great!
