### ISSUE TITLE
Issues with Note Sync on macOS Sierra 

### ISSUE THREAD

**Issue by deskroid** [Automattic/simplenote-macos#96]
A user reported an issue with the note sync feature, specifically on macOS Sierra. The user has two Mac devices : 1 MBP and 1 Mac Mini, both running macOS Sierra. 

A new note written on the MBP is not being displayed in Mac Mini and vice-versa. The user mentions that the issue occurs only after they updated to macOS Sierra so it seems to be related to the OS itself.

Reference Screenshot : https://cloudup.com/cfsk8M9Ykwn
Ticket Link : https://help.automattic.com/staff/index.php?_m=tickets&_a=viewticket&ticketid=2934016

**Comment by bummytime** [comment]
Closing because of issue age.
