### ISSUE TITLE
Incomplete note title on older versions of macOS

### ISSUE THREAD

**Issue by reginabally** [Automattic/simplenote-macos#973]
It was reported in 4014824-zd-woothemes that the macOS app doesn't show the complete note title. This seems to be happen only on older versions of macOS (e.g. Catalina and Mojave) since we're not able to reproduce this on Big Sur.

### Reproduced

1. Create a note with a title longer than 26 - 27 characters for example `trabalhos Central :: BluAct (Matosinhos)` (this is what the user observed)
2. Notice that the note title doesn't display completely in the app even resizing the app's windows size

Screenshots and video recordings can be found in the ticket.

macOS Version|App Version
-|-
Mojave 10.14.6|2.11
Catalina 10.15.7|2.11

**Comment by eshurakov** [comment]
I think it is the same issue as [this one](https://github.com/Automattic/simplenote-macos/issues/969)

**Comment by jleandroperez** [comment]
Confirming this is indeed the same as #969 (checked the clip in `4014824-zd-woothemes`).

Closing as dupe, thank you Regina!!
