### ISSUE TITLE
Multiple note editor windows

### ISSUE THREAD

**Issue by haszari** [Automattic/simplenote-macos#976]
### What
I would love the ability to edit and view two more notes at the same time. The single-window interface is clean and compact, but sometimes I am working with 2 notes and it's a lot of work to switch between each note.

### Why
I dump a lot of into into notes over the week and later come back and reorganise, pasting things from one raw dumping ground note into other notes focused on a specific area. Having two or more editor/viewer windows would make this much simpler. For long docs, this would preserve scroll position, etc.

### How
- Menu option to open additional windows with note list sidebar and editor pane.
- Tear off an individual note editor to a separate edit/view window (no sidebar).

I'm sure there are lots of ways to accommodate editing multiple notes :)

**Comment by pachlava** [comment]
Thank you, @haszari ! This is one of the requested features, and I have just added your report to our enhancements tracker. While it's on our radar, I can't predict when exactly will it be implemented.

A few things that might help you meanwhile:
- You can install [Simplenote Electron](https://github.com/Automattic/simplenote-electron/releases) on macOS in parallel to native macOS version, and use both simultaneously.
- [Internal linking](https://simplenote.com/2020/11/03/introducing-internal-links/) might also make the process easier, for some cases you mention.

Hope this helps.
