### ISSUE TITLE
Nested lists created with Markdown don't display properly in Chrome

### ISSUE THREAD

**Issue by carladoria** [Automattic/simplenote-macos#98]
User at #2942794-t reported that nested lists are not displayed properly when published. I tested this on Windows (as reported by the user) and also on Mac, both on Chrome. -  On Safari it is working without problems. 

Steps to reproduce:
- Create a markdown list with nested items like:
* eggs
* ham
  * bread
- Publish the note 
- View the published note through the provided link 

Current result:
- The nested list doesn't show properly on the published note (it is shown as part of the main list and not nested)

Expected result
- The nested list should show as in the preview note

**Comment by jleandroperez** [comment]
Hey there @carladoria!

Moved this issue [to this other repository](https://github.com/Simperium/simplenote-gae/issues/142), since here we only track issues that affect the native macOS App.

Hope you're doing more than great,
Thank you!!
