### ISSUE TITLE
Kernel Panic with Simple Note Running

### ISSUE THREAD

**Issue by johnnydhicks** [Automattic/simplenote-macos#981]
### Observed
For the past couple months, I’ve noticed that my MacBook Pro (early 2015) has been having kernel panics while the computer sleeps. It is the same kernel panic each time. 
I called Apple, and they weren’t too helpful. I’ve done my own testing and it seems that the kernel panics only happen when Simplenote is open. If I quit out of the app, the computer sleeps without issue. 

I can send you a copy of crash report that generates each time. I know that I cannot conclude causation, but the two events are certainly correlated and I have many instances of the same issue. There are other people on reddit who have experienced the same kernel panic on the same computer that I have. I do not know if they use Simplenote. 

Make|Model|macOS Version|App Version
-|-|-|-
Apple|MacBook Pro (early 2015)|MacOS 11.4|2.13
[Crash Report 6-23-21.txt](https://github.com/Automattic/simplenote-macos/files/6717670/Crash.Report.6-23-21.txt)

**Comment by jleandroperez** [comment]
Hello there @johnnydhicks,

If you happen to have a Simplenote crashlog, we'd love to take a look. I'm afraid the crash report attached to this issue doesn't provide any leads we could follow.

Thank you for reaching out!

**Comment by johnnydhicks** [comment]
Hi @jleandroperez, 

Just went through Sentry to see if I could locate a crash log for the user but doesn't look like any have been generated. My guess is the user is seeing his computer crash, not the app specifically, so maybe this really isn't enough to go on.

**Comment by jleandroperez** [comment]
Thank you @johnnydhicks. Yes, I'm afraid this is a no go (no stack trace, and no leads in the crashlogs).

Closing this for now, please feel free to reopen if we do manage to get an actual Simplenote crashlog.

**Thank you!**
