### ISSUE TITLE
Syntax Highlighting for Native Apps

### ISSUE THREAD

**Issue by johnnydhicks** [Automattic/simplenote-macos#982]
Please, be as descriptive as possible.  Issues lacking detail, or for any other reason than to request a feature, may be closed without action.

### What
Syntax highlighting for native mobile apps.

### Why
We currently support syntax highlighting in the web app, users would expect to see the same highlighting in native apps.

### How
<img width="846" alt="Screen Shot 2021-06-25 at 2 01 07 PM" src="https://user-images.githubusercontent.com/31710506/123479301-f4f27e00-d5bd-11eb-8e93-b3546f75cb56.png">

**Comment by jleandroperez** [comment]
Adding +1 vote in our internal system, for the `Markdown: code formatting/syntax highlighting` feature.

Thank you for reaching out sir!
