### ISSUE TITLE
No multi-select tag capability

### ISSUE THREAD

**Issue by geekpete** [Automattic/simplenote-macos#99]
Due to the limited import functionality (individual email per note or dropbox shared folder with individual text files per note) there needs to be a way to mass-tag messages after initial import via one of the described import methods.

This would allow a mass import of all notes for a single tag, then selecting them all and assigning the same tag(s) to them all.

Search should also be improved to be able to show all notes NOT matching particular tags to filter out the previously tagged new notes, allowing a second batch of notes to be imported, searched for and mass-tagged with a different tag to the first batch.

**Comment by bummytime** [comment]
Ref: #294
